fix(alert): Ignore ipmi Entity Presence type alert
canonical/hardware-observer-operator pull request #101
Opened 2023-11-14 09:34 UTC by jneo8

Alert rule ipmi_generic_sensor_value ignoe type="Entity Presence"

2023-11-14 15:05 UTC, aieri requested changes
Some minor rewording. Also please add context to this change and the related bug. Why are we doing this? Is this related to https://bugs.launchpad.net/charm-hw-health/+bug/1891915 ?

2023-11-14 15:05 UTC, aieri commented on src/prometheus_alert_rules/ipmi_sensors.yaml
> +          A sensor value, recorded by ipmi sensor, in {{ toLower $labels.state }} state and ignore type Entity Presence.
```suggestion
          A sensor value, recorded by ipmi sensor, in {{ toLower $labels.state }} state. Entity Presence sensors are ignored.
```

2023-11-14 15:05 UTC, aieri commented on tests/unit/test_alert_rules/test_ipmi_sensors.yaml
> +                A sensor value, recorded by ipmi sensor, in warning state and ignore type Entity Presence.
```suggestion
                A sensor value, recorded by ipmi sensor, in warning state. Entity Presence sensors are ignored.
```

2023-11-14 15:05 UTC, aieri commented on tests/unit/test_alert_rules/test_ipmi_sensors.yaml
> +                A sensor value, recorded by ipmi sensor, in critical state and ignore type Entity Presence.
```suggestion
                A sensor value, recorded by ipmi sensor, in critical state. Entity Presence sensors are ignored.
```

2023-11-15 02:18 UTC, Pjack approved these changes

2023-11-15 10:04 UTC, jneo8 commented
> Is this related to https://bugs.launchpad.net/charm-hw-health/+bug/1891915 ?

It's a different case that want to ignore Entity Absent. I would like to put it into another issue.

2023-11-16 05:56 UTC, jneo8 commented
Hi @aieri , I update the wording and put some information on the issue.

2023-11-16 10:53 UTC, aieri approved these changes

2023-11-16 11:14 UTC, merged