Catch `ServerDownOrUnreachableError` in redfish_available function
canonical/hardware-observer-operator pull request #110
Opened 2023-11-17 09:40 UTC by chanchiwai-ray

See PR title.

2023-11-20 01:30 UTC, jneo8 requested changes
In view of the particularity of this charm.

Instead of just catch one more `ServerDownOrUnreachableError`, we should provide a general exception catch to prevent any possible error to crash the install hook.

In this case any error happen when detecting redfish, then we just leave a error msg and disable the redfish.

How do you think?

(Intentionally make install hook fail is also a way, but we should discuss about this.)

2023-11-20 02:16 UTC, chanchiwai-ray commented
we can't catch general exception: `W0718: Catching too general exception Exception (broad-exception-caught)`

2023-11-20 02:39 UTC, Pjack commented
I would like to confirm some hehavior of hardware-observer-operator.

1. If Redfish is temporaray unavailable (e.g. network / hardware issue), will the redfish collector be disabled?
2. After collector is been disabled, when the redfish connection recovered, will the collector be enabled again?
3. What's the behavior of alert?

2023-11-20 02:44 UTC, chanchiwai-ray commented
Ideally, the redfish collector should be temporarily disabled, then when redfish service is recovered, the collector should be automatically enabled. But looking at the code for the charm's life-cycle, in the case you mentioned, it will:

1. exporter will enable the collector `on_config_changed`
2. but the tool will not be installed if it's not installed at the begining.

2023-11-20 02:57 UTC, jneo8 commented
> we can't catch general exception: W0718: Catching too general exception Exception (broad-exception-caught)

It just for linter check. As long as we know what we are doing, we can choose to ignore it.

2023-11-20 10:33 UTC, jneo8 requested changes
Overall LGTM. Only need 1 more line change.

2023-11-20 10:33 UTC, jneo8 commented on src/hw_tools.py
> +        result = False
I would like to provide some logs here.

2023-11-20 11:16 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        result = False
Added

2023-11-20 15:17 UTC, Pjack commented
> Ideally, the redfish collector should be temporarily disabled, then when redfish service is recovered, the collector should be automatically enabled. But looking at the code for the charm's life-cycle, in the case you mentioned, it will:
> 
> 0. tool will not be installed and collector will not be enabled (because of `get_hw_tool_white_list`)
> 1. exporter will enable the collector `on_config_changed`
> 2. but the tool will not be installed if it's not installed at the beginning.

The tool will not be installed => the collector cannot collect data even when it is enabled. 
I think this is a bug. If we do not fix it in this MR, could we raise another issue to track this issue?
Just like you mentioned, In idea case, the collector and the tool should be automatically enabled when the hardware back to normal. 
> 
> Note: this is generic, not specific to redfish

2023-11-21 03:39 UTC, chanchiwai-ray commented
No problem, I opened #114 to track that issue

2023-11-21 06:09 UTC, jneo8 requested changes
The logging level need to be either warning or error.

2023-11-21 06:09 UTC, jneo8 commented on src/hw_tools.py
> +        result = False
The level should be warning or error instead of info.

2023-11-21 06:14 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        result = False
Done, it's because other part of the codes are using `info` when exception happens. I wanted to be consistent.

2023-11-22 02:59 UTC, jneo8 commented
Wait for failed test pass.

2023-11-22 03:35 UTC, jneo8 approved these changes

2023-11-22 03:35 UTC, merged