Enhance charm's life-cycle
canonical/hardware-observer-operator pull request #118
Opened 2023-11-27 04:14 UTC by chanchiwai-ray

2023-11-27 04:15 UTC, chanchiwai-ray commented
Unit test / functional test will be added if the approach is approved

2023-11-27 10:02 UTC, jneo8 requested changes
Some question need more information and discussion.

2023-11-27 12:26 UTC, dashmage requested changes
Apologies in advance for the large number of comments. Overall, I think these are really good changes for hardware-observer and appreciate the time taken to plan and code this out :+1: Lot of my suggestions are just typos or re-wording to comments and doc-strings :)

2023-11-27 12:26 UTC, dashmage commented on src/charm.py
> +    def get_redfish_options(self) -> Dict[str, Any]:
Is it possible to call this `get_redfish_configs` similar to `get_exporter_configs` ? I wouldn't mind if both are using `options` as well, but it would be nice if both are consistent :)

2023-11-27 12:26 UTC, dashmage commented on src/exporter.py
> +        """Validate exporter static and runtime config options."""
nit: small restructure -- "Validate static and runtime config options for the exporter"

2023-11-27 12:26 UTC, dashmage commented on src/hardware.py
> +    pkg = "ipmitool"
Could we refactor the installation of `ipmitool` into a separate method? So this one would only take care of getting the BMC IP address.

2023-11-27 12:26 UTC, dashmage commented on src/hardware.py
> +    """Validate redfish credential by logging in with the credential."""
nit: "Validate redfish credentials by attempting to login with them".

2023-11-27 12:26 UTC, dashmage commented on src/hw_resources.py
> +        self.message = f"{tool}: {path} does not exists"
typo: exists --> exist

2023-11-27 12:26 UTC, dashmage commented on src/hw_resources.py
> +    """Raise if resources is not an executable."""
typo: resources --> resource

2023-11-27 12:26 UTC, dashmage commented on src/hw_resources.py
> +def validate_checksum(support_version_infos: t.List[ToolVersionInfo], path: Path) -> bool:
You could argue that `checksum.py` contains all the checksums for the various resource tools but doesn't need to contain the actual validation logic which could happen elsewhere.

2023-11-27 12:26 UTC, dashmage commented on src/service.py
> +            REDFISH_OPTIONS=redfish_options,
Collecting all the redfish options into one structure is a really good idea :+1:

2023-11-27 12:26 UTC, dashmage commented on src/service.py
> +NUM_RETRIES = 3
We could possible provide some more context to these constants. Maybe:

```python
EXPORTER_HEALTH_RETRY_COUNT = 3
EXPORTER_HEALTH_RETRY_TIMEOUT = 3
```

2023-11-27 12:26 UTC, dashmage commented on src/service.py
> +        is already installed. If it is somehow stopped, we should try to
In what situation would the exporter have been stopped (and not crashed) and require a restart logic to fix it?

2023-11-27 12:26 UTC, dashmage commented on templates/hardware-exporter-config.yaml.j2
> +{% if REDFISH_OPTIONS.get('enable', False)  %}
Should have a hyphen (`-`) before the closing `%`

2023-11-28 02:06 UTC, chanchiwai-ray commented on src/charm.py
> +        self._stored.resource_install_status = resource_install_status
No problem, I personally will never think of `status` with `*Status` (in libjuju) 😆

2023-11-28 02:18 UTC, chanchiwai-ray commented on src/exporter.py
> +"""Exporter relation observer."""
Just to be clear, there is no "3 layers for the charm". Each subclass of `ops.Object` is sort of like a leaf to the `ops.CharmBase`, so there is only 2 layers.

If we choose to combine the `Service(object)` and the relation handler `Observer(ops.Object)` together, then the service class will be like `Service(ops.Object)`, and it's "inheritance", and I used to do [that](https://git.launchpad.net/charm-juju-backup-all/tree/src/exporter.py). But there's no clear "inheritance" between a relation handler and a exporter service. So I chose [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance). However, that's only a benefit on the meaning of code.

The other benefits are:

1. Easier unit test: relation handler is decoupled with whatever service (systemd or snap), so the test for relation handler should be unchanged even if we later switch from a systemd to a snap.
2. Easier to rewrite the exporter from a systemd service to a snap, since they are decoupled.

But that's being said, the benefit is in the future, and not present. If we want to refactor it later, we can still do it later (but I doubt we will do it later)

2023-11-28 02:22 UTC, chanchiwai-ray commented on src/hw_resources.py
> +def validate_checksum(support_version_infos: t.List[ToolVersionInfo], path: Path) -> bool:
`checksum.py` is only the definition of the checksum similar to `config.py`. The main purpose of validating checksum is for the resource, so I put them together.

2023-11-28 02:23 UTC, chanchiwai-ray commented on src/hw_resources.py
> +"""Wrapper for `model.Resources`."""
there are indeed 2 different distinct items + 1 helper: hardware, resources + hw_tool

2023-11-28 02:26 UTC, chanchiwai-ray commented on src/exporter.py
> +        """Return True if cos-agent relation is not zero."""
probably nope, if cos-agent relation is present, then it can mean more than one relations. In which case, we don't want to enable the exporter: #95

2023-11-28 02:28 UTC, chanchiwai-ray commented on src/exporter.py
> +        """Return True if cos-agent relation is not zero."""
Probably the condition is `self.num_relations == 1`: #95

2023-11-28 02:32 UTC, chanchiwai-ray commented on src/hw_resources.py
> +def validate_checksum(support_version_infos: t.List[ToolVersionInfo], path: Path) -> bool:
we can maybe move `checksum.py` to `config.py`, and rename `config.py` to `constants.py`

2023-11-28 02:34 UTC, chanchiwai-ray commented on src/service.py
> +NUM_RETRIES = 3
It's within the context of `service.py`

2023-11-28 02:37 UTC, chanchiwai-ray commented on src/service.py
> +        is already installed. If it is somehow stopped, we should try to
maybe stopped by the operator?

2023-11-28 03:01 UTC, jneo8 requested changes
Add review for `hw_tools.py`

2023-11-28 03:10 UTC, chanchiwai-ray commented on src/hw_tools.py
> +class APTStrategy(APTStrategyABC):
Then I would suggest remove `APTStrategyABC` and `TRPStrategyABC` since they are not useful abstraction. `APTStrategy` and `TRPStrategy` are enough

2023-11-28 03:11 UTC, chanchiwai-ray commented on src/hw_tools.py
> +class TPRStrategy(TPRStrategyABC):
Same here, then I would suggest remove `APTStrategyABC` and `TRPStrategyABC` since they are not useful abstraction. `APTStrategy` and `TRPStrategy` are enough

2023-11-28 04:49 UTC, chanchiwai-ray commented on src/charm.py
>      def _on_remove(self, _: EventBase) -> None:
Currently, there's not remove fail logic in the code

2023-11-28 05:09 UTC, jneo8 commented on src/hw_tools.py
> +        # cache the white list because it might be expensive to get
Instead of cache instead class. A ttl cache or a decorator to decide when to use refresh maybe more make sense?

More to add is making class become `no-status` can ignore a lot of hidden bugs.

2023-11-28 06:14 UTC, chanchiwai-ray commented on src/charm.py
> +                "Exporter crashes unexpectedly, please refer to systemd logs..."
I think keeping it short maybe better since you can't display a long text in `juju status`

2023-11-28 06:26 UTC, chanchiwai-ray commented on templates/hardware-exporter-config.yaml.j2
> +{% if REDFISH_OPTIONS.get('enable', False)  %}
Probably not, the indentation will be wrong:

```
port: 1000
level: debug
enable_collectors:
  - 1
  - 2
  - 3
  redfish_host: ""
redfish_username: ""
redfish_password: ""
```

2023-11-28 07:25 UTC, chanchiwai-ray commented on src/charm.py
> +    def get_redfish_options(self) -> Dict[str, Any]:
it's consistent in a way  that `redfish_options = get_redfish_options()`, but not in `get_redfish_configs` and `get_exporter_configs`. 😢

2023-11-28 07:31 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        # cache the white list because it might be expensive to get
used `cached_property`

2023-11-28 07:32 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    origin_path: Path
reverted

2023-11-28 07:32 UTC, chanchiwai-ray commented on src/hw_tools.py
> +class APTStrategy(APTStrategyABC):
reverted

2023-11-28 07:33 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    def add_repos(self) -> None:
reverted

2023-11-28 07:33 UTC, chanchiwai-ray commented on src/hw_tools.py
> +            self._hw_collector_white_list = collectors
yep, `hw_tool_white_list` only this is expensive, updated

2023-11-28 13:29 UTC, dashmage requested changes
Left some more comments. Overall, I think we could use some nice refactoring with the hardware related modules. `hw_tool.py` looks good adding the validate and install checks directly in the parent strategy classes :+1:

2023-11-28 13:29 UTC, dashmage commented on src/hw_resources.py
> +"""Wrapper for `model.Resources`."""
Here are my thoughts:

## current
### hw_resources.py
- contains exception classes for resource check fails
- utils related to resource file handling eg: `check_file_exists`, `validate_size` etc.

### hardware.py
- constant containing supported raid storages
- utils for general hw checks. eg:  `lshw`, `get_bmc_address`
- utils for hw verification, `{raid,bmc}_hw_verifier}`

### hw_tools.py
- utils related to package management, eg: `install_deb`, `remove_deb`, `check_deb_pkg_installed`
- strategy classes for various tools
- HwToolHelper class


## what i'm proposing

### utils.py
- This will be a general class with util methods contained in these helper classes similar to `HwToolHelper`
  - `ResourceHelper`: This contains mostly the helper methods from `hw_resources.py` -- `check_file_exists`, `validate_size` etc.
  - `PackageHelper` -- will contain all the `apt` and `deb` related functions -- `install_deb`, `remove_deb`, `check_deb_pkg_installed`, `install_apt_package`
  - `HwHelper`: contains helper methods for hardware related tasks. --`lshw`, `get_bmc_address`, `validate_redfish_credentials`
  - `HwVerifier`: contains the "verifier" methods from `hardware.py` and generate the whitelist -- `{raid,bmc}_hw_verifier}`
  - Also exception classes for resource checks. 

### hw_tools.py
- This will now only have the strategy classes + `HwToolHelper` class
  
- The constant containing supported raid storages from `hardware.py` should go into `config.py`/`constants.py`

2023-11-28 13:29 UTC, dashmage commented on src/hw_resources.py
> +def validate_checksum(support_version_infos: t.List[ToolVersionInfo], path: Path) -> bool:
> The main purpose of validating checksum is for the resource, so I put them together.

I agree with this approach. We could possibly rename `checksum.py` to maybe `tool_info.py` since it contains more than the checksums for each of the tools. The checksum validation functionality could go into the `ResourceHelper` class I detailed in my other comment.

2023-11-28 13:29 UTC, dashmage commented on src/service.py
> +        is already installed. If it is somehow stopped, we should try to
Hmm, I wouldn't imagine the operator directly intervening with the lifecycle of the exporter service in the ideal case. Because then the operator would also know to start it back up again. But I can understand than things aren't ideal always and maybe we do need to have restarts to bring up the exporter. But this feels quite "hacky" for some reason.

2023-11-28 13:29 UTC, dashmage commented on src/charm.py
> +    def get_redfish_options(self) -> Dict[str, Any]:
I see, maybe we could have `redfish_configs`, `get_redfish_configs` along with `get_exporter_configs`? What do you think?

2023-11-28 13:29 UTC, dashmage commented on src/hw_tools.py
> +    def check_status(self) -> t.Dict[str, bool]:
`check_status` sounds quite ambiguous. Could we rename this like `check_installed` or `install_status` to make it more clear that this method lets you know if the tool was installed properly or not.

2023-11-29 03:53 UTC, chanchiwai-ray commented on templates/hardware-exporter-config.yaml.j2
> +{% if REDFISH_OPTIONS.get('enable', False)  %}
Yep, it's the same as above. Somehow it thinks the `redfish_host: ""` part of `enable_collectors`

2023-11-29 04:06 UTC, chanchiwai-ray commented
@dashmage , thanks for providing you thoughts, I am not against your idea of re-organizing the code base, but having everything inside a helper module isn't going to make the code base easier to understand (for example, you can broadly break down the code base into `charm.py` and `utils.py`, and put everything unrelated to the charm into `utils.py`), especially when they have clear functionalities and non-trivial lines of code.

That's being said the purpose of this is PR is **not refactoring**, I am only doing the minimal refactoring that allows us to improve the charm's life cycle, makes it easier to debug by simplifying the logic in `charm.py`, and improve the efficiency by reducing the calls to the `get_hw_white_list` to only once. 

Looking back now, I think I can further reduce the refactoring, and leave the code base mostly unchanged at the expense of losing those benefits.

2023-11-29 04:14 UTC, dashmage commented
> @dashmage , thanks for providing you thoughts, I am not against your idea of re-organizing the code base, but having everything inside a helper module isn't going to make the code base easier to understand (for example, you can broadly break down the code base into `charm.py` and `utils.py`, and put everything unrelated to the charm into `utils.py`), especially when they have clear functionalities and non-trivial lines of code.
> 
> That's being said the purpose of this is PR is **not refactoring**, I am only doing the minimal refactoring that allows us to improve the charm's life cycle, makes it easier to debug by simplifying the logic in `charm.py`, and improve the efficiency by reducing the calls to the `get_hw_white_list` to only once.
> 
> Looking back now, I think I can further reduce the refactoring, and leave the code base mostly unchanged at the expense of losing those benefits.

This makes sense, maybe we can take up the refactoring discussion + work in another PR. It's better to have a smaller, clear PR that aims to achieve one thing :+1:

2023-11-29 09:38 UTC, jneo8 commented on src/hw_resources.py
> +def validate_checksum(support_version_infos: t.List[ToolVersionInfo], path: Path) -> bool:
I will still choose to have all the part relate to `checksum` in this module. I don't want to switch between charm to verify the logic of checksum checks.

`constants.py` is somehow bad because we are not just putting *constants* in the config. All the related config or loading functions will be here also. No necessary to split it.

One more thing to add is we would like to have someone easily contribute to the checksum. So intuitively `checksum.py` is the best place.

Sorry, still -1 for this change.

2023-11-29 09:43 UTC, jneo8 commented on src/hw_resources.py
> +"""Wrapper for `model.Resources`."""
I suggest:
- `hw_helpers.py` for all the operation not relate to resource directly, including check file size or build soft-link.
- `hw_tools.py` for all the operation relate to tools.

2023-11-29 09:44 UTC, jneo8 commented on src/charm.py
>      def _on_remove(self, _: EventBase) -> None:
So it just get into error state?

2023-11-29 10:01 UTC, chanchiwai-ray commented
Closing this. Please check out #119 instead

2023-11-29 10:01 UTC, closed without merging

2023-11-29 10:08 UTC, jneo8 commented on src/exporter.py
> +"""Exporter relation observer."""
When I say three layers it's because when we try to debug we still need to check three classes. `charm` -> `exporter` -> `service`. Yes, we have a *composition over inheritance* pattern here but it somehow make it more hard to debugging. For `decoupled` part because we already extract the *service* from *charm*, it's already decoupled from charm. But do we need to decouple `service` from `exporter` life cycle now?

The different of one `service` vs `service` + `exporter` is when we try to switch from systemd to snap:

- `service`: Re-implement the `service`.
- `service` + `exporter`: Re-implement the `service`, but can we ignore the life cycle define in `exporter` in reality?

If you think the answer is yes, then we can keep this design else I suggest to have merge them use mixin.