refactor: Fix alert rules for failed collector.
canonical/hardware-observer-operator pull request #121
Opened 2023-12-01 14:19 UTC by dashmage

Relates to https://github.com/canonical/prometheus-hardware-exporter/pull/54

2023-12-04 14:45 UTC, rgildein reviewed
need informations

2023-12-04 14:45 UTC, rgildein commented on tests/functional/test_charm.py
> +pytestmark = pytest.mark.asyncio(scope="module")
If this is needed due some bug, please add note here.

2023-12-05 01:29 UTC, Pjack approved these changes
Overall, it's good to me. Please add the comment suggested from Robert.

2023-12-05 01:29 UTC, Pjack commented on tests/functional/test_charm.py
> +pytestmark = pytest.mark.asyncio(scope="module")
+1

2023-12-05 02:24 UTC, jneo8 requested changes
LGTM. Just need to remove the line which provide pytest-asyncio fix.

2023-12-05 02:24 UTC, jneo8 commented on tests/functional/test_charm.py
> +pytestmark = pytest.mark.asyncio(scope="module")
The upstream of pytest-operator provides the fix to it 12 hours ago. This line is not needed now.

https://github.com/charmed-kubernetes/pytest-operator/pull/120

2023-12-05 06:10 UTC, chanchiwai-ray commented
Not related to this PR, are we actually perform the static test of the alert rules?

2023-12-05 07:11 UTC, dashmage commented on tests/functional/test_charm.py
> +pytestmark = pytest.mark.asyncio(scope="module")
I've confirmed what @jneo8 has mentioned and with the version pin on `pytest-asyncio`, things look good for us. I'll remove this line and push the change.

2023-12-05 07:18 UTC, dashmage commented
> Not related to this PR, are we actually performing the static test of the alert rules?

If you mean running `promtool`, this is done manually before committing the code currently. There's no automated process in place yet :(

2023-12-05 07:34 UTC, dashmage commented
Update: Functional tests are green, looks good to merge!
[Latest job run](https://github.com/canonical/hardware-observer-operator/actions/runs/7097409972/job/19317515361?pr=121)

2023-12-05 08:23 UTC, rgildein approved these changes
LGTM

2023-12-05 11:44 UTC, jneo8 approved these changes

2023-12-05 11:44 UTC, merged