Separate enabling logic of individual ipmi services monitoring
canonical/hardware-observer-operator pull request #123
Opened 2023-12-04 16:19 UTC by sudeephb

Fixes: #106

2023-12-05 01:38 UTC, Pjack commented
Is it related to any bug?

2023-12-05 02:01 UTC, Pjack requested changes

2023-12-05 02:01 UTC, Pjack commented on tests/unit/test_exporter.py
> +    @mock.patch(
We setup this 2 mock everywhere in test_exporter.py. Is it possible to set up it in setup()? 

@mock.patch("charm.get_bmc_address", return_value="127.0.0.1")
@mock.patch(
        "charm.bmc_hw_verifier",
        return_value=[HWTool.IPMI_SENSOR, HWTool.IPMI_SEL, HWTool.IPMI_DCMI, HWTool.REDFISH],

2023-12-05 02:33 UTC, jneo8 requested changes
Please also add related issue in the pr description.

2023-12-05 02:33 UTC, jneo8 commented on src/hw_tools.py
> +    _name = HWTool.IPMI_SENSOR
**issue:** 

Because this somehow break the design of Strategy. It's really weird to just put `IPMI_SENSOR` here.

I won't ask you to provide a fix here. But please add comments to mention about this. We can provide a refactoring later.

2023-12-05 02:33 UTC, jneo8 commented on src/hw_tools.py
> +        subprocess.check_output("ipmimonitoring".split())
**nitpick:** 

Don't you want to check the output?

2023-12-05 02:33 UTC, jneo8 commented on tests/unit/test_exporter.py
> +    @mock.patch(
+1

2023-12-05 02:43 UTC, jneo8 commented on src/hw_tools.py
> +    _name = HWTool.IPMI_SENSOR
https://github.com/canonical/hardware-observer-operator/issues/124

2023-12-05 17:07 UTC, sudeephb commented on tests/unit/test_hw_tools.py
> +        mock_check_output.assert_has_calls(ipmi_calls)
I added a separate test for a mixture of failures and successes.

2023-12-05 17:08 UTC, sudeephb commented on src/hw_tools.py
> +    _name = HWTool.IPMI_SENSOR
Thanks, I added a comment.

2023-12-05 17:08 UTC, sudeephb commented on src/hw_tools.py
> +        subprocess.check_output("ipmimonitoring".split())
I'm not sure what you mean by checking the output? Do you mean validating the result of the command?

2023-12-06 02:48 UTC, jneo8 commented on src/hw_tools.py
> +        subprocess.check_output("ipmimonitoring".split())
Yes, or we only want to catch subprocess error?

2023-12-06 02:52 UTC, Pjack commented on tests/unit/test_hw_tools.py
> +            mock_apt.add_package.assert_called_with("freeipmi-tools", update_cache=False)
I am not the fan to use "assert_called_with"  or "assert_called". I will only use it when I cannot validate the output. It limits the implementation of the function. Therefore, we may not reuse these unit test when doing refactor internally. The purpose of the unit test is to validate the corresponding output from specific inputs. We don't care how does the function implemented.

Just leave my idea. Nothing needs to be changed. But you can consider to remove these "assert_called" if you agree with me.

2023-12-06 02:55 UTC, Pjack approved these changes

2023-12-06 04:22 UTC, sudeephb commented on src/hw_tools.py
> +        subprocess.check_output("ipmimonitoring".split())
Yes, in this step we only care about the subprocess error. If the command works but there are inconsistencies in the output, the collector logic will take care of it.

2023-12-06 04:23 UTC, sudeephb commented on tests/unit/test_hw_tools.py
> +            mock_apt.add_package.assert_called_with("freeipmi-tools", update_cache=False)
I agree. The `assert_called` lines add no extra advantage, as our tests should pass when the return value is as we want it. I have updated it.

2023-12-06 04:40 UTC, jneo8 approved these changes

2023-12-06 05:14 UTC, dashmage approved these changes
LGTM :heavy_check_mark:

2023-12-06 06:28 UTC, Pjack approved these changes

2023-12-06 08:05 UTC, merged