feat: Add promtool testing in Makefile
canonical/hardware-observer-operator pull request #132
Opened 2023-12-08 12:16 UTC by dashmage

This change adds another make target to run promtool tests and install the prometheus snap (which comes with promtool).

Also fixes a typo in an alert rule test.

Resolves #3

2023-12-08 12:22 UTC, dashmage commented
Turns out the GH job does *not* call the makefile target for `unittests` which was my initial assumption. Would need to create a new tox env for unit tests on the alerts rules and modify the workflow yaml files so that this gets called.

2023-12-08 12:31 UTC, chanchiwai-ray commented on Makefile
> +	@sudo snap install prometheus
I know it's still in draft, but is there a better way to do this without using `sudo` (open question)?

2023-12-11 11:58 UTC, dashmage commented
Got promtool tests to run in a very basic job: https://github.com/canonical/hardware-observer-operator/actions/runs/7167042325/job/19512326718?pr=132

2023-12-11 12:03 UTC, dashmage commented on Makefile
> +	@sudo snap install prometheus
I've made some changes to the GH `check.yaml` workflow now. I am using `sudo` to install the prometheus snap but that's probably the only way to do so. We seem to be using `sudo` in [bootstack-actions](https://github.com/canonical/bootstack-actions/blob/v2/.github/workflows/func.yaml) as well.

2023-12-12 05:55 UTC, chanchiwai-ray commented on Makefile
> +	@sudo snap install prometheus
It's fine in CI since it's temporary environment. But if it's in `Makefile`, someone can accidentally run `sudo` in their local environment if they use password-less `sudo`

2023-12-12 06:45 UTC, chanchiwai-ray commented
LGTM, we can final test alert rules 🥲

2023-12-12 06:50 UTC, rgildein requested changes

2023-12-12 06:50 UTC, rgildein commented on .github/workflows/check.yaml
> +    runs-on: ubuntu-latest
I think that func test should require this job to be finished.
Option1: Unit-lint and this required at the same time in func.
Option2: This require unit-lint job and func require this job.

I vote for option1.

2023-12-12 06:53 UTC, chanchiwai-ray commented on .github/workflows/check.yaml
> +    runs-on: ubuntu-latest
option1 +1

2023-12-12 08:27 UTC, dashmage commented on .github/workflows/check.yaml
> +    runs-on: ubuntu-latest
I'm good with option 1 too which is simpler to understand and works for our purposes. I'll make the changes in the latest commit I'm pushing.

2023-12-12 09:09 UTC, rgildein approved these changes

2023-12-12 10:16 UTC, chanchiwai-ray approved these changes

2023-12-12 16:27 UTC, merged