Feat/hw tool state pattern
canonical/hardware-observer-operator pull request #134
Opened 2023-12-11 10:57 UTC by jneo8

Draft PR without unit test.

---

Store status in the charm `_stored`.

2023-12-11 13:59 UTC, gabrielcocenza requested changes
Hi, I left some comments that I think it can be improved.

I also would like to know why we are using `# type: ignore` in a lot of places of the code.

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        return True
Maybe this would be equivalent?
```suggestion
        return len(self._stored.missing_resources) > 0
```

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        return True
```suggestion
        return len(self._stored.failed_strategies) > 0

```

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        return True
I think we can use `state_missing_resource` and `state_failed_install_strategies` and not repeat the logic
```suggestion
        return self.state_missing_resource or self.state_failed_install_strategies
```

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        return health
We can use walrus notation
```suggestion
        if not health := self.exporter.check_health():
            logger.warning("Exporter health check - failed.")
        return health
```

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +            f" {list(self._stored.installed_strategies)}"  # type: ignore
maybe:

```suggestion
            f" { ', '.join(list(self._stored.installed_strategies))}"  # type: ignore
```

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        return self.state_msg_failed_install_strategies
```suggestion
       return self.state_msg_missing_resources if self.state_missing_resource else  self.state_msg_failed_install_strategies
```

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +            hw_white_list=[],
nit: I think it's preferable using `accept_list` or `allow_list` than `white_list`

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        self._log_stored()
Why here we don't have the same pattern of generating the message and logging as it happens on `state_msg_missing_resources` and `state_msg_failed_install_strategies`?

2023-12-11 13:59 UTC, gabrielcocenza commented on src/charm.py
> +        return f"Missing resources: {list(self._stored.missing_resources)}"  # type: ignore
Maybe using `.join` as the comment bellow

2023-12-11 13:59 UTC, gabrielcocenza commented on src/hw_tools.py
> +            if ok:
`ok` it's not a good variable name and it's not used on other places. I prefer checking directly like `if strategy.check():`

2023-12-11 13:59 UTC, gabrielcocenza commented on src/service.py
> +        success = self.template.render_config(
I don't understand why we are using twice and overriding  the variable `success`.  If this fails it will not be checked and logged

2023-12-11 14:01 UTC, rgildein requested changes
Couple of small comments, but for functionality point of view it looks good to me.

2023-12-11 14:01 UTC, rgildein commented on src/charm.py
> +            logger.info("Get redfish creds." "")
```suggestion
            logger.info("Get redfish creds.")
```

2023-12-12 01:48 UTC, jneo8 commented on src/charm.py
> +            hw_white_list=[],
This terms is been used in whole project now. We can use another PR to replace it.

2023-12-12 01:52 UTC, jneo8 commented on src/charm.py
> +            or len(self._stored.failed_strategies) > 0  # type: ignore
Yes, `StoredState` is not providing type hinting.

2023-12-12 02:00 UTC, jneo8 commented on src/charm.py
> +        return True
I believe the meaning is different here.

2023-12-12 02:04 UTC, jneo8 commented on src/charm.py
> +            f" {list(self._stored.installed_strategies)}"  # type: ignore
We would like to keep `[]` in the msg, so maybe not.

2023-12-12 06:41 UTC, closed without merging

2023-12-12 09:34 UTC, rgildein commented on src/charm.py
> +            or len(self._stored.failed_strategies) > 0  # type: ignore
I think it would be good to report an issue. Those `type: ignore` are enjoying :).