Fix/resoure install failed
canonical/hardware-observer-operator pull request #135
Opened 2023-12-12 07:11 UTC by jneo8

- Remove install retry
- Add cache to hw_white_list to avoid repeat calls
- Fix missing resource failed msg in update status hook

2023-12-12 07:48 UTC, chanchiwai-ray commented
Do you think we should split the PR into two? Adding `lru_cache` is only for optimization I suppose (i.e. not fixing bug)?

2023-12-12 08:03 UTC, Pjack requested changes
Can we assume resource and exporter both should be installed in on_install()
For other hook, we should return directly when resource_installed is false or exporter_enabled is false.

* _on_cos_agent_relation_joined  :  Should we defer the message when resources or exporters are not installed?

* _on_cos_agent_relation_departed:  Should we drop the message if the relation is not existed?

2023-12-12 09:08 UTC, rgildein commented on src/charm.py
> +        if not self._stored.resource_installed:  # type: ignore[truthy-function]
IMO we should use same behavior for other blocked state also, e.g. from line 77

2023-12-12 09:23 UTC, jneo8 commented on src/hw_tools.py
> +@lru_cache
We actually using it multiple times to get the enabled list.

2023-12-12 09:32 UTC, dashmage reviewed
Need some info for the cache. Otherwise, LGTM :smile:

2023-12-12 09:32 UTC, dashmage commented on src/hw_tools.py
> +@lru_cache
Needs info: Could you clarify a bit more on why this cache is needed -- maybe describe the situation when there's a repeat call and the cache would be used? Or link an issue which is resolved by this change?

Also, if we're already caching the result of `get_hw_tool_white_list` which in turn calls the `raid_hw_verifier`, then is there a need to cache the output from `raid_hw_verifier` as well?

2023-12-12 09:32 UTC, dashmage commented on src/hw_tools.py
> +@lru_cache
Same as previous comment -- if we're caching `bmc_hw_verifier` already, do we need to explicitly cache `redfish_available` as well?

2023-12-12 09:33 UTC, dashmage commented on src/hw_tools.py
> +@lru_cache
I see that you've responded to the first part of my question [here already](https://github.com/canonical/hardware-observer-operator/pull/135#discussion_r1423704579).

2023-12-12 09:42 UTC, jneo8 commented on src/hw_tools.py
> +@lru_cache
Because we don't assume user only use `get_hw_tool_white_list`, for example we also use `bmc_hw_verifier` in `charms.py`. Then in this case the cache for `get_hw_tool_white_list` is not been used.

2023-12-12 09:51 UTC, dashmage commented on src/hw_tools.py
> +@lru_cache
That's true, but I was specifically mentioning about the caching for `raid_hw_verifier` and `redfish_available` only which are not used independently but only through either `get_hw_tool_white_list` or `bmc_hw_verifier` respectively.

2023-12-12 09:56 UTC, jneo8 commented on src/hw_tools.py
> +@lru_cache
The effort is really small since the cache will gone after hook finish.

2023-12-12 11:01 UTC, dashmage commented on src/hw_tools.py
> +@lru_cache
Still, it might be misleading because we should only cache a function that requires it.

Anyway, I'll leave the final decision to you. Feel free to resolve this and the other conversation :smile:

2023-12-13 01:51 UTC, jneo8 commented
> 
Do you think we should split the PR into two? Adding lru_cache is only for optimization I suppose (i.e. not fixing bug)?

If you persist I can separate them.

2023-12-13 01:53 UTC, jneo8 commented on src/hw_tools.py
> +@lru_cache
I expect the return value won't change during one hook's execution period. Unless you think it's not True.

2023-12-13 01:57 UTC, chanchiwai-ray commented
> > Do you think we should split the PR into two? Adding lru_cache is only for optimization I suppose (i.e. not fixing bug)?
> 
> If you persist I can separate them.

This is fine for me (i.e. the changes are small, not extra effort to review them together), but I already saw the discussion is going side way: it's suppose to fix installed failed due to `defer` but most discussion is on the cache.

2023-12-13 02:05 UTC, chanchiwai-ray commented on src/charm.py
>              self.model.unit.status = BlockedStatus("Missing relation: [cos-agent]")
I've been thinking about this, should we just remove the logic of starting / stopping exporter when relation join / departed, and just start it right away when the charm is installed. Since this charm depends on multiple things (hardware / resources) already, making it depends on the relation is just adding more points-of-failure. What do you think ?

2023-12-13 04:23 UTC, dashmage commented on src/charm.py
>              self.model.unit.status = BlockedStatus("Missing relation: [cos-agent]")
I agree with you, I don't think it would cause any issue if the exporter were running even without the relation being added. And it would lessen the complexity a bit.

2023-12-13 06:51 UTC, Pjack reviewed
LGTM, but I have my last question about `upgrade` behavior. Please check my inline question. thanks

2023-12-13 06:51 UTC, Pjack commented on src/charm.py
>      def _on_install_or_upgrade(self, event: ops.InstallEvent) -> None:
When we upgrade the charm, should we re-trigger these actions again?
1. hardware-detection 
2. install resource
3. install exporter

IMO, we should do it. 
Please imaging that we may support new hardware type in new version (bugfix), so that we can detect more hardware than before. We may generate more alert rule. We may install new exporter... etc... 
We probaly should reset these flags and restart all these procedures.

    exporter_installed = False
    resource_installed = False
    reset the relation => recreate the alert rule

What's the current behavior we have?

2023-12-14 03:08 UTC, chanchiwai-ray approved these changes
Approved on the basis that this is against a development branch, and we still need second review when merging to main branch. At the meantime, we can still test it and fix any potential issues.

2023-12-14 03:37 UTC, Pjack commented on src/charm.py
>      def _on_install_or_upgrade(self, event: ops.InstallEvent) -> None:
After discussion, we will handle upgrade behavior in another MR.

2023-12-14 03:37 UTC, Pjack approved these changes

2023-12-14 05:24 UTC, merged