Fix: #147
canonical/hardware-observer-operator pull request #148
Opened 2024-01-08 07:14 UTC by honghan-wong

Fix: #147

2024-01-09 11:05 UTC, sudeephb requested changes
Thank you for the change.
Rather than making an exception for `ipmiselcollector`, we could change the alert rule to `for: 1m` for all the collectors. If a collector is really down, it will be down for > 1m anyway.

Do you have any second opinion @jneo8 / @Pjack ?

2024-01-09 12:17 UTC, dashmage requested changes
Thanks for your PR! I've left a few comments :smile:

2024-01-09 12:17 UTC, dashmage commented on src/prometheus_alert_rules/general.yaml
> +      expr: '{__name__=~"(.*)_collector_failed",__name__!="ipmiselcollector_collector_failed"} == 1'
Why is this `ipmiselcollector_collector_failed` instead of `ipmisel_collector_failed`? 

The PRs https://github.com/canonical/prometheus-hardware-exporter/pull/54 and https://github.com/canonical/hardware-observer-operator/pull/121 should've fixed that :/

2024-01-09 12:17 UTC, dashmage commented on src/prometheus_alert_rules/general.yaml
> +            LABELS = {{ $labels }}
I agree with @sudeephb's comment [here](https://github.com/canonical/hardware-observer-operator/pull/148#pullrequestreview-1810921578) and think that it would be nice to make this change for all collectors instead of just `IpmiSelCollector` specifically unless there's a specific collector where this wouldn't work.

2024-01-10 00:52 UTC, honghan-wong commented on src/prometheus_alert_rules/general.yaml
> +      expr: '{__name__=~"(.*)_collector_failed",__name__!="ipmiselcollector_collector_failed"} == 1'
oh well, the deployed hardware observer version is not yet updated to latest and still using the old version. i missed that change.

this is not a valid rules after i update. will revert this naming change

2024-01-10 00:54 UTC, honghan-wong commented on src/prometheus_alert_rules/general.yaml
> +            LABELS = {{ $labels }}
i would love to have all of them to be in a 1 min eval time.
however im not sure if we have any other use case for the 0m?

the `1m` I proposed is for flapping scenario, thus im not sure if that alert is valid across other collector failure as well.

2024-01-10 00:55 UTC, honghan-wong commented on tests/unit/test_alert_rules/test_general.yaml
> +        values: '1x15'
its a redundant, I'll make the change after we have a consensus on the alert eval time.

2024-01-10 04:46 UTC, dashmage commented on src/prometheus_alert_rules/general.yaml
> +            LABELS = {{ $labels }}
> the 1m I proposed is for flapping scenario, thus im not sure if that alert is valid across other collector failure as well.

Do you mean that other collector failures might need greater than `1m`? In which case setting a global `1m` duration would be better than the present `0m`.

Any failure would be valid for > `1m` I'm guessing, so I would like to apply this change globally if no one has any objections.

2024-01-10 06:56 UTC, honghan-wong commented on src/prometheus_alert_rules/general.yaml
> +            LABELS = {{ $labels }}
im +1 for this change, if it only happen in 1 scrape interval, then it most likely is a flapping issue.
i have updated the general collector to `1m` in the next commit.

however if other have any input/suggestion, please let me know so i can update this change.

2024-01-11 13:46 UTC, sudeephb approved these changes
LGTM

2024-01-11 17:34 UTC, dashmage approved these changes
LGTM now. Thanks for making the suggested changes!

2024-01-15 02:47 UTC, Pjack approved these changes

2024-01-15 03:28 UTC, merged