[wip] feat: Add option to provide collectors for hardware dependent tests
canonical/hardware-observer-operator pull request #168
Opened 2024-02-21 12:36 UTC by dashmage

This PR is part of the effort to automate many of the manual tests for hardware observer. These tests depend on the availability of real hardware resources with which the functionality of the charm can be tested. The tests include:

* Check if provided collector is present in the exporter config file
* Verify if metrics are present at the expected endpoint on the unit
* Verify if collector specific metrics (as per the collectors being provided for the tests) are available in the metrics output

Collectors that need to be tested (as per availability on the underlying hardware) can be provided via the `--collectors` flag as space separated arguments. Eg: `--collectors ipmi_sel redfish mega_raid`. These collectors need to belong to a pre-configured list present in `conftest.py`.

The `realhw` marker has also been added to mark the tests which are hardware dependent. If the `--collectors` flag is not provided, then all these tests will be skipped so that only the regular, non-hardware-dependent tests are executed.

2024-02-22 07:37 UTC, sudeephb commented on tests/functional/conftest.py
> +        help="Provide space-separated collectors for testing with real hardware.",
```suggestion
        help="Provide space-separated list of collectors for testing with real hardware.",
```

2024-02-22 07:37 UTC, sudeephb commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
This doesn't verify that the collectors that should be absent aren't absent. We could assert something like 
```
assert set(provided_collectors) == set(config.get("enable_collectors"))
```

2024-02-22 07:45 UTC, sudeephb commented on tests/functional/test_charm.py
> +                parsed_metrics.append(metric)
Nitpick:
What if we store this as a tuple like:
```suggestion
                parsed_metrics.append(tuple(metric.strip().split()))
```
I know that currently the string works, but if we want to validate the metric value (for example, verifying it's a number in a certain range), having it directly readable from a tuple is simpler than parsing from the string.

2024-02-22 08:27 UTC, dashmage commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
There's a small issue with this, let me give an example:

Imagine I am testing only for collectors `redfish` and `mega_raid` only and provide those options to pytest. But if the hardware supports `ipmi_sel` and `ipmi_dcmi` as well, then the above assertion for the exact set of collectors would fail. 

We would have to assume that ALL the collectors supported by the hardware would be provided to pytest which might not always be the case.

2024-02-23 03:35 UTC, dashmage commented on tests/functional/test_charm.py
> +                parsed_metrics.append(metric)
Great suggestion! I'm sure as part of the tests, we'll need to be picking apart not just the metric value but the labels as well. To that extent, I'm in the process of creating a `Metric` dataclass with `name`, `value` and an optional labels. 

For example, `megaraid_physical_drive_info{controller_id="0",drive_type="SSD",enclosure_id="68",slot_id="0",state="Onln"} 1.0` would give me 
```
Metric(name='megaraid_physical_drive_info', labels='controller_id="0",drive_type="SSD",enclosure_id="68",slot_id="0",state="Onln"', value=1.0)
```

If labels is not provided, it will be provided as `None`.

2024-02-26 09:20 UTC, dashmage commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
It's only violating copyright if we redistribute the resources anywhere. But we can possibly have a script that automates downloading them from the various third-party vendor websites. But for now, we could just download them manually and place them in a pre-defined directory that could be picked up as part of the test.

2024-02-26 09:22 UTC, chanchiwai-ray commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
Thanks for clarifying

2024-02-26 09:51 UTC, rgildein requested changes

2024-02-26 09:51 UTC, rgildein commented on tests/functional/conftest.py
> +        results = await SyncHelper.run_command_on_unit(ops_test, unit_name, command)
Why we are using class here? What is benefit over defining the `run_command_on_unit`?

2024-02-26 09:51 UTC, rgildein commented on tests/functional/conftest.py
> +        nargs="+",
It is wise to let user choose two option at once? What if I choose two completely contrary options (maybe I'm wrong and there are not contrary options), e.g.  `mega_raid` and `poweredge_raid`?

2024-02-26 09:51 UTC, rgildein commented on tests/functional/test_charm.py
> +        name = metric.name
also defined parsed_metrics = defaultdict(list) above for loop

2024-02-26 09:51 UTC, rgildein commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
We cannot use unit test here, since we are using pytest. I think that is fine as it's.

2024-02-26 18:07 UTC, dashmage commented on tests/functional/conftest.py
> +        port = 10200
Thanks for the idea! I've raised another PR for this here: https://github.com/canonical/hardware-observer-operator/pull/172

2024-02-26 18:12 UTC, dashmage commented on tests/functional/conftest.py
> +        results = await SyncHelper.run_command_on_unit(ops_test, unit_name, command)
It's just meant to collect the helper functions but I see your point. I can move both the functions out of the class.

2024-02-26 18:15 UTC, dashmage commented on tests/functional/conftest.py
> +        nargs="+",
In our case, there's no contrary options for the user to pick and the design of letting them pick one or more options here is intentional. It's more like letting the users pick the collectors for which they'd like to run the tests (each of which are independent from the other).

2024-02-26 18:20 UTC, dashmage commented on tests/functional/test_charm.py
> +        name = metric.name
Very nice refactor, will make the change :+1:

2024-02-26 18:27 UTC, dashmage commented on tests/functional/test_charm.py
>          await app.reset_config(["exporter-port"])
I agree with your point. Maybe wrapping the assertion statements in a try/finally block would work?

2024-02-27 04:08 UTC, Pjack commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
Sudeep's question is a good question. 
It's important to validate the compatibility of specific hardware. Including
- supported collector should be enabled
- unsupported collector should be disabled.

Right now, the input parameter depends on "human"'s judgement (how many collecter will be test on a specific hardware).
Is it possible that we can handle it in other place or another level to make sure the judgement should be aligned between everyone? No matter I trigger the full functional test or you trigger the full functional test,  we should validate the same collectors on the same machine.

For regular testing (full test), wee can take Sudeep's opinion as the default beahvior. We can create partial test mode if it is neccessary in the future.

2024-02-27 08:30 UTC, rgildein commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
You are suggesting that we automatically found out what collectors are on the machine and run those tests? Since we are getting the machine manually (in script, but not by func tests automatically), I do not see much benefit if that is not easy task, but if we can get such information easily it can be nice.

> No matter I trigger the full functional test or you trigger the full functional test  ...

If you run `tox -e func -- --colector ipmi_sel redfish mega_raid` and I run `tox -e func -- --colector ipmi_sel redfish mega_raid`, we are sure that we are running same tests.

2024-02-27 08:35 UTC, rgildein commented on tests/functional/conftest.py
> +        results = await SyncHelper.run_command_on_unit(ops_test, unit_name, command)
> Edit: I looked at this again and this seems to be done so that we can have an async function be used along with the other synchronous pytest fixtures (we also aren't using pytest-asyncio). The sync fixture `sync_helper` returns the output after executing the methods.

The `sync_helper` is just a placeholder, we are executing with
```python
    results = await sync_helper.run_command_on_unit(ops_test, unit.name, cmd)
```
and we can accomplish same thing with

```python
from .conftest import run_command_on_unit  # maybe moving it to utils make more sense
...

    results = await run_command_on_unit(ops_test, unit.name, cmd)
```

2024-02-27 08:39 UTC, rgildein commented on tests/functional/test_charm.py
>          await app.reset_config(["exporter-port"])
no, we need to use something similar to [`self.addCleanup`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.addCleanup) (I think in pytest only via fixture, but we can define TestCharm as [TestCase](https://docs.python.org/3/library/unittest.html#unittest.TestCase)), at the beginning of the test.

2024-02-27 08:44 UTC, dashmage commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
So after discussing with Eric, Sudeep and James the conclusion was that by default we have to know beforehand what collectors are available for the machine being tested and provided them all as CLI options. If any are missing, then this particular test would fail. This would allow us to test whether the exact collectors are enabled for the machine.

In order to accommodate the situation where we want to test only for a subset of collectors, we can pass another flag (maybe `--allow-partial-collectors` or a better name would work too). This would perform the same check as the already existing code (just checks if provided collector is present in config, if other collectors are also present, it doesn't matter).

What do you think about this?

2024-02-27 12:14 UTC, dashmage commented on tests/functional/test_charm.py
> +            assert f"collector.{collector_name}" in config.get("enable_collectors")
For now, I've made the change so that all collectors enabled in the config file need to be provided to pytest at runtime. The additional flag for testing collectors selectively can be part of another PR if needed.

2024-02-27 12:15 UTC, dashmage commented on tests/functional/conftest.py
> +        results = await SyncHelper.run_command_on_unit(ops_test, unit_name, command)
After going through your suggestion, I've moved the `SyncHelper` methods and the parse metric helper functions to a newly created `utils.py`

2024-02-27 13:33 UTC, dashmage commented on tests/functional/test_charm.py
>          await app.reset_config(["exporter-port"])
I'll create a new issue for this so that we don't lose this improvement.

2024-02-27 14:22 UTC, sudeephb approved these changes
LGTM, thanks.

2024-02-28 09:19 UTC, rgildein approved these changes

2024-02-28 09:24 UTC, dashmage commented
@Pjack , @jneo8 - kindly provide your approval if you think everything looks good now.

2024-02-29 05:23 UTC, jneo8 reviewed
Most LGTM, some non-blocking comments

2024-02-29 05:23 UTC, jneo8 commented on tests/functional/conftest.py
> +def pytest_collection_modifyitems(config, items):
Can you provide more description in the doc-string?

2024-02-29 05:23 UTC, jneo8 commented on tests/functional/test_charm.py
> +class TestCharmWithHW:
non-blocking: The current test structure may not be highly scalable. Adding a specific test case to a hardware tool could complicate the TestCharmWithHW class. However, as we don't use such tests currently, maintaining the status quo is acceptable.

2024-02-29 05:23 UTC, jneo8 commented on tests/functional/utils.py
> +def _parse_single_metric(metric: str) -> Optional[Metric]:
non-blocking: Do we have any prometheus lib can help us for this purpose?

2024-02-29 06:55 UTC, dashmage commented on tests/functional/test_charm.py
> +class TestCharmWithHW:
Adding a specific test case for a collector is also supported by dynamically skipping other tests with `pytest.skip`. This is already done for the `test_collector_specific_metrics` test where if a collector is not present in the set of provided collectors, the test is skipped for that particular collector. Hope I understood your question correctly.

2024-02-29 07:00 UTC, dashmage commented on tests/functional/utils.py
> +def _parse_single_metric(metric: str) -> Optional[Metric]:
Upon checking, I did find [this parser](https://prometheus.github.io/client_python/parser/) on the prometheus_client library docs. But it might not be worth the effort to figure out how it works and adapt it to our specific use case.

2024-02-29 07:02 UTC, dashmage commented on tests/functional/conftest.py
> +def pytest_collection_modifyitems(config, items):
This is actually a default pytest hook function, not my custom function -- https://docs.pytest.org/en/7.1.x/how-to/writing_hook_functions.html. So I think maybe without docstring it's okay since it's pytest itself

2024-02-29 07:07 UTC, merged