fix: support smart array
canonical/hardware-observer-operator pull request #169
Opened 2024-02-22 07:33 UTC by jneo8

Fetch hardware information from hwinfo and add support items

Fix: #90

2024-02-22 07:53 UTC, sudeephb commented on src/hardware.py
> +    Returns:
Nitpick:

It would be nice to have an example input+output pair for the function here as it would make it simpler for future readers to understand.

2024-02-22 07:53 UTC, sudeephb commented on src/hardware.py
> +    """Run hwinfo command and return output as dicturary.
```suggestion
    """Run hwinfo command and return output as dictionary.
```

2024-02-22 08:27 UTC, jneo8 commented
@nishant-dash Can you try to build the charm in your local and try if this fit your needed?

2024-02-23 08:08 UTC, sudeephb approved these changes

2024-02-23 10:27 UTC, Pjack requested changes

2024-02-23 10:27 UTC, Pjack commented on src/hw_tools.py
> +    hwinfo_tools = _raid_hw_verifier_hwinfo()
How about to change the structure as following?
```
lshw_tools = _raid_hw_verifier_lshw()
hwinfo_tools = _raid_hw_verifier_hwinfo()
return list(lshw_tools | hwinfo_tools)
```

2024-02-23 10:34 UTC, err404r commented
I tested it on the affected cloud and could confirm that the fix is working

2024-02-23 13:31 UTC, dashmage reviewed
Overall, some small nits along with some info that would be nice if you could provide.

2024-02-23 13:31 UTC, dashmage commented on tests/unit/test_hardware.py
> +class TestHwinfo:
```suggestion
class TestHwinfo(unittest.TestCase):
```
Should inherit from `unittest.TestCase` to include as part of tests.

2024-02-23 13:31 UTC, dashmage commented on tests/unit/test_hardware.py
> +        "hw_classes,expect_cmd, hwinfo_output,expect",
```suggestion
        "hw_classes, expect_cmd, hwinfo_output, expect",
```
small nit

2024-02-23 13:31 UTC, dashmage commented on src/hardware.py
> +    output = subprocess.check_output(hw_classes, text=True)
```suggestion
    hw_info_cmd = ["hwinfo"] + hw_classes

    output = subprocess.check_output(hw_info_cmd, text=True)
```
It feel more readable to define a separate `hw_info_cmd` variable that would be run by `subprocess.check_output`.

2024-02-23 13:31 UTC, dashmage commented on src/hardware.py
> +        output = _split_at(output, "=========== end debug info ============", 1)[1]
This might be a really dumb question, but why can't we just use 
`output.split("=========== end debug info ============")[1]` over here?

2024-02-26 08:59 UTC, dashmage commented on src/hardware.py
> +    Args:
I see you've changed `_split_at` to use `Args`. I'll mark this as resolved since the main idea was to ensure we're consistent.

2024-02-26 09:04 UTC, dashmage commented on tests/unit/test_hardware.py
> +class TestHwinfo:
Got to know we're using pytest to manage this tests. The other test classes would need to be migrated over too.

2024-02-26 09:09 UTC, dashmage commented on tests/unit/test_hardware.py
> +        "hw_classes,expect_cmd, hwinfo_output,expect",
While [checking the docs](https://docs.pytest.org/en/7.1.x/example/parametrize.html) it does look like no space is the preferred way to separate the parameters. Thanks for verifying and making the correct change!

2024-02-26 09:26 UTC, dashmage approved these changes
Apart from the one comment by Eric, everything else LGTM. Thanks for addressing my comments!

2024-02-26 09:37 UTC, Pjack approved these changes
LGTM

2024-02-26 09:54 UTC, sudeephb approved these changes

2024-02-27 03:36 UTC, merged