Add redfish credential validation in `validate_exporter_configs`.
canonical/hardware-observer-operator pull request #182
Opened 2024-03-04 03:33 UTC by chanchiwai-ray

This PR introduces the validation for the runtime config (i.e. redfish related config) in `validate_exporter_configs` function, and move the charm to `blocked` if the validation did not pass.

Affected event: [install_or_upgrade, update_status, config_changed].

1. `install_or_upgrade`: if during the charm install or charm refresh event, Redfish is detected and the redfish credential is not correct, the charm will be blocked.
2. `update_status`: on every update status, the redfish credential will be validated if Redfish is detected. If it's not valid the charm will be blocked.
3. `config_changed`: on config changed, the redfish credential will be validated if Redfish is detected. If it's not valid the charm will be blocked.

2024-03-04 10:33 UTC, rgildein requested changes

2024-03-04 10:33 UTC, rgildein commented on src/charm.py
> +            redfish_creds = {}
I think it makes sense to move
```python
if not self.redfish_available():
    logger.warning("Redfish unavailable, disregarding redfish config options...")
    redfish_creds = {}
```
to `get_redfish_creds`. It's called get_*, so it's fine that can return empty dict.

2024-03-04 10:33 UTC, rgildein commented on src/charm.py
> +            logger.error("Invalid redfish credentials.")
This is not good log, because if redfish is not available it does not mean the credentials are wrong.

2024-03-04 10:33 UTC, rgildein commented on src/hw_tools.py
> +        logger.info("gw_white_list: %s", hw_white_list)
I think:
```suggestion
        logger.info("hw_white_list: %s", hw_white_list)
```

2024-03-04 10:33 UTC, rgildein commented on src/hw_tools.py
> +    health_check_enpoint = f"https://{bmc_address}:443/redfish/v1/"
question: Why we are not using [`HttpClient`](https://github.com/DMTF/python-redfish-library/blob/9c0e28f7c83b9efe469d9a9150bea1c436a62786/src/redfish/rest/v1.py#L1042)?

2024-03-04 10:33 UTC, rgildein commented on requirements.txt
> +requests
This is already part of redfish client, so is it really needed?

2024-03-04 17:51 UTC, dashmage reviewed
left some comments, thanks for the PR!

2024-03-05 05:28 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        logger.info("gw_white_list: %s", hw_white_list)
Thanks, that's a typo

2024-03-05 05:29 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    health_check_enpoint = f"https://{bmc_address}:443/redfish/v1/"
I will give it a try

2024-03-05 05:48 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    health_check_enpoint = f"https://{bmc_address}:443/redfish/v1/"
I think we can use `HttpClient` but at the expense of unexpected side-effect when there is no redfish service. For example, if we try to initialize the class `c = HttpClient(base_url="....")`, it failed with `redfish.rest.v1.RetriesExhaustedError` without even running `c.get("/redfish/v1/")`. So maybe using `requests` is more clear and simpler in turns of the logic

2024-03-05 06:03 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    health_check_enpoint = f"https://{bmc_address}:443/redfish/v1/"
Done

2024-03-05 06:03 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        response = requests.get(health_check_enpoint, verify=False, timeout=REDFISH_TIMEOUT)
Done

2024-03-05 06:10 UTC, chanchiwai-ray commented on src/charm.py
> +            redfish_creds = {}
Updated

2024-03-05 06:10 UTC, chanchiwai-ray commented on src/charm.py
> +            logger.error("Invalid redfish credentials.")
Yes, now I saw that too

2024-03-05 06:14 UTC, chanchiwai-ray commented on requirements.txt
> +requests
We can at least make it comment about it

2024-03-05 06:14 UTC, chanchiwai-ray commented on src/charm.py
> +    def redfish_available(self) -> bool:
Done

2024-03-05 07:42 UTC, dashmage requested changes
Thanks for addressing my previous comments! I had another pass at the code and wanted to bring up a few, tiny things that popped up.

2024-03-05 07:42 UTC, dashmage commented on src/charm.py
> +    def get_redfish_creds(self) -> Dict[str, Any]:
nit: I was under the assumption that credentials means username, password. This method also returns the address of the redfish service which provides the bmc endpoint. In which case, does it make sense to rename this method to something like `get_redfish_connection_params`? And if so, we could also rename the vars in `validate_exporter_config` as shown below 

```python
        redfish_connection_info = self.get_redfish_connection_info()
        if redfish_connection_info:
            redfish_creds_valid = self.validate_redfish_creds(redfish_connection_params)
```

Just a nitpick and makes it a bit more verbose, feel free to ignore if you disagree.

2024-03-05 07:42 UTC, dashmage commented on tests/unit/test_charm.py
> +        """Test event install when redfish is available but credential is wrong."""
Docstring should be `Test event config changed...`

2024-03-05 07:42 UTC, dashmage commented on tests/unit/test_exporter.py
> +                    COLLECTORS=sorted(["collector.mega_raid", "collector.hpe_ssa"]),
needs info: Why are we sorting a list whose values are already predefined? Wouldn't it make more sense to just set `COLLECTORS` to the value of the output to `sorted(["...", "..."])` which would be `["collector.hpe_ssa", "collector.mega_raid"]`

2024-03-05 23:13 UTC, gabrielcocenza commented on src/charm.py
> +
If you agree with my suggestion above this can be reduced to
```suggestion
        if self.validate_redfish_creds is False:
            logger.error("Invalid redfish credentials.")
            return False, "Invalid config: 'redfish-username' or 'redfish-password'"

```

2024-03-05 23:13 UTC, gabrielcocenza commented on src/charm.py
> +        return result
non-blocker: I don't see the need of accepting a parameter is this function and maybe this can be changed to something like:

```suggestion
    @property
    def validate_redfish_creds(self) -> Optional[bool]:
        """Validate the redfish credentials used by the exporter."""
        creds = self.get_redfish_creds()
        if not creds:
            return None
        redfish_obj = None
        try:
            redfish_obj = redfish_client(
                base_url=creds.get("host", ""),
                username=creds.get("username", ""),
                password=creds.get("password", ""),
                timeout=REDFISH_TIMEOUT,
                max_retry=REDFISH_MAX_RETRY,
            )
            redfish_obj.login(auth="session")
        except InvalidCredentialsError as e:
            result = False
            logger.error("invalid redfish credential: %s", str(e))
        except Exception as e:  # pylint: disable=W0718
            result = False
            logger.error("cannot connect to redfish: %s", str(e))
        else:
            result = True
        finally:
            # Make sure to close connection at the end
            if redfish_obj:
                redfish_obj.logout()

        return result
```

2024-03-06 02:10 UTC, chanchiwai-ray commented on tests/unit/test_exporter.py
> +                    COLLECTORS=sorted(["collector.mega_raid", "collector.hpe_ssa"]),
in general, it's not ideal to compare two list generated by some functions (e.g. `list(some_dict.keys())` == `list(some_other_dict.keys())` because they are not necessarily in the same order. I encountered issues while doing some refactoring before: in that case the collector was coming from `list(set([...])` and the `assert_called_with` failed because they are not in the same order. Nevertheless, I did not add the refactoring here, so the `sorted` seems unrelated here.

2024-03-06 02:13 UTC, chanchiwai-ray commented on src/charm.py
> +    def get_redfish_creds(self) -> Dict[str, Any]:
Yeah, that's definitely make sense, I thought about that too, but decided not to complicate things by renaming it. Since you brought this up I can make the changes requested.

2024-03-06 02:27 UTC, chanchiwai-ray commented on src/charm.py
> +    def get_redfish_creds(self) -> Dict[str, Any]:
Done

2024-03-06 02:29 UTC, chanchiwai-ray commented on src/charm.py
> +        return result
Though it does make the function overloaded with many functionalities, but given the complexity now in `charm.py`. I think it's acceptable to do that.

2024-03-06 02:29 UTC, chanchiwai-ray commented on src/charm.py
> +
Done

2024-03-06 02:34 UTC, chanchiwai-ray commented on tests/unit/test_charm.py
> +        """Test event install when redfish is available but credential is wrong."""
Done, thanks

2024-03-06 03:23 UTC, jneo8 reviewed
non-blocking comments only. Feel free to resolve them.

2024-03-06 03:23 UTC, jneo8 commented on src/hw_tools.py
> +urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
**question (non-blocking):** 

Is disable warning globally here the only way we can have? Won't it have site-effect?

2024-03-06 05:35 UTC, chanchiwai-ray commented on src/hw_tools.py
> +urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
Good question, I guess without it, the juju-log will be full of InsecureRequestWarning. So it's a trade-off, I guess

2024-03-06 06:10 UTC, dashmage commented on src/charm.py
> +        redfish_creds = self.get_redfish_conn_params()
Maybe my [earlier comment](https://github.com/canonical/hardware-observer-operator/pull/182#discussion_r1512250215) can provide some more insight. But essentially, `credentials` would refer to just the user/password to login and having the redfish service URL as well would be better be better identified as "connection parameters".

2024-03-06 06:12 UTC, dashmage commented on src/charm.py
> +        redfish_creds = self.get_redfish_conn_params()
But it does seem confusing to assign this to `redfish_creds`

2024-03-06 06:14 UTC, chanchiwai-ray commented on src/charm.py
> +        redfish_creds = self.get_redfish_conn_params()
Done

2024-03-06 06:20 UTC, dashmage commented on tests/unit/test_exporter.py
> +                    COLLECTORS=sorted(["collector.mega_raid", "collector.hpe_ssa"]),
If we're comparing elements of 2 data structures and we don't want to care about order, a set would make more sense and definitely not a list. If we're not worried about order, we could just do `some_dict == some_other_dict` which compares the keys anyway.

I'm not sure why we'd need to do `list(set([...]))` because that is going from list --> set --> list while a set itself would be fine IMO.

2024-03-06 06:27 UTC, dashmage commented on src/charm.py
> +    def get_redfish_creds(self) -> Dict[str, Any]:
Thanks for also changing the other references and making it more consistent. It looks good now :100:

2024-03-06 06:34 UTC, dashmage approved these changes
LGTM :rocket: Thanks for addressing all my comments and I particularly like the change to `redfish_available` where we're just doing a lightweight GET request to the endpoint instead of trying to do a full-fledged login to check if redfish is present.

2024-03-06 06:49 UTC, Pjack commented on src/hw_tools.py
> +        response = requests.get(health_check_endpoint, verify=False, timeout=REDFISH_TIMEOUT)
Just want to share another trick. 
If we only want to know if a web service available or not, we can consider "HEAD" . It's efficient than "GET".  But it seems we also want to check the data here. So no question here.

2024-03-06 06:50 UTC, Pjack approved these changes

2024-03-06 07:05 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        response = requests.get(health_check_endpoint, verify=False, timeout=REDFISH_TIMEOUT)
Yeah, just to be clear: there aren't any official doc saying that there is health check endpoint for redfish service. But the response from a redfish endpoint is generally a json, so I think we can just try `resp.json()` to see if there are any json output, and if we can decode the response with json. `HEAD` should also provide you response type, but will need extra checks to validate it, but json decode error is already capture inside generic exception

2024-03-06 09:20 UTC, rgildein commented on src/charm.py
> +            redfish_obj = redfish_client(
Some question here as I did in other PR, the redfish_client is connect manager, so why not using it like that without need to define logout in finally?

2024-03-06 09:28 UTC, chanchiwai-ray commented on src/charm.py
> +            redfish_obj = redfish_client(
If `redfish_client` crashes in `__enter__`, it won't `__exit__` 

Example:
```python3
class Foo:

    def __enter__(self):
        print("enter")
        raise KeyError

    def __exit__(self, *args, **kwargs):
        print("exit")

try:
    with Foo() as f:
        print("do something")
except ValueError:
    print("catch ValueErrror")
except Exception:
    print("catch Exception")
```

2024-03-06 10:16 UTC, chanchiwai-ray commented on tests/unit/test_exporter.py
> +                    COLLECTORS=sorted(["collector.mega_raid", "collector.hpe_ssa"]),
I've removed it

2024-03-06 10:48 UTC, rgildein commented on src/charm.py
> +            redfish_obj = redfish_client(
The __enter__ is doing only logging and if that failed do you really need to do logout? If yes, I think that should be reported as a bug.

2024-03-06 15:02 UTC, gabrielcocenza commented on src/charm.py
> +            redfish_obj = redfish_client(
I agree with Robert. I think this is a bug on redfish client and a bug should be raised. If the enter method can raise an exception, it should handle it. E.g:

```python3
import sys

class DummyContextManager:
     def __enter__(self):
        print('Entering...')
         try:
            raise ValueError("Not valid")
        except:
            # Ignore if __exit__ returns a True value
            if self.__exit__(*sys.exc_info()):
                 pass
             else:
                 raise

    def __exit__(self, exc_type, exc_value, traceback):
        print('Exiting...')

with DummyContextManager() as d:
     pass

```
You would see
```
Entering...
Exiting...
```

2024-03-06 22:29 UTC, rgildein submitted a review, later dismissed

2024-03-07 01:26 UTC, chanchiwai-ray commented on src/charm.py
> +            redfish_obj = redfish_client(
> The enter is doing only logging and if that failed do you really need to do logout? If yes, I think that should be reported as a bug.

As I mentioned in another PR's description, Yes, you **might** need to `logout` but you probably can't if `login` failed because of timeout (I did not verify this but I suspect it, also this is another story). It's not necessary a bug, it can be a choice of yours. For example if you set a login timeout to 1s, and you think your server can handles the login in 1s, that's fine. However, if the server take too long to respond (say 5s), then `redfish_client` raise time out exception, and can't handle the response which sets the `self.__session_key`. In that case, even if we do `redfish_client.logout` it will do nothing.

> I agree with Robert.  ....

Yes, that should be handled in `redfish_client` itself, we can report it as an issue. But I don't think we need to use context manager in this case because we don't need "context": we only need to explicitly run `login` and see if it's working or it raises exception (in some sense, if upstream did fix the issue, we can't do validation here because it will not raise exception). For example:

```python3
try:
    with redfish_client(...) as helper:
        pass # or do logging
        # we don't need to do anything with the context: "helper"
except ...:
    result =False
except ...:
    result =False
```
so you will have an empty `with` block, IMHO, this is even more confusing

2024-03-07 15:03 UTC, gabrielcocenza approved these changes

2024-03-08 01:20 UTC, merged