tests: Collector specific tests for real hw
canonical/hardware-observer-operator pull request #183
Opened 2024-03-04 06:21 UTC by dashmage

Adds collector specific tests most notably for redfish.

For the redfish test, two new env vars are introduced for the username and password credentials. After successful authentication to the redfish service, the redfish specific metrics are fetched.

Also fixes "ipmi_sensor" typo in `parse_metrics` function and `test_collector_specific_metrics_available`.

The documentation for letting the user know that they have to add these env vars for redfish will come as part of a later PR which will cover all prerequisite steps for real h/w testing.

2024-03-04 07:37 UTC, Pjack approved these changes
LGTM

2024-03-05 04:25 UTC, dashmage commented on tests/functional/test_charm.py
> +                assert metric.value == 0.0, f"{metric.name} value is incorrect"
You're right, good catch.

2024-03-05 09:49 UTC, Pjack submitted a review, later dismissed

2024-03-05 12:43 UTC, dashmage commented
Rebased changes from master branch

2024-03-06 03:03 UTC, Pjack approved these changes

2024-03-06 03:13 UTC, jneo8 requested changes

2024-03-06 03:13 UTC, jneo8 commented on tests/functional/test_charm.py
> +    async def test_redfish_metrics(self, ops_test, app, unit, provided_collectors):  # noqa: C901
**suggestion (blocking):** 

The test function's name does not clearly indicate it's for real hardware testing. Prefixing it could unify and clarify its purpose as part of a series of hardware-related tests

2024-03-06 03:13 UTC, jneo8 commented on tests/functional/test_charm.py
> +        try:
**nitpick (non-blocking):** 

Maybe you want to check if the service is in active status instead of querying the endpoint?

I saw we assign the result variable in the retry block and used later for checking. More clearly, we can re-write this part like below:

```python
try:
    (check service available)
except:
    pytest.fail()
    
result = get_metrics_from_endpoint()
```

2024-03-06 05:05 UTC, dashmage commented on tests/functional/test_charm.py
> +    async def test_redfish_metrics(self, ops_test, app, unit, provided_collectors):  # noqa: C901
This test belongs to the `TestCharmWithHW` class in which all the tests are hardware dependent and require real hardware for testing. This is also signified by the "realhw" marker attached to the class (which would extend it to all the tests as well).

So, none of the tests in this class have any explicit mention of requiring real hardware since it's implied by belonging to the class itself.

2024-03-06 05:36 UTC, jneo8 commented on tests/functional/test_charm.py
> +    async def test_redfish_metrics(self, ops_test, app, unit, provided_collectors):  # noqa: C901
Ok that make sense now, thanks for explain about this.

2024-03-06 06:12 UTC, sudeephb approved these changes
LGTM

2024-03-06 17:16 UTC, dashmage commented on tests/functional/test_charm.py
> +        try:
For some reason, while trying this even after the service was active the curl command for metrics didn't go through during my tests. So I was retrying directly for the results itself since that's what we're finally testing with

2024-03-06 17:22 UTC, dashmage commented
Had to rebase from master again due to new changes

2024-03-06 21:33 UTC, gabrielcocenza submitted a review, later dismissed

2024-03-06 21:33 UTC, gabrielcocenza commented on tests/functional/test_charm.py
> +        results = await get_metrics_output(ops_test, unit.name)
Why not change the output of `get_metrics_output` to already return the result parsed?
The `return-code` could also be part of it and I guess it would cover all use cases.

This would avoid of always getting the result and then transform into a format that is more usable for the tests

2024-03-06 21:33 UTC, gabrielcocenza commented on tests/functional/test_charm.py
> +            if metric.name == "redfish_service_available":
I have some questions:
Should this test pass if there is no `redfish` on the parsed_metrics?
Would be ok if this metric changes the name in the upstream code, not be checked and still pass the tests?

2024-03-06 21:33 UTC, gabrielcocenza commented on tests/functional/test_charm.py
> +                assert metric.value == 1.0, f"{metric.name} should be 1.0 after login."
Those asserts are very repetitive, and I think using the [keyword class pattern](https://peps.python.org/pep-0622/#class-patterns) is a good thing here. You could do something like this:

```python
def _assert_metric(metrics, name, value):
    result = []
    for metric in metrics:
        match metric:
            case Metric(name=name, value=value):
                result.append(metric)
    assert len(result) == 1
```

And then
```python
_assert_metric(parsed_metrics.get("redfish"), "redfish_call_success", 1.0)
```

2024-03-06 23:17 UTC, gabrielcocenza reviewed
My comments are not blockers, just suggestions

2024-03-06 23:17 UTC, gabrielcocenza commented on tests/functional/test_charm.py
> +                assert metric.value == 1.0, f"{metric.name} should be 1.0 after login."
Actually I discovered that unfortunately my suggestions does not work inside a function.
Something like this would work, but it needs to be hardcoded which adds little value:

```python
for metric in parsed_metrics.get("redfish"):
    expected_result = []
    match metric:
        case Metric(name="redfish_call_success", value=1.0):
            expected_result.append(metric)
        case Metric(name="redfish_service_available", value=1.0):
            expected_result.append(metric)
    assert len(expected_result) == 2
```
But in any case, transforming those asserts into a function would avoid repetitive code.

2024-03-07 04:54 UTC, dashmage commented on tests/functional/test_charm.py
> +        results = await get_metrics_output(ops_test, unit.name)
That's actually a really nice idea, thanks for the suggestion. I'll implement this.

2024-03-07 04:58 UTC, dashmage commented on tests/functional/test_charm.py
> +            if metric.name == "redfish_service_available":
Hmm, I hadn't thought of that. The test shouldn't pass if there isn't redfish in the parsed_metrics. If the redfish collector is enabled we expect to see redfish metrics. Thanks for pointing it out, I'll add a check that fails the test in case redfish isn't present in parsed_metrics.

2024-03-07 05:49 UTC, dashmage commented on tests/functional/test_charm.py
> +                assert metric.value == 1.0, f"{metric.name} should be 1.0 after login."
Appreciate the thoughtful insights here. The only issue I see with just checking the number of expected results is that we aren't exactly sure which metric is the one that has the wrong value. 

But I do think there's value in moving the repetitive asserts into a function - I can change the assertion fail log in one place which is a nice benefit.

```python
def assert_metric(metrics, name, value):
    for metric in metrics:
         if metric.name == name:
              assert metric.value == value, f"wrong value"

# call the function
assert_metric(parsed_metrics, "redfish_call_success", 1.0)
```
For such a simple case, the `match` syntax adds extra verbosity so I've just decided to keep the if statements here.

The structural pattern matching PEP was a good read as well :+1:

2024-03-07 09:40 UTC, dashmage commented on tests/functional/test_charm.py
> +        try:
In the [latest commit ](https://github.com/canonical/hardware-observer-operator/pull/183/commits/766ec8589708c64dd21b48dc3e9ad68ab5c1b110) I've reduced the complexity of the retry block by creating a custom exception that would be raised when the metrics are not able to be fetched.

2024-03-07 09:44 UTC, jneo8 approved these changes

2024-03-07 11:35 UTC, Pjack commented on tests/functional/test_charm.py
> +        results = await get_metrics_output(ops_test, unit.name)
Sorry that I close this conversation behave of @gabrielcocenza . 
Ashley is not available tomorrow and since the code was been revised, it's reasonable to close it.

2024-03-07 11:37 UTC, Pjack commented on tests/functional/test_charm.py
> +            if metric.name == "redfish_service_available":
Sorry that I close this conversation behave of @gabrielcocenza . 
Ashley is not available tomorrow and since the code was been revised, it's reasonable to close it.

2024-03-07 12:01 UTC, sudeephb approved these changes
LGTM, thanks.

2024-03-07 13:14 UTC, merged