Deploy environment for integration tests with COS
canonical/hardware-observer-operator pull request #185
Opened 2024-03-05 12:05 UTC by sudeephb

This deploys a lxd model and a k8s model on pre-existing lxd and microk8s controllers. On those models, Hardware Observer and COS are deployed.
The CI configuration to create the controllers will be created as a separate PR,. The current version works as is with environment variables(`LXD_CONTROLLER` and `K8S_CONTROLLER`) passed for the corresponding controller names.
The actual tests will also be implemented in a separate PR.

2024-03-06 02:38 UTC, jneo8 requested changes
The direction seems ok to me. Just some nitpicks and questions. Please see my inline comments.

2024-03-06 02:38 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +    lxd_ctl_name = os.environ["LXD_CONTROLLER"]
**suggestion (non-blocking):** 

This is a very important information we should know before running the test, maybe you want to change it as global immutable variable instead of hiding inside this function.

2024-03-06 02:38 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +async def _deploy_cos(ops_test, series, channel, k8s_ctl, k8s_mdl):
**nitpick (blocking):** 

Please consider to add doc-string for this function and could you explain why you choose to run juju command with subprocess instead of using pytest-operator?

2024-03-06 02:38 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +async def _deploy_hardware_observer(ops_test, series, channel, lxd_mdl):
**nitpick (blocking):** 

Need doc-string here.

2024-03-06 02:38 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +async def _add_cross_controller_relations(ops_test, series, channel, k8s_ctl, k8s_mdl, lxd_mdl):
**nitpick (blocking):** 

Need doc-string here.

2024-03-06 02:38 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +    lxd_mdl = await get_or_add_model(ops_test, lxd_ctl, lxd_mdl_name)
**question (non-blocking):** 

Any reason the model will exists before running the test?

2024-03-06 02:38 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +
**nitpick (non-blocking):** 

You probably want to add a simple check here to confirm the environment is ready.

2024-03-06 09:02 UTC, rgildein submitted a review, later dismissed

2024-03-06 09:02 UTC, rgildein commented on tox.ini
> +    pytest {toxinidir}/tests/integration -vv --log-cli-level=INFO -s {posargs}
not-blocking:
```suggestion
    pytest {toxinidir}/tests/integration {posargs:-s -vv --log-cli-level=INFO}
```

2024-03-06 09:02 UTC, rgildein commented on tox.ini
> +    sh -c 'if [ -z "$K8S_CONTROLLER" ]; then echo "The K8S_CONTROLLER variable must be set."; exit 1; fi'
Now I see you are checking env here, but we should rather to it in Python, because we can run test with pytest directly without using tox.

2024-03-06 09:26 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    )
>Also we want to tests hw-observer from charmhub? Like this, every week we will test same version, it will be the edge channel?

Yes, the default for channel option is `edge`, and we will use it. My thought process for using the edge channel instead of building the charm here is, since we won't be running these tests when a PR is created, building from master and using the edge channel is the same.
However, if you think building is better, I am open to it as well.

(I will address the other comments in a subsequent commit push.)

2024-03-06 18:52 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    lxd_mdl = await get_or_add_model(ops_test, lxd_ctl, lxd_mdl_name)
Pytest Operator provides a --model option. If provided, model with that name will be used.
So, we need to check if it already exists.

I also added this comment in `utils.py`, where the function is implemented.

2024-03-07 03:32 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +async def _deploy_cos(ops_test, series, channel, k8s_ctl, k8s_mdl):
Added.
Also now the deployment is done with libjuju.

2024-03-07 03:34 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +async def _deploy_hardware_observer(ops_test, series, channel, lxd_mdl):
Added

2024-03-07 03:34 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +async def _add_cross_controller_relations(ops_test, series, channel, k8s_ctl, k8s_mdl, lxd_mdl):
Added, thanks.

2024-03-07 08:12 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    lxd_ctl_name = os.environ["LXD_CONTROLLER"]
Updated

2024-03-07 08:12 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +
Added, can you have a look.

2024-03-07 08:12 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    await lxd_mdl.set_config({"logging-config": "<root>=WARNING; unit=DEBUG"})
Done

2024-03-07 08:13 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    await lxd_mdl.block_until(lambda: len(lxd_mdl.applications["hardware-observer"].units) > 0)
I updated it to check based on hardware observer's status.

2024-03-07 08:16 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
You're right about the juju snap version. I updated it to use libjuju.
Howerver, still have to use juju CLI for consume. I will add a step in workflow job to make sure it's the same version in CI.

2024-03-07 08:16 UTC, sudeephb commented on tox.ini
> +    pytest {toxinidir}/tests/integration -vv --log-cli-level=INFO -s {posargs}
Done

2024-03-07 08:16 UTC, sudeephb commented on tox.ini
> +    sh -c 'if [ -z "$K8S_CONTROLLER" ]; then echo "The K8S_CONTROLLER variable must be set."; exit 1; fi'
Done

2024-03-07 08:43 UTC, jneo8 submitted a review, later dismissed

2024-03-07 08:56 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +def get_this_script_dir() -> Path:
Thanks, updated. We also need to change it [in the main func tests](https://github.com/canonical/hardware-observer-operator/blob/2ce8f5f39466109d34604812c985cafe1572850a/tests/functional/test_charm.py) later.

2024-03-07 09:20 UTC, jneo8 approved these changes

2024-03-07 14:30 UTC, Pjack submitted a review, later dismissed

2024-03-07 14:35 UTC, dashmage approved these changes
LGTM :100: As mentioned by Robert, if we could get the timeout and idle_period values from constants, it might be easier to change. But not a blocking issue :)

2024-03-07 14:49 UTC, sudeephb commented
Rebased it on current master.
Can you give one more review @dashmage / @Pjack / @jneo8 ?

2024-03-07 14:57 UTC, dashmage approved these changes

2024-03-07 14:57 UTC, Pjack approved these changes

2024-03-07 15:30 UTC, merged