docs: Add steps for testing with real hw
canonical/hardware-observer-operator pull request #186
Opened 2024-03-05 12:27 UTC by dashmage

Check [this link](https://github.com/dashmage/hardware-observer-operator/blob/bseng-2067-documentation/tests/functional/README.md) to see the formatted README page.

2024-03-05 14:12 UTC, rgildein commented on tests/functional/README.md
> +We would need 2 machines which are in the same network. One of them will be bootstapped as a controller (can be VM or container) for the juju manual cloud we will be creating and the other will be ad
bootstapped -> bootstrapped

2024-03-05 14:12 UTC, rgildein commented on tests/functional/README.md
> +After ensuring the prerequiste steps are complete, the final command to run the tests would look something like this:
prerequiste -> prerequisite

2024-03-05 14:12 UTC, rgildein commented on tests/functional/README.md
> +3. Provide collectors to pytest.
```suggestion
4. Provide collectors to pytest.
```
or you can use `1.` everywhere, if I'm correct.

2024-03-05 14:12 UTC, rgildein commented on tests/functional/README.md
> +Hardware independent tests are run on every PR/ weekly scheduled test run. They belong to the `TestCharm` class in the `test_charm.py` module.
```suggestion
Hardware independent tests are run on every PR / weekly scheduled test run. They belong to the `TestCharm` class in the `test_charm.py` module.
```

2024-03-05 14:12 UTC, rgildein commented on tests/functional/README.md
> +Running these tests is as simple as executing the `make functional31` command (for the juju 3.1 tests).
I think we should provide also `make functional` here.

2024-03-05 14:12 UTC, rgildein commented on tests/functional/README.md
> +* Test exporter is stopped and related files removed on removal of charm
If I'm correct, we are testing also relations with grafana-agent, or not?

2024-03-06 02:59 UTC, jneo8 requested changes

2024-03-06 02:59 UTC, jneo8 commented on tests/functional/README.md
> +### 1. Setup test environment
**nitpick:** 

I suggest to move this **how to** to another doc file, which make user more easy to follow.

2024-03-06 03:42 UTC, sudeephb commented on tests/functional/README.md
> +3. Provide collectors to pytest.
Nitpick:
Is this really a pre requisite? I feel it is the step to actually run the tests, so it can be dropped from the prerequisite steps list.
And, of course, if we're keeping it, it needs to be `4.` :D

2024-03-06 04:23 UTC, dashmage commented on tests/functional/README.md
> +3. Provide collectors to pytest.
Or I'll leave `3.` everywhere :wink:

2024-03-06 04:27 UTC, dashmage commented on tests/functional/README.md
> +* Test exporter is stopped and related files removed on removal of charm
We do relate with grafana-agent but there's one this one test where we verify in `test_build_and_deploy` whether the charm is blocked before the relation and active after it.

2024-03-06 04:27 UTC, dashmage commented on tests/functional/README.md
> +* Test exporter is stopped and related files removed on removal of charm
I also didn't want to leave a list of all tests but just a sample so anyone reading would get an idea about what kind of test are covered by hardware dependent/ independent tests.

2024-03-06 04:35 UTC, dashmage commented on tests/functional/README.md
> +### 1. Setup test environment
I believe you have the right idea but since each of the subheadings don't have a lot of content, it seems okay to leave it in the same document IMO. If the content is less, I think it makes it easy for the user to have all info in one place. But if the steps do start getting bigger or there's a lot more steps, it makes sense to put all of it into a separate doc.

Thanks for the suggestion!

2024-03-06 04:38 UTC, dashmage commented on tests/functional/README.md
> +3. Provide collectors to pytest.
Good point, that does not read like a prerequisite but actual implementation. The prerequisite should really be: `Find available collectors` which we would need to know beforehand. These collectors could then be used while running the pytest command. I'll make the required changes :smile:

2024-03-06 09:06 UTC, rgildein approved these changes

2024-03-06 09:31 UTC, sudeephb approved these changes
LGTM, thanks

2024-03-06 16:24 UTC, Pjack approved these changes

2024-03-07 05:01 UTC, jneo8 approved these changes

2024-03-07 05:02 UTC, merged