Setup synthetic metrics and test alerts on COS
canonical/hardware-observer-operator pull request #188
Opened 2024-03-13 15:52 UTC by sudeephb

2024-03-14 06:06 UTC, dashmage requested changes
Thanks for your PR! I've left some comments for minor refactoring improvements. Also, nice idea with `pyinstaller` :smile: 

I also wanted to know whether we would be adding more data into `mock_data.py` down the line?

2024-03-14 06:06 UTC, dashmage commented on tests/integration/test_cos_integration.py
> +    ]
praise: innovative solution to not have to install requirements and bundling all the deps in an executable.

2024-03-14 15:59 UTC, sudeephb commented on tests/integration/requirements.txt
> +pyinstaller
Added a comment.

2024-03-14 15:59 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    await k8s_model.set_config(MODEL_CONFIG)
Done

2024-03-14 15:59 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    return True
Done, can you have a look?

2024-03-14 16:00 UTC, sudeephb commented on tests/integration/test_cos_integration.py
> +    except subprocess.CalledProcessError:
Since the alert response is too big, and a relatively smaller response is received even if the required alerts are not there yet, this is not feasible.

2024-03-15 02:18 UTC, sudeephb commented
> I also wanted to know whether we would be adding more data into `mock_data.py` down the line?

Yes, after this approach is accepted, we will add additional metrics(and corresponding alerts) in `mock_data.py` , and we can keep adding it in the future if we think we need more cases.

2024-03-15 02:49 UTC, chanchiwai-ray approved these changes
Overall LGTM

2024-03-15 02:49 UTC, chanchiwai-ray commented on tests/integration/conftest.py
> +async def k8s_ctl():
`lxd controller` -> `k8s controller`

2024-03-15 02:49 UTC, chanchiwai-ray commented on tests/integration/utils.py
> +        if self.state != other.state:
non-blocker + nit:  can be `if self.state != other.state or self.value != other.value`.

Free feel to resolve it

2024-03-15 02:58 UTC, sudeephb commented on tests/integration/conftest.py
> +async def k8s_ctl():
Thanks, updated.

2024-03-15 02:58 UTC, sudeephb commented on tests/integration/utils.py
> +        if self.state != other.state:
Done

2024-03-15 03:48 UTC, chanchiwai-ray approved these changes
LGTM after new commit

2024-03-15 04:34 UTC, dashmage approved these changes
LGTM :rocket:

2024-03-15 04:46 UTC, dashmage approved these changes

2024-03-15 05:42 UTC, chanchiwai-ray approved these changes

2024-03-15 06:36 UTC, Pjack approved these changes
LGTM

2024-03-15 06:46 UTC, merged