Add workflow for cos integration tests
canonical/hardware-observer-operator pull request #189
Opened 2024-03-14 19:31 UTC by sudeephb

2024-03-15 02:56 UTC, chanchiwai-ray reviewed
Small nit: I am not sure how to find the major `3.1.0` number, can you document it

2024-03-15 02:56 UTC, chanchiwai-ray commented on .github/workflows/cos_integration.yaml
> +        run: sed -E -i 's/^\s*juju\s*~=.+/    juju~=3.1.0/g' tests/integration/requirements.txt
worth documenting it on how to find / determine the magic number `3.1.0`

2024-03-15 03:43 UTC, sudeephb commented on .github/workflows/cos_integration.yaml
> +        run: sed -E -i 's/^\s*juju\s*~=.+/    juju~=3.1.0/g' tests/integration/requirements.txt
There's no strong reason to use any specific version, but it needs to be compatible with libjuju. I added a comment. Can you have one more look?

2024-03-15 03:55 UTC, chanchiwai-ray commented on .github/workflows/cos_integration.yaml
> +        run: sed -E -i 's/^\s*juju\s*~=.+/    juju~=3.1.0/g' tests/integration/requirements.txt
Discussed internally: this major number should match `juju-channel` used above

2024-03-15 03:56 UTC, chanchiwai-ray submitted a review, later dismissed

2024-03-15 05:05 UTC, jneo8 requested changes
Need more information.

2024-03-15 05:05 UTC, jneo8 commented on .github/workflows/cos_integration.yaml
> +        run: sed -E -i 's/^\s*juju\s*~=.+/    juju~=3.1.0/g' tests/integration/requirements.txt
**nitpick (blocking):** 

Why we want to update the requireement.txt here?

2024-03-15 05:05 UTC, jneo8 commented on .github/workflows/cos_integration.yaml
> +        run: tox -e integration
**question (non-blocking):** 

Why don't use makefile? I though makefile should be the entrypoint of all commands.

2024-03-15 05:05 UTC, jneo8 commented on .github/workflows/cos_integration.yaml
> +      - name: Dump debug log
**question:** 

Doesn't the functional output enough for use for debugging?

2024-03-15 07:35 UTC, sudeephb commented on .github/workflows/cos_integration.yaml
> +      - name: Dump debug log
Since these tests will run weekly, it will be handy to have the full juju debug log in case of failure, regardless of the logs given by pytest-operator. 
This will avoid us from always having to deploy and rerun the tests in case there's something wrong inside juju units.

2024-03-15 07:37 UTC, sudeephb commented on .github/workflows/cos_integration.yaml
> +          echo "IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')" >> $GITHUB_ENV
Added a comment

2024-03-15 07:37 UTC, sudeephb commented on .github/workflows/cos_integration.yaml
> +        run: sed -E -i 's/^\s*juju\s*~=.+/    juju~=3.1.0/g' tests/integration/requirements.txt
Added a comment

2024-03-15 07:38 UTC, sudeephb commented on .github/workflows/cos_integration.yaml
> +        run: tox -e integration
Thanks, I added a target in Makefile and used it

2024-03-15 09:49 UTC, dashmage submitted a review, later dismissed
Just a small nit, otherwise LGTM :+1:

2024-03-15 10:12 UTC, sudeephb commented on .github/workflows/cos_integration.yaml
> +      - name: Get prefsrc
I have put a more readable name `Get IP address of the host`.

2024-03-15 10:15 UTC, dashmage approved these changes

2024-03-18 03:04 UTC, jneo8 approved these changes

2024-03-18 03:23 UTC, merged