fix: Raise custom exception instead of ErrorStatus
canonical/hardware-observer-operator pull request #191
Opened 2024-03-19 07:30 UTC by dashmage

Raise custom exception `ExporterError` instead of failing with `ops.model.ModelError` when `restart_exporter` fails.

Couple of points to note:
* The exporter class doesn't need a `pass` statement as it's not needed. This was something I learned after hitting [this lint error](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-pass.html)
* This does NOT resolve issue #190. The config hook still fails in that situation but it's a better error message. Will be raising another PR for the actual fix to that issue.

The new error after this patch would look something like
```
unit-hardware-observer-5: 12:16:57 ERROR unit.hardware-observer/5.juju-log Failed to restart the exporter.
unit-hardware-observer-5: 12:16:57 ERROR unit.hardware-observer/5.juju-log Uncaught exception while in cha
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/./src/charm.py", line 344, in <module>
    ops.main(HardwareObserverCharm)  # type: ignore
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/venv/ops/main.py", line 451, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/./src/charm.py", line 224, in _on_config_changed
    self._on_update_status(event)
  File "/var/lib/juju/agents/unit-hardware-observer-5/charm/./src/charm.py", line 148, in _on_update_status
    raise ExporterError(restart_msg)
service.ExporterError: Exporter crashed unexpectedly, please refer to systemd logs...
unit-hardware-observer-5: 12:16:58 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

I would also like to hear about any other ways to handle this sort of issue where `BlockedStatus` wouldn't work since the user can't fix the exporter crash.

2024-03-19 08:46 UTC, sudeephb approved these changes
Thanks. Overall LGTM, left a non-blocking comment.

2024-03-19 08:46 UTC, sudeephb commented on src/charm.py
> +            return "Exporter crashed unexpectedly, please refer to systemd logs..."
Since the same string is used twice, we could set it as a variable and use it in both places.

2024-03-19 09:00 UTC, dashmage commented on src/charm.py
> +            return "Exporter crashed unexpectedly, please refer to systemd logs..."
Yeah that's a good point, will make the change.

2024-03-19 09:01 UTC, dashmage commented
Didn't realize this change breaks a couple of unit tests. Will push the required changes to fix the unit tests soon.

2024-03-19 11:44 UTC, sudeephb submitted a review, later dismissed

2024-03-20 02:26 UTC, chanchiwai-ray approved these changes

2024-03-20 05:13 UTC, jneo8 requested changes

2024-03-20 05:13 UTC, jneo8 commented on src/charm.py
> +        exporter_crashed_msg = "Exporter crashed unexpectedly, please refer to systemd logs..."
**nitpick:** 

I would like to put this static error msg as a global variable and centralized management. So user can easily trace the source code.

2024-03-20 05:13 UTC, jneo8 commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
**nitpick (blocking):** 

I would not choose string to pass the status. How about return the error object?

2024-03-20 05:34 UTC, dashmage commented on src/charm.py
> +        exporter_crashed_msg = "Exporter crashed unexpectedly, please refer to systemd logs..."
Sounds good, I'll keep this somewhere global.

2024-03-20 05:37 UTC, dashmage commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
I'd like to push back on this. I feel like returning str/None object is a very simple approach (str means error is present, block with that message; None means there's no errors) and would like to know your reasoning behind returning the error object instead.

2024-03-20 05:52 UTC, dashmage commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
And the PR itself is created so that we can remove the `ErrorStatus` object since that's something that juju automatically raises and not something we should manage. So it isn't possible to send this error object. Let me know if my understanding is incorrect.

2024-03-20 06:30 UTC, jneo8 commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
> I'd like to push back on this. I feel like returning str/None object is a very simple approach (str means error is present, block with that message; None means there's no errors) and would like to know your reasoning behind returning the error object instead.

The disadvantage here is it's hard to maintain. For example, which if I want to have blockstatus instead of errorstatus? How can I know that from the str?

2024-03-20 06:32 UTC, dashmage commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
So we shouldn't be setting `ErrorStatus` in the charm anyway. Now from the string, it's upto the calling function to decide how to handle it, eg: `BlockedStatus` or `MaintenanceStatus` etc.

2024-03-20 06:33 UTC, jneo8 commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
> And the PR itself is created so that we can remove the ErrorStatus object since that's something that juju automatically raises and not something we should manage. So it isn't possible to send this error object. Let me know if my understanding is incorrect.

We can return Exception or other kind of object to replace it, which can show the status better. String is not a good choice here.

2024-03-20 06:48 UTC, rgildein commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
I came across these comments, and I was interested what is actual function.
I think that current approach is little better than what James proposing, but neither of these two are actualy good. I will try to explain why I think so.
If I see function 'restart_exporter' I would assume that it restart service and returns either nothing or Boolean, True if it was successful and False if not. If anything fail it will raise an exception, which I can catch and use it error message however I want. There could be multiple exception and I can handle them at once or individually.

2024-03-20 07:11 UTC, dashmage commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
Hmm, I think that's a nice idea and I agree that the functionality isn't aligning with the name currently. What about something like this then?

```python
    def restart_exporter(self) -> Optional[str]:
        """Restart exporter service with retry."""
        try:
            for i in range(1, EXPORTER_HEALTH_RETRY_COUNT + 1):
                logger.warning("Restarting exporter - %d retry", i)
                self.exporter.restart()
                sleep(EXPORTER_HEALTH_RETRY_TIMEOUT)
                if self.exporter.check_active():
                    logger.info("Exporter restarted.")
                    break
            if not self.exporter.check_active():
                logger.error("Failed to restart the exporter.")
                raise ExporterError()
        except Exception as err:  # pylint: disable=W0718
            logger.error("Exporter crashed unexpectedly: %s", err)
            raise ExporterError()
        return True

# --- usage ---

        if not self.exporter.check_health():
            logger.warning("Exporter health check - failed.")
            try:
                restart_status = self.restart_exporter()
            except ExporterError:
                logger.error(EXPORTER_CRASH_MSG)
                raise
```

2024-03-20 09:49 UTC, jneo8 commented on src/charm.py
> +    def restart_exporter(self) -> Optional[str]:
> I came across these comments, and I was interested what is actual function.
I think that current approach is little better than what James proposing, but neither of these two are actualy good. I will try to explain why I think so.
If I see function 'restart_exporter' I would assume that it restart service and returns either nothing or Boolean, True if it was successful and False if not. If anything fail it will raise an exception, which I can catch and use it error message however I want. There could be multiple exception and I can handle them at once or individually.

Thanks Robert. Raise exception directly also works. Just different error control flow than return it, since `restart_exporter` is the function inside charm class. Raise it directly is nicer than return.

2024-03-20 11:30 UTC, jneo8 approved these changes

2024-03-20 11:30 UTC, jneo8 commented on src/config.py
> +EXPORTER_CRASH_MSG = "Exporter crashed unexpectedly, please refer to systemd logs..."
**nitpick (non-blocking):** 

It's not a nice place to put the exception. My exception is like [this](example).

(It's not a blocking comment, please feel free to resolve it)

2024-03-20 11:36 UTC, dashmage commented on src/config.py
> +EXPORTER_CRASH_MSG = "Exporter crashed unexpectedly, please refer to systemd logs..."
So this is just the error message. The actual exception is created in the `service.py` module. Are you suggesting to create another `error.py` module to keep this exception and it's error message?

2024-03-20 22:59 UTC, gabrielcocenza commented on src/service.py
> +class ExporterError(Exception):
non-blocker:

reading the [docs](https://juju.is/docs/sdk/styleguide#heading--application-and-unit-statuses) and the examples [0](https://github.com/juju-solutions/resource-oci-image/blob/fca2ff473e96db170811b81ffe70505ac70612e8/oci_image.py#L51) and [1](https://github.com/canonical/kubeflow-dashboard-operator/blob/2e96dcea52ce6995b49ab439c0d5c04ead22c08c/src/charm.py#L171) I'm wondering if we should do something like this:

```python
class ExporterError(Exception):
    """Custom exception for exporter errors."""
    status_type = ErrorStatus
   
    def __init__(self, msg):
        super().__init__()
        self.status = status_type(msg)
```

At least for me it's a little bit more explicit, because it took me sometime to understand that the error bubble up to Juju, which would set an error status.

2024-03-21 06:05 UTC, jneo8 commented on src/config.py
> +EXPORTER_CRASH_MSG = "Exporter crashed unexpectedly, please refer to systemd logs..."
Manage all the error in one place it's a nice practice when your project start to grow.

2024-03-21 06:11 UTC, dashmage commented on src/config.py
> +EXPORTER_CRASH_MSG = "Exporter crashed unexpectedly, please refer to systemd logs..."
Alright, understood. I agree with your idea and if we keep adding more custom error classes we should certainly collect them in a single module. 

Maybe we can have another refactor PR later to move all the custom exceptions (`ExporterError`, `ResourceFileSizeZeroError`, `ResourceChecksumError` etc.) into another module. 

Thanks for your input :)

2024-03-21 08:01 UTC, dashmage commented on src/service.py
> +class ExporterError(Exception):
Hi Gabriel, thanks for leaving your comment. While trying to test this out in my environment, I wasn't able to get the exception to print the status msg with the init method even after trying a bunch of things.

Maybe we could improve this as part of a later effort. But I do agree that it's better to be explicit about the intention, so I've left an additional line in the docstring of the custom exception with this particular detail.

2024-03-21 08:05 UTC, jneo8 approved these changes

2024-03-21 08:18 UTC, Pjack approved these changes
LGTM

2024-03-21 08:19 UTC, sudeephb approved these changes

2024-03-21 09:03 UTC, merged