fix: Check exporter installed before healthcheck
canonical/hardware-observer-operator pull request #192
Opened 2024-03-19 14:56 UTC by dashmage

Fixes #190 

The error happens because the `service.py::check_installed` function (called as a decorator for the various exporter service helper methods) would return `False` when the exporter isn't installed. This would cause the exception to be raised from `update_status --> restart_exporter` since the health check would fail.

Also fixed some typos and re-ordered the redfish credential validation check in the update status handler so that the blocked status message for it comes before the one for missing cos-agent relation.

Note: I really wanted to do
```python
if self._stored.exporter_installed and not self.exporter.check_active():  # type: ignore[truthy-function]
```
but then the linter complains that the line is too long. Would appreciate any advice on having a single if condition but also ignoring that specific linter rule.

2024-03-19 14:57 UTC, dashmage commented
Will fix unit tests after rebasing changes from #191 once it's merged.

2024-03-20 02:24 UTC, chanchiwai-ray approved these changes
Thanks for the workaround

2024-03-21 08:42 UTC, Pjack requested changes

2024-03-21 08:42 UTC, Pjack commented on src/charm.py
> +        if self._stored.exporter_installed:  # type: ignore[truthy-function]
Is it more reasonable to skip this function when exporter not installed? 
We can add the code at the top of this function.

```
if not self._stored.exporter_installed:  # type: ignore[truthy-function]
            # The charm should be in BlockedStatus with install failed msg
            return  # type: ignore[unreachable]
```     

If we invoke this function when the exporter is not installed, it seems the status will be changed back to "ActiveStatus" which is incorrect.

2024-03-21 10:05 UTC, dashmage commented on src/charm.py
> +        if self._stored.exporter_installed:  # type: ignore[truthy-function]
Good suggestion, with this change it will only go past and execute the restart function if the exporter is actually installed. Is this what you had in mind?

```python
        if not self._stored.exporter_installed:
            self.model.unit.status = BlockedStatus("Exporter not installed")
            return
            
        if not self.exporter.check_active():
            logger.warning("Exporter health check - failed.")
            # if restart isn't successful, an ExporterError exception will be raised here
            self.restart_exporter()

        self.model.unit.status = ActiveStatus("Unit is ready")
```

> If we invoke this function when the exporter is not installed, it seems the status will be changed back to "ActiveStatus" which is incorrect.

If the restart function is somehow invoked when the exporter isn't installed (which shouldn't happen after the fix in this PR), the status would be `ErrorStatus` since all the exporter helper methods would fail when the exporter isn't installed. 

But I still think your suggestion is valid and makes it clear that we would want the charm to be blocked if the exporter isn't installed.

2024-03-21 10:20 UTC, dashmage commented on src/charm.py
> +            if not self.exporter.check_active():
```suggestion
            if not self.exporter.check_health():
```
Wrong function being called. Will make this change.

2024-03-21 11:55 UTC, dashmage commented on src/charm.py
> +        if self._stored.exporter_installed:  # type: ignore[truthy-function]
I've made the change from 

```python
        if self._stored.exporter_installed:  # type: ignore[truthy-function]
            if not self.exporter.check_health():
            (...)
```

to

```python
        if not self._stored.exporter_installed:
            logger.warning("exporter not installed")
            return
            
        if not self.exporter.check_active():
            logger.warning("Exporter health check - failed.")
            self.restart_exporter()
```

If any reviewers have alternate thoughts or think one is better than the other, please let me know

2024-03-21 13:20 UTC, Pjack requested changes

2024-03-21 13:20 UTC, Pjack commented on src/charm.py
> +        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
It's better to move this logic to the top of this function. 

```
if not self._stored.resource_installed or not self._stored.exporter_installed:
    return

```
For this two cases, they are already handled in _on_install_or_upgrade. That's why we don't set up the status again here. If you compare with other case, we will change the status to BlockedStatus.

2024-03-21 13:34 UTC, dashmage commented on src/charm.py
> +        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
Ahh I see, let me move it to the top then. Makes sense to keep them together. I will add it as another clause and not in the same if statement to prevent the linter from complaining about the line length.

```python
        if not self._stored.resource_installed:  # type: ignore[truthy-function]
            # The charm should be in BlockedStatus with install failed msg
            return  # type: ignore[unreachable]

        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
            # The charm should be in BlockedStatus with exporter install failed msg
            logger.warning("Exporter not installed")  # type: ignore[unreachable]
            return
```

2024-03-21 14:09 UTC, chanchiwai-ray reviewed
It doesn't seem to me that I will fix the issue.. Have you test if it can fix the issue ?

Since the validation of redfish config did not remove from install or upgrade event, there's still possibility that operator deploys the charm with incorrect credential and causing the exporter not being installed.

2024-03-21 14:41 UTC, dashmage commented
> It doesn't seem to me that I will fix the issue.. Have you test if it can fix the issue ?
Since the validation of redfish config did not remove from install or upgrade event, there's still possibility that operator deploys the charm with incorrect credential and causing the exporter not being installed.

Good thing you brought this up. So I did check initially and the hook didn't fail for the charm and no exceptions were raised. So I thought the code was good. But upon checking once more carefully, another issue comes up. With the latest change, even after I configure the redfish creds, the status doesn't change from `BlockedStatus` with invalid redfish creds message. This might be because the `ActiveStatus` is not being reached at the end of the update status hook and it keeps looping when `exporter_installed` is not set. So I might have to revert that change.

^ @Pjack

2024-03-22 19:52 UTC, gabrielcocenza requested changes

2024-03-22 19:52 UTC, gabrielcocenza commented on src/charm.py
> +        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
In the end of the day what is considered to have the exporter installed?

In my understanding reading the code is:
- exist a file at `/etc/systemd/system/hardware-exporter/.service` and `/etc/hardware-exporter-config.yaml`

This is very easy to check and not CPU intensive by using [Path.exists](https://docs.python.org/3/library/pathlib.html#pathlib.Path.exists) and I don't see the need at all of using `self._stored` and by consequence those type ignore.

The juju sdk documentation has an interesting section of uses and limitations with [StoredState](https://juju.is/docs/sdk/stored-state-uses-limitations) and the problematic solution looks like a lot with what I'm seeing in this project.

I've spotted another possible issue into the install function:

https://github.com/canonical/hardware-observer-operator/blob/86f0d7e0dd8b0339740518b27eb224fb1fcaf2b9/src/service.py#L132-L149

See that if line 137 fails, it will overwrite the result on line 143 meaning that if for some reason the redfish config file fails, but for the service doesn't, you won't notice.

To say the truth I' would refactor those functions of `install` and `uninstall` to return nothing and let to bubble in the charm code here

2024-03-23 03:46 UTC, Pjack commented on src/charm.py
> +        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
Thanks for pointing out the issue.
We discussed that we need a refactor for this part but not handle with this issue together. 
Repost to #196 to handle it later.

2024-03-23 09:53 UTC, dashmage commented
[This commit](https://github.com/canonical/hardware-observer-operator/pull/192/commits/16fd216cff684794d4876162ae3a715270ea22bd) just cleans up the unit test names and docstrings since many of them were incorrect.

2024-03-23 09:58 UTC, dashmage commented
I've also added an [extra check](https://github.com/canonical/hardware-observer-operator/pull/192/commits/6432d07ff93dc04a7e33ad972c21aa851ea9ca05) in `test_install_redfish_enabled_with_incorrect_credential` to make sure that the exporter is installed when when there's wrong redfish credentials.

2024-03-25 04:13 UTC, Pjack reviewed
The code and logic looks good to me .

I would like to confirm where should we validate this behavior?
1. config or credential is invalid
2. User change the configuration or provide correct credential.
3. Verify if the charm will become active state again.

Maybe in hardware-indendent functional test?

2024-03-25 04:26 UTC, dashmage commented
> The code and logic looks good to me .
> 
> I would like to confirm where should we validate this behavior?
> 
>     1. config or credential is invalid
> 
>     2. User change the configuration or provide correct credential.
> 
>     3. Verify if the charm will become active state again.
> 
> 
> Maybe in hardware-indendent functional test?

It would probably be in the hardware *dependent* functional tests if the redfish creds are invalid and we want to test that after the correct config is provided, the charm is in active status. Currently we only have [the test](https://github.com/canonical/hardware-observer-operator/blob/master/tests/functional/test_charm.py#L337) to check if we're able to query the redfish metrics.

If you're talking about any hardware *independent* config (exporter log level, port etc.), we [already have functional tests](https://github.com/canonical/hardware-observer-operator/blob/master/tests/functional/test_charm.py#L524) for the behavior you've mentioned. But we do need to make some changes to verify that the charm is active afterwards. Currently it just verifies if the config is correctly changed in the underlying file.

It would be good to have another refactoring PR for the functional tests as well so we can follow through on these requirements.

2024-03-25 12:26 UTC, gabrielcocenza commented on src/charm.py
> +        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
Can we create another issue to remove the usage of `StoredState` to track if it was successfully installed?

2024-03-25 12:35 UTC, dashmage commented on src/charm.py
> +        if not self._stored.exporter_installed:  # type: ignore[truthy-function]
I've opened a new issue for this: https://github.com/canonical/hardware-observer-operator/issues/201

2024-03-25 13:26 UTC, gabrielcocenza reviewed
I'm a little bit lost with the PR title, description and the bug that points the fix.

The bug description says:
> This is because the blocked status message for invalid redfish creds has been overwritten by the missing relation message while executing the `update status hook`.

I'm not seeing any changes in the `update status hook`.

What are we fixing by removing the validation of the exporter configs on the install hook?

2024-03-25 18:04 UTC, dashmage commented
> I'm a little bit lost with the PR title, description and the bug that points the fix.
> 
> The bug description says:
> 
> > This is because the blocked status message for invalid redfish creds has been overwritten by the missing relation message while executing the `update status hook`.
> 
> I'm not seeing any changes in the `update status hook`.
> 
> What are we fixing by removing the validation of the exporter configs on the install hook?

Sorry about the confusion. We made some findings over the course the PR due to which we had to change the originally intended fix. Plus, the logic is a bit tricky to follow. I've made some changes to the PR description that hopefully clarifies your doubts. If not, feel free to respond with any questions and I'll try my best to address them.

2024-03-25 20:59 UTC, gabrielcocenza commented on src/charm.py
> +        config_valid, config_valid_message = self.validate_exporter_configs()
> This PR aims to fix this by removing the unnecessary redfish credential validation step during the install event since it will be performed as part of both the update status and config changed events. This ensures that the exporter is installed before invoking the restart_exporter method.

I understand that if you don't have valid exporter configs on the installation (most likely), it will end up not properly installing the exporter and this can have a weird state, so I'm totally favorable of removing this.

However, another thing showed up to me while  reading the `_on_install_or_upgrade`. If it fails to install the charm is setting to `blocked state`, and this does not look right to me. Blocked means that the user should manually do something. What the user should do if the installation fails? IMO, we should raise an exception and let to be on error state.

2024-03-26 03:03 UTC, chanchiwai-ray commented on src/charm.py
> +        config_valid, config_valid_message = self.validate_exporter_configs()
To be more precise, we should remove any statement about the redfish credential validation since it's a bug before having redfish credential validation step (for example, you can deploy with a wrong `exporter-log-level`, the same problem should arise); that step only reveals the problem now.

> However, another thing showed up to me while reading the _on_install_or_upgrade. If it fails to install the charm is setting to blocked state,...

+1, it does not seem to me that we cannot do anything about install hook fail, the charm should be in error state, and it's bug that we should fix. But that should be raised in another issue

2024-03-26 03:05 UTC, chanchiwai-ray commented on src/charm.py
> +        config_valid, config_valid_message = self.validate_exporter_configs()
though, I agree that the issue and PR description / title did not capture the root cause

2024-03-26 03:06 UTC, chanchiwai-ray approved these changes
It looks good to me for addressing the root cause

2024-03-26 07:07 UTC, dashmage commented on src/charm.py
> +        config_valid, config_valid_message = self.validate_exporter_configs()
@gabrielcocenza - Appreciate the suggestion for the PR description. I've made changes accordingly.
@gabrielcocenza , @chanchiwai-ray - I also agree about the exporter install failure bug. I've raised a separate issue to track this (#203)

2024-03-26 07:27 UTC, Pjack commented on src/charm.py
> +        config_valid, config_valid_message = self.validate_exporter_configs()
I suggest to move the discussion to somewhere else. There are some gray area between error/blocked status. You can also find similiar discussion in discourse. 
https://discourse.charmhub.io/t/its-probably-ok-for-a-unit-to-go-into-error-state/13022/24

> However, another thing showed up to me while reading the _on_install_or_upgrade. If it fails to install the charm is setting to blocked state, and this does not look right to me. Blocked means that the user should manually do something. What the user should do if the installation fails? IMO, we should raise an exception and let to be on error state.

https://juju.is/docs/sdk/styleguide#heading--error-handling
If installation fails due to network connectivity issues, the operator is responsible for addressing the network problem, as it's not a bug within the charm itself. Therefore, setting the status to "blocked" is reasonable in this scenario. In summary, any error state indicates a potential bug. 

Since Ashley changed the title, please @gabrielcocenza close this discussion thread. thanks!

2024-03-26 07:28 UTC, Pjack approved these changes

2024-03-26 12:47 UTC, gabrielcocenza approved these changes

2024-03-26 13:08 UTC, dashmage commented on src/charm.py
> +        config_valid, config_valid_message = self.validate_exporter_configs()
Resolving this conversation since a separate issue has been created for it and the PR desc has been updated.

2024-03-26 13:10 UTC, merged