Add scrape_timeout config option
canonical/hardware-observer-operator pull request #193
Opened 2024-03-20 10:40 UTC by sudeephb

Depends on https://github.com/canonical/prometheus-hardware-exporter/pull/67

2024-03-22 07:10 UTC, jneo8 requested changes

2024-03-22 07:10 UTC, jneo8 commented on config.yaml
> +  collect-timeout:
**suggestion:** 

Since we have a hard code scrape-interval. We should also mention about the timeout should not be longer than 1 min.

Also we should provide some checking in the charm to avoid this happen.

2024-03-22 07:26 UTC, Pjack commented on config.yaml
> +  collect-timeout:
+1

2024-03-22 07:27 UTC, sudeephb commented on config.yaml
> +  collect-timeout:
I agree we should mention that the timeout should not be longer than prometheus `scrape_interval`(by default 1m). 

However, I don't think we should stop the users from doing so. Because, if the grafana-agent charm provides `scrape_interval` config in the future, they could change it to any arbitrary value, and hence it being greater than 1m is not an issue(though not recommended, I suppose).

2024-03-22 07:30 UTC, Pjack commented on config.yaml
> +  collect-timeout:
Is that possible we can compare the scrape_interval with timeout value after we set up the relation?

2024-03-22 07:34 UTC, sudeephb commented on config.yaml
> +  collect-timeout:
I don't think so. Getting the `scrape_config` currently shows only whatever has been set by hw-observer while creating the hardware-observer <-> grafana-agent relation. So, config set from another charm is not visible.

2024-03-22 07:49 UTC, Pjack commented on config.yaml
> +  collect-timeout:
Then please add description to remind the user to check the scrape interval in grafana-agent if they want to increase the timeout over 1 min. thanks!

2024-03-22 07:49 UTC, Pjack approved these changes

2024-03-22 07:50 UTC, sudeephb commented on config.yaml
> +  collect-timeout:
I have added a note about `scrape_interval` in the config description btw.

2024-03-22 09:05 UTC, Pjack commented on config.yaml
> +  collect-timeout:
User can change the scrape_interval at granafa-agent by themselve if they want to use the timeout > 60s.

2024-03-22 09:34 UTC, jneo8 approved these changes

2024-03-22 09:35 UTC, merged

2024-03-27 07:24 UTC, Pjack commented
Lesson learn: We should add new unit/func test when adding new configuration.
https://github.com/canonical/hardware-observer-operator/issues/200