Store hw tool list in _stored and reuse it.
canonical/hardware-observer-operator pull request #217
Opened 2024-04-09 06:24 UTC by sudeephb

The list will be created only once, during the install hook, and the same list will be reused everywhere else. This avoids generating a new list everytime it's needed, and potentially losing a hw from the list when it can't be temporarily accessed.

Setting the target as a dev  branch because this feature needs an accompanying action to regenerate hw list before it's merged to main.

2024-04-10 06:14 UTC, chanchiwai-ray commented on src/charm.py
> +        )
[non-blocking] we could refactor this as a function

```python
...

def __init__(self, ...):
  ...
  self._stored.set_default(
    exporter_installed=False,
    resource_installed=False,
    enabled_hw_tool_list=[],
  )

def get_enabled_hw_tool_list(self):
  if not self._stored.get("enabled_hw_tool_list", []):
    self._stored.enabled_hw_tool_list = [tool.value for tool in get_hw_tool_white_list()]
  return self._stored.enabled_hw_tool_list
```

2024-04-10 08:35 UTC, jneo8 requested changes

2024-04-10 08:35 UTC, jneo8 commented on src/charm.py
> +            enable_hw_tool_list = [
**nitpick:** 

There are many duplicate `HWTool(value) for value in self._stored.enable_hw_tool_list_values`.

I would like to have a property function for it.

2024-04-10 08:35 UTC, jneo8 commented on src/charm.py
> +        if isinstance(event, ops.InstallEvent):
**suggestion (non-blocking):** 

Move the logic here to `_on_install` function

2024-04-10 08:35 UTC, jneo8 commented on src/service.py
> +        if enable_hw_tool_list is not None:
**nitpick:** 

The logic here maybe not necessary. We can assumed that the enable list will always be passed.

2024-04-10 08:35 UTC, jneo8 commented on src/service.py
> +        if enable_hw_tool_list is not None:
**nitpick (blocking):** 

The logic here maybe not necessary. We can assumed that the enable list will always be passed.

2024-04-11 04:12 UTC, sudeephb commented
> Could we also replace whilte_list with allowlist in this refactor?

I think `enable_list` makes more sense here, since we're not `allow`ing or `deny`ing anything. We are choosing what to `enable` or `disable`. 
What do you think?

2024-04-12 00:37 UTC, Pjack commented
> > Could we also replace whilte_list with allowlist in this refactor?
> 
> I think `enable_list` makes more sense here, since we're not `allow`ing or `deny`ing anything. We are choosing what to `enable` or `disable`. What do you think?

Good with enable/disable  ,   so that should be enabled_list ?

2024-04-12 00:46 UTC, Pjack requested changes

2024-04-12 00:46 UTC, Pjack commented on tests/unit/test_charm.py
> +        get_hw_tool_white_list_patcher = mock.patch.object(charm, "get_hw_tool_white_list")
still use whilte_list

2024-04-12 00:46 UTC, Pjack commented on tests/unit/test_charm.py
> +        self.mock_get_hw_tool_white_list.return_value = [
still use whilte_list

2024-04-12 00:46 UTC, Pjack commented on tests/unit/test_exporter.py
> +        get_charm_hw_tool_white_list_patcher = mock.patch(
Ditto

2024-04-12 00:46 UTC, Pjack commented on tests/unit/test_charm.py
> +        mock_stored.enable_hw_tool_list_values = [
What's the reason to avoid using "HWTool.XXX"  here?

2024-04-12 09:03 UTC, sudeephb commented on tests/unit/test_charm.py
> +        mock_stored.enable_hw_tool_list_values = [
juju `_stored ` can only store 'simple' types like strings, ints. If we store our custom objects, it throws an exception. I have put a comment [here](https://github.com/sudeephb/hardware-observer-operator/blob/2e55a34f9eb59c8ebdc4840e793f9647fb82f3b2/src/charm.py#L74)

2024-04-12 09:27 UTC, chanchiwai-ray commented on src/charm.py
> +        return list(self._stored.enabled_hw_tool_list_values)  # type: ignore[call-overload]
is it because of `mypy` that you add `list(xxx)` here?

2024-04-12 09:35 UTC, Pjack approved these changes

2024-04-12 09:35 UTC, Pjack commented on src/charm.py
> +from hw_tools import HWToolHelper, get_hw_tool_white_list
It's white_list, could we change the naming?

2024-04-12 09:35 UTC, Pjack commented on src/charm.py
> +            logger.debug("Install hook: Getting hw tool white list")
white list

2024-04-12 10:26 UTC, sudeephb commented on src/charm.py
> +        return list(self._stored.enabled_hw_tool_list_values)  # type: ignore[call-overload]
Yes, an alternative would be to just add   `# type: ignore`. and simply return `self._stored.enabled_hw_tool_list_values`.

2024-04-15 07:14 UTC, chanchiwai-ray commented on src/charm.py
> +        return [HWTool(value) for value in hw_tool_values]
Question: why do we convert the list from `str` to `HWTool`? Do we use the `str` version somewhere? Can we just `tool for tool in get_hw_tool_enable_list()`

2024-04-15 07:50 UTC, sudeephb commented on src/charm.py
> +        return [HWTool(value) for value in hw_tool_values]
We can only store the `str` version in `_stored`([as I have left a comment here](https://github.com/sudeephb/hardware-observer-operator/blob/bseng-2271/src/charm.py#L74)). 

>Can we just use tool for tool in get_hw_tool_enable_list()..

In this case, we would get the hw list from the system instead of from `_stored`, which is what we're trying to avoid.

2024-04-15 07:55 UTC, chanchiwai-ray approved these changes

2024-04-15 08:04 UTC, merged

2024-04-15 12:15 UTC, dashmage commented
I realize this PR is merged but after checking out the changes, this usage to get the hwtool objects looks quite weird

```python
self.hw_tool_helper.check_installed(
     self.get_hw_tools_from_values(self.get_enabled_hw_tool_list_values())
)
```

It would be nice if we could refactor later on to be more like

```python
self.hw_tool_helper.check_installed(self.get_enabled_hw_tools())
```

We could make the other methods private if needed and make the usage a bit more cleaner.

2024-04-15 12:17 UTC, sudeephb commented
> I realize this PR is merged but after checking out the changes, this usage to get the hwtool objects looks quite weird
> 
> ```python
> self.hw_tool_helper.check_installed(
>      self.get_hw_tools_from_values(self.get_enabled_hw_tool_list_values())
> )
> ```
> 
> It would be nice if we could refactor later on to be more like
> 
> ```python
> self.hw_tool_helper.check_installed(self.get_enabled_hw_tools())
> ```
> 
> We could make the other methods private if needed and make the usage a bit more cleaner.

Thank you. This is still in dev branch, I will address these while creating a PR for the main branch.