[WIP]Refactor to support multiple exporters
canonical/hardware-observer-operator pull request #218
Opened 2024-04-11 07:54 UTC by sudeephb

Some refactor so that adding a new exporter becomes simpler. After this is merged, a new exporter can simply be added by implementing:
1.  a new `XxxExporterTemplate` class that inherits from `ExporterTemplate`. 
2.  a new `XxxExporter` class that inherits from `Exporter`.

2024-04-11 09:45 UTC, chanchiwai-ray commented on src/service.py
> +def check_installed(exporter_name: str) -> Callable:
I think we should find a way to remove this guard: e.g. by returning a exporter service instance.

For example:

```python
def install_service(...) -> Service: pass
def get_service(...) -> Optional[Service]: pass

class Service:
   def configure(...):
   def restart_and_enable(...):
   .... # will not handle install / remove here now
```

This way, we guarantee to be able to configure, start, stop the service because you either get `None` or the `Service` instance.

2024-04-11 10:25 UTC, jneo8 requested changes

2024-04-11 10:25 UTC, jneo8 commented on src/config.py
> +HARDWARE_EXPORTER_NAME = "hardware-exporter"
**suggestion:** 

It will be nice if you can use some solution like pydantic to manage those config for a single exporter.

2024-04-11 10:25 UTC, jneo8 commented on src/service.py
> +            if exporter_name == HARDWARE_EXPORTER_NAME:
**issue:** 

This is not ready for handle multiple exporter.
You need to let the decorator can accept parameters.

2024-04-11 10:25 UTC, jneo8 commented on src/charm.py
> +        hardware_exporter_success = self.hardware_exporter.install(
**issue (non-blocking):** 

I feel it will become a disaster once you start to put more exporter here.
The possible solutions could be:

1. Re-writing the service to become the [Object](https://github.com/canonical/operator/blob/b7e5ba33e7a18022b56535a4d3d84363e1091f5b/ops/framework.py#L369), and follow the way how operator framework control the life-cycle for the service.

2. You probably need a more nice logic here to control all the exporter's install/remove/configure. Not just adding more code directly.

2024-04-11 10:30 UTC, jneo8 requested changes

2024-04-11 10:30 UTC, jneo8 commented on src/charm.py
>      def restart_exporter(self) -> None:
**nitpick (blocking):** 

Imagine you add 2 more exporters here.
This function is not ready to handler multiple exporters.

2024-04-16 17:04 UTC, dashmage requested changes
Thanks for all the work on this PR. Made some great improvements from the first version of the draft :smile:

2024-04-16 17:04 UTC, dashmage commented on src/service.py
> +class BaseExporter(metaclass=ABCMeta):
```suggestion
class BaseExporter(ABC):
```
Also import `ABC`

2024-04-16 17:04 UTC, dashmage commented on src/service.py
> +        """Setup a file with content."""
```suggestion
    def _write_to_file(self, path: Path, content: str) -> bool:
        """Write to file with provided content."""
```
This would make the functionality more explicit

2024-04-17 06:04 UTC, chanchiwai-ray requested changes

2024-04-17 06:10 UTC, chanchiwai-ray commented
Thanks for the hard works! I would suggest that refactoring at this scale should be merging into a staging branch (deb branch) and with multiple (smaller) chunks (e.g. renaming config option (which we should not because it's a non-compatible change), refactoring config handler, refactor service handler, refactor charms...) before goes to master branch.

2024-04-17 09:22 UTC, jneo8 requested changes
Some suggestions.

2024-04-17 09:22 UTC, jneo8 commented on src/charm.py
> +exporter_settings = ExporterSettings()
**nitpick:** 

Can you explain why you initial a exporter service object but you still need to initial another exporter config object here?

You should able to get those config values from the exporter object.

2024-04-17 09:22 UTC, jneo8 commented on src/charm.py
> +                self.reconfigure_exporter(exporter)
**suggestion:** 

Consider to put those helper functions(`reconfigure_exporter`, `uninstall_exporter`, ...) in another Mixin. It will be more clear and easy to read.

2024-04-17 09:22 UTC, jneo8 commented on src/charm.py
> +            if str(exporter) in self._stored.installed_exporters:
**nitpick:** 

Exporter should check if it's installed before remove by itself. The checking logic should be put inside the exporter class.

2024-04-17 09:22 UTC, jneo8 commented on src/config.py
> +    redfish_max_retry: int = 2
Using pydantic is fine. But I have question why you don't inheritance base class?

2024-04-17 09:22 UTC, jneo8 commented on src/service.py
> +    def __str__(self) -> str:
**nitpick:** 

Any reason to overwrite the `__str__`?

2024-04-17 09:22 UTC, jneo8 commented on src/service.py
> +    def _setup_file(self, path: Path, content: str) -> bool:
**nitpick:** 

You need a ` @abstractmethod` decorator?

2024-04-18 10:35 UTC, sudeephb commented on src/service.py
> +
Since it's related to a particular exporter(ie. the `HardwareExporter`) service, I felt it made more sense for it to be in `service.py`. Since it's not a class method, it can reside anywhere.

2024-04-18 10:42 UTC, sudeephb commented on src/service.py
> +    def __str__(self) -> str:
In many log messages, we simply print the `exporter` object. Overwriting this method makes the log messages more readable.
Before overwriting `__str__`:
```
print(hardware_exporter)
<HardwareExporter object at 0x7aa2fc1f7730> # Something similar to this
```
After overwriting `__str__`:
```
print(hardware_exporter)
HardwareExporter
```

2024-04-18 10:44 UTC, sudeephb commented on src/service.py
> +    def _setup_file(self, path: Path, content: str) -> bool:
Not really. This implementation works for all child classes, as long as they provide the right path and content. So, the child classes don't need to implement this method.

2024-04-18 10:54 UTC, dashmage commented on src/service.py
> +
Checking the code again, it looks like we only use it with hardware exporter during its install when we need to render the config. I was initially under the impression this is used elsewhere in `charm.py`. So maybe this works out. I'd like to hear what others have to say about this though.

2024-04-19 02:10 UTC, sudeephb commented on src/config.py
> +    redfish_max_retry: int = 2
Thanks. I updated by inheriting from the `ExporterSettings` class.

2024-04-19 03:25 UTC, jneo8 requested changes

2024-04-19 03:25 UTC, jneo8 commented on src/config.py
> +hardware_exporter_settings = HardwareExporterSettings()
**nitpick:** 

Can you follow the constant variable naming to change the variable name to `HARDWARE_EXPORTER_SETTINGS`

2024-04-19 03:25 UTC, jneo8 commented on src/hw_tools.py
> +hardware_exporter_settings = HardwareExporterSettings()
**nitpick (blocking):** 

Please import it from the config module instead of init it again.

2024-04-19 03:25 UTC, jneo8 commented on src/service.py
> +        config_path = self.exporter_config_path
**issue:** 

I kind of thinking the check_installed logic will be different for each exporter.

Can you make create a new abs method called `check_installed` in the exporter class and call it from this decorator?

2024-04-22 03:20 UTC, sudeephb commented on src/service.py
> +class ExporterLifecycleHelper:
The methods were within the charm class beforehand, and after @jneo8's [comment](https://github.com/canonical/hardware-observer-operator/pull/218#discussion_r1568500260), we decided to move them to a separate mixin to make it look cleaner. What do you think would be the best choice @jneo8 @samuelallan72?

2024-04-22 03:35 UTC, sudeephb commented on src/config.py
> +    redfish_max_retry: int = 2
I agree on removing the init method on the base exporter. 
However, these constants are also used in `src/hw_tools.py` which manages the installation and removal of packages and third party resources. If we initialized these inside the exporter constructor, we would need to initialize them somewhere else as well.

2024-04-22 03:59 UTC, sudeephb commented on src/service.py
> +        return not systemd.service_failed(self.exporter_name)
In a previous discussion on this, we decided it was best to implement `install, uninstall, etc` as methods in ABC since we do  not have any snap services now or in the near future. And if we add snap services, they can still implement and override these methods.

2024-04-22 04:16 UTC, sudeephb commented on src/config.py
> +    redfish_max_retry: int = 2
Yes they were constants beforehand. The classes were used simply for separation of concerns between the exporters. If we store directly as constants, things will get out of hand as we add more exporters:
```
HARDWARE_EXPORTER_CONFIG_TEMPLATE = ....
....
SMART_EXPORTER_CONFIG_TEMPLATE = ...
....
GPU_EXPORTER_CONFIG_TEMPLATE = ...
```

2024-04-22 04:24 UTC, dashmage commented on src/service.py
> +class ExporterLifecycleHelper:
I'm curious to know why you'd want to avoid mixins here @samuelallan72. It does seem like a nice way to encapsulate all the exporter related methods elsewhere and keep the charm class clean.

2024-04-22 04:38 UTC, dashmage commented on src/service.py
> +    def _write_to_file(self, path: Path, content: str) -> bool:
Or it could be a static method for the class.

2024-04-23 08:25 UTC, jneo8 commented on src/service.py
> +class ExporterLifecycleHelper:
I think we try to avoid define every functions in the charm class. Putting event handler functions and Exporter related functions in the same class make this class huge to to maintain.

Also the purpose of this PR is to make sure the architecture can support multiple exporters. The mixin helps us to separate the logic of charm and exporter services. The disadvantage of mixin is not like what you imagine here:

- *Difficult to trace inheritance*: we don't have multiple layers of inheritance here. And we will avoid to do that.
- *Difficult to maintain*: As I mention above, the currently status is more hard to maintain.

I think we use it really carefully.

2024-04-23 08:50 UTC, jneo8 commented on src/config.py
> +    redfish_max_retry: int = 2
> by the way, why can't src/hw_tools be refactored, and package installation, etc. be part of the package/module/class specific to each new exporter? ie. refactor things at a higher level.

I think this really out of scope here.

2024-04-23 08:50 UTC, jneo8 commented on src/config.py
> +    redfish_max_retry: int = 2
> Yes, but this is the same kind of growth as your new pattern - there will be a new class for each new exporter.

It's just different way to structure the constants config variables. I don't see big issue to use pydantic.

2024-04-24 05:45 UTC, jneo8 commented on src/service.py
> +class ExporterLifecycleHelper:
The benefit is you can use self.xxx to call those helper function, like a additional service helper plugin.

2024-04-25 10:01 UTC, sudeephb commented
Closing this in favor of #228 , which targets a dev branch, so the different stages can be reviewed and merged one by one.

2024-04-25 10:01 UTC, closed without merging