feat: Expose redfish-client-timeout as charm config
canonical/hardware-observer-operator pull request #220
Opened 2024-04-16 14:41 UTC by dashmage

This change exposes a new charm config option for `redfish-client-timeout` which is then written to the `/etc/hardware-exporter-config.yaml` file. When hardware exporter is installed, this configured value will be used for redfish (also refer [hardware-exporter config.py](https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/config.py#L36) for config definition and [main.py](https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/__main__.py#L186) where config is loaded from file).

Fixes #170

2024-04-16 14:44 UTC, dashmage commented
Unit test changes are in progress.

2024-04-17 02:01 UTC, Pjack requested changes
There are two timeout value in the charm. I prefer to make it easy to the user.
Collect-timeout could impact all timeout value, including shell command , redfish, even the SMART metrics exporter in the future.

This is also the reason I think #193 should solve #170

2024-04-17 04:34 UTC, dashmage commented
> I prefer to provide less configuration to the user based on charm's design philosophy. Collect-timeout could impact all timeout value, including shell command , redfish, even the SMART metrics exporter in the future.
> 
> This is the reason I think #193 should solve #170

I see, so you suggest using the same config option (`collect-timeout`) itself for all metric collection operations instead of adding a separate one for redfish. The only con I see with this approach is that there might be a situation where we just want the timeout for redfish to be very high (due to very slow redfish response on some host) but we still want the timeout for the other collectors to be normal. Not sure if that's an issue we can ignore for a simpler setup with a single config option.

2024-04-17 05:15 UTC, Pjack commented
My two cents.
We've implemented collect_timeout for all shell commands, including ipmi, megacli, and others. The issues you mentioned are indeed valid now. Therefore, I don't think it's a problem to include redfish.

2024-04-17 05:15 UTC, Pjack commented
> My two cents.
> We've implemented collect_timeout for all shell commands, including ipmi, megacli, and others. The issues you mentioned are indeed valid now. Therefore, I don't think it's a problem to include redfish.

My two cents.
We've implemented collect_timeout for all shell commands, including ipmi, megacli, and others. The issues you mentioned are indeed valid now. Therefore, I don't think it's a problem to include redfish.

2024-04-17 05:15 UTC, Pjack commented
> > I prefer to provide less configuration to the user based on charm's design philosophy. Collect-timeout could impact all timeout value, including shell command , redfish, even the SMART metrics exporter in the future.
> > This is the reason I think #193 should solve #170
> 
> I see, so you suggest using the same config option (`collect-timeout`) itself for all metric collection operations instead of adding a separate one for redfish. The only con I see with this approach is that there might be a situation where we just want the timeout for redfish to be very high (due to very slow redfish response on some host) but we still want the timeout for the other collectors to be normal. Not sure if that's an issue we can ignore for a simpler setup with a single config option.

My two cents.
We've implemented collect_timeout for all shell commands, including ipmi, megacli, and others. The issues you mentioned are indeed valid now. Therefore, I don't think it's a problem to include redfish.

2024-04-17 07:05 UTC, dashmage commented
I've modified the PR title and description in order to reflect the new changes.

2024-04-17 08:11 UTC, chanchiwai-ray approved these changes
LGTM, except for small nit

2024-04-17 08:11 UTC, chanchiwai-ray commented on src/charm.py
> +                timeout=redfish_conn_params.get("timeout", REDFISH_TIMEOUT),
`REDFISH_TIMEOUT` constant now become obsolete, maybe consider removing it

2024-04-17 09:11 UTC, dashmage commented on src/charm.py
> +                timeout=redfish_conn_params.get("timeout", REDFISH_TIMEOUT),
It's also used in the `redfish_available` method in [`hw_tools.py`](https://github.com/canonical/hardware-observer-operator/blob/master/src/hw_tools.py#L439) which might require some refactoring to remove. So I think we can leave it in place for now.

2024-04-17 14:13 UTC, Pjack approved these changes

2024-04-18 04:25 UTC, merged