feat: redetect-hardwares juju action
canonical/hardware-observer-operator pull request #226
Opened 2024-04-25 08:48 UTC by jneo8

Redetect the hardwares and reinitialize the charm. The exporter service(s) will be reconfigured and restarted.

2024-04-25 09:18 UTC, Pjack requested changes

2024-04-25 09:18 UTC, Pjack commented on charmcraft.yaml
> +        default: false
"detect" sounds read-only to me and no harm at all. I prefer the default behavior should not change anything to prevent careless action. 

I prefer to change the naming, something like this
* additional paramaeter :  --initial-hardware-list, default : false

Furthermore, I would like to know the naming of these juju actions

- get current hardware list
- detect new hardware list
- generate new hardware list
  
They should have aligned naming rule so the user is easy to remember how to execute it.

2024-04-25 10:09 UTC, jneo8 commented on charmcraft.yaml
> +        default: false
Sound better then what we have now.
How about:

- get-current-hardware-tools
- detect-hardwares
  - with `--apply` option, default is `False`

2024-04-26 02:45 UTC, Pjack commented on charmcraft.yaml
> +        default: false
It's a good idea :) I like it.

2024-04-26 03:19 UTC, chanchiwai-ray commented on charmcraft.yaml
> +        default: false
Would be better to get a diff, then just showing the new list. And should be default to show the diff, if `--apply`, then apply

2024-04-26 06:10 UTC, chanchiwai-ray requested changes

2024-04-26 06:10 UTC, chanchiwai-ray commented on charmcraft.yaml
> +  detect-hardwares:
I suggest the name to `hardware-detection`, because it will be called like `juju run hardware-observer/0 hardware-detection [apply=false]` with a default `apply=false`.

2024-04-26 06:10 UTC, chanchiwai-ray commented on src/charm.py
> +        if event.params["dry-run"] == True:
As mentioned above, `if not apply`, just list the saved and latest detected hardware. `If apply`, do `install_or_upgrade` and print out the new hardware list

2024-04-26 06:51 UTC, jneo8 commented on charmcraft.yaml
> +  detect-hardwares:
Should it be noun? I thought verb will be more precise.

For example: https://github.com/canonical/github-runner-operator/blob/main/actions.yaml

2024-04-26 06:58 UTC, chanchiwai-ray commented on charmcraft.yaml
> +  detect-hardwares:
but `juju run <action_name>`: "subject verb object" ...

2024-04-26 07:07 UTC, chanchiwai-ray commented on charmcraft.yaml
> +  detect-hardwares:
> I don't mind either way really.

Same, please consider this non-blocking

2024-04-26 07:19 UTC, jneo8 commented on charmcraft.yaml
> +        default: false
> Would be better to get a diff, then just showing the new list. And should be default to show the diff, if --apply, then apply

Do you mean showing the diff only?
I would like to show the full list now since it is still comparable by the naked eye.

2024-04-26 07:27 UTC, chanchiwai-ray commented on charmcraft.yaml
> +        default: false
As long as we know what's the difference is good enough to me

2024-04-26 07:28 UTC, chanchiwai-ray commented on charmcraft.yaml
> +      `--apply` is provided.
I think `apply` not `--apply`

2024-04-26 09:00 UTC, jneo8 commented on charmcraft.yaml
> +      `--apply` is provided.
Updated.

2024-04-26 09:42 UTC, dashmage requested changes
Left some comments regarding the naming. Otherwise, the logic is good :)

2024-04-26 09:42 UTC, dashmage commented on charmcraft.yaml
> +  detect-hardware:
nit: I know the conversation regarding this has been resolved already but I would like to suggest `redetect-hardware` as the action name to be more explicit about the functionality. The charm has already detected the hardware once automatically and now the user is explicitly "redetecting" it to fetch the latest hardware list.

2024-04-26 09:42 UTC, dashmage commented on src/charm.py
> +        result = {
I feel similarly to you regarding the var name `consistent` being confusing to understand. I would prefer it be called as `new_hw_detected`. We can set it to false if `current_hw_tools_str_list == detected_hw_tool_str_list` and true otherwise.

Regarding `apply`, I'd like to suggest the name `update_hw_tools` which would be `True` if the new hardware tool list needs to be applied.

2024-04-26 11:29 UTC, rgildein commented on tests/unit/test_charm.py
> +        print(expect_output)
I think you forgot to remove these lines.

2024-04-26 11:52 UTC, dashmage commented on tests/unit/test_charm.py
> +        print(expect_output)
This isn't part of your changes in this PR, but it would be nice if you could similarly remove this `print` statement usage left behind in the unit tests: https://github.com/canonical/hardware-observer-operator/blob/master/tests/unit/test_charm.py#L278

2024-04-29 02:12 UTC, jneo8 commented on src/charm.py
> +        result = {
Updated

2024-04-29 02:12 UTC, jneo8 commented on charmcraft.yaml
> +  detect-hardware:
Updated

2024-04-29 02:12 UTC, jneo8 commented on tests/unit/test_charm.py
> +        print(expect_output)
Thanks, it's removed.

2024-04-29 03:50 UTC, chanchiwai-ray commented on src/charm.py
> +            hw_change_detected = True
I am a bit confused about this: why does `hw_changed_detected = True` if current and detected hw_tools are the same?

2024-04-29 04:18 UTC, dashmage commented on src/charm.py
> +            hw_change_detected = True
We should only set this flag when there's any changes present. So,
```
if current_hw_tools_str_list != detected_hw_tool_str_list:
    hw_change_detected = True
```

2024-04-29 05:05 UTC, jneo8 commented on src/charm.py
> +            hw_change_detected = True
Thanks, I forget to reverse the logic of `hw_change_detected`. It's updated in the newest commit.

2024-04-29 05:14 UTC, dashmage approved these changes
LGTM :rocket: Thanks for addressing the var name related changes!

2024-04-29 05:27 UTC, Pjack requested changes

2024-04-29 05:27 UTC, Pjack commented on src/charm.py
> +        # Show compare lists if not hw_change_detected
The comment seems not correct. Actually I prefer
1. show current hardware tools list if no changed detected.
current-hardware-tools
hardware-change-detected: false

2. show current-hardware-tools and detected-hardware-tools if hardware-change-detected is true.

What do other people think? it's a kind of user behavior design.

2024-04-29 06:37 UTC, jneo8 commented on src/charm.py
> +        # Show compare lists if not hw_change_detected
Updated

2024-04-29 07:04 UTC, Pjack approved these changes

2024-04-29 07:10 UTC, chanchiwai-ray approved these changes

2024-04-29 07:23 UTC, merged