Refactor to support multiple exporters
canonical/hardware-observer-operator pull request #228
Opened 2024-04-25 09:58 UTC by sudeephb

Some refactor so that adding a new exporter becomes simpler. After this is merged, a new exporter can be added by implementing:
1.  a new `XxxExporter` class that inherits from `BaseExporter`.
2. Initialize the new exporter in charm init and append it to `self.exporters`. 

Unit tests will be updated and added after this is merged, the target is a dev branch.

2024-04-26 01:10 UTC, jneo8 requested changes

2024-04-26 01:10 UTC, jneo8 commented on src/exporter_helpers.py
> +
**nitpick:** 

Require `__all__ = ["get_exporter", "remove_exporter", ...]`

2024-04-26 01:10 UTC, jneo8 commented on src/charm.py
> +from exporter_helpers import (
**nitpick:** 

After adding `__all__` in the exporter_helpers module. You can change this line to

```
import exporter_helpers

exporter_helpers.some_function()
```

2024-04-26 01:10 UTC, jneo8 commented on src/charm.py
> +        if all(exporters_health):
**nitpick:** 

If not?

2024-04-26 02:41 UTC, sudeephb commented on src/charm.py
> +        if all(exporters_health):
It is handled inside `check_exporter_health`. The unit will be blocked with the name of the failed exporter.

2024-04-26 02:49 UTC, chanchiwai-ray commented on config.yaml
> +      Start the prometheus hardware exporter at "exporter-port". By default,
The description also need to be updated: "exporter-port"

2024-04-26 02:51 UTC, chanchiwai-ray commented on requirements.txt
> +pydantic
I am a bit surprise this will work: this should break the dependency of `cos_agent.py` in https://github.com/canonical/grafana-agent-operator/blob/49abf15ffcde20d02961118f921c34565084a310/lib/charms/grafana_agent/v0/cos_agent.py#L239.

2024-04-26 02:54 UTC, chanchiwai-ray commented on src/exporter_helpers.py
> +
Same question: why wouldn't it work without `__all__`?

2024-04-26 02:58 UTC, sudeephb commented on src/exporter_helpers.py
> +
It does work. I have tested and updated the import without using `__all__`.

2024-04-26 02:58 UTC, jneo8 commented on src/exporter_helpers.py
> +
Relate to this [one](https://github.com/canonical/hardware-observer-operator/pull/228#discussion_r1580314938)

2024-04-26 03:12 UTC, chanchiwai-ray commented on src/charm.py
> +        hardware_exporter = exporter_helpers.get_exporter(
the logic inside `exporter_helpers.get_exporter` should be less aggressive: only install the exporter if there exporter related file (service file, config file not found, i.e. it should check `exporter.exporter_service_path.exists()` before install the exporter).

In short: singleton: the `get_exporter` function should get the existing exporter instance, if not found, create one and return that one.

2024-04-26 03:12 UTC, chanchiwai-ray commented on src/exporter_helpers.py
> +def get_installed_exporters(all_exporters) -> List:
This function can be superseded by `get_exporter` if the `get_exporter` is doing what I described above: get the existing exporter instances, if not found, create new one and return

2024-04-26 03:23 UTC, sudeephb commented on requirements.txt
> +pydantic
Yes, it's probably because compatible versions were installed. 
I have pinned pydantic to `<2` in here as well.

2024-04-26 11:48 UTC, dashmage approved these changes
Others have mentioned most of the comments that came to my mind as well. This is quite a big change and I noticed that there aren't any additional tests. Perhaps we could test the functionality of multiple exporter support by creating a dummy exporter and then testing out the various methods? But the logic itself LGTM and since it's going to a dev branch, we can address this later as well.

Good thing you decided to split up the work into multiple PRs. The code looks quite modular now :clap:

2024-04-29 02:42 UTC, sudeephb commented on src/charm.py
> +from exporter_helpers import (
I changed it to simply `import exporter_helpers` and used `exporter_helpers.fn()` everywhere. Let me know if it looks good to you.

2024-04-29 03:31 UTC, chanchiwai-ray approved these changes
Since it's not targeted to master branch, let's test it and iterate on this

2024-04-29 06:41 UTC, merged