Improve functest
canonical/hardware-observer-operator pull request #24
Opened 2023-06-30 10:05 UTC by chanchiwai-ray

Add basic functional testing for the charm.

2023-06-30 10:15 UTC, jneo8 requested changes

2023-06-30 10:15 UTC, jneo8 commented on src/charm.py
> +        self.exporter.install(dict(self.model.config))
**nitpick:** 

It's not useful in the future if we have more configuration that is not required by exporter.

2023-06-30 10:15 UTC, jneo8 commented on tests/functional/conftest.py
> +class Helper:
**nitpick:** 

helper is too generic.

2023-06-30 10:25 UTC, chanchiwai-ray commented on tests/functional/conftest.py
> +class Helper:
DONE

2023-06-30 10:25 UTC, chanchiwai-ray commented on src/charm.py
> +        self.exporter.install(dict(self.model.config))
DONE

2023-06-30 10:35 UTC, Pjack approved these changes

2023-06-30 10:56 UTC, jneo8 approved these changes
Wait for functional test pass.

2023-06-30 11:11 UTC, sudeephb approved these changes

2023-07-04 08:56 UTC, chanchiwai-ray commented
Not sure why it's failing on github runner; test on local lxd cloud works https://pastebin.ubuntu.com/p/gTgXSwk563/

2023-07-05 08:38 UTC, merged