Skip tests that require service when no hardware is present
canonical/hardware-observer-operator pull request #245
Opened 2024-05-22 08:44 UTC by sudeephb

2024-05-22 11:45 UTC, dashmage requested changes
I have a couple of questions on the changes. But maybe this might be due to the fact that I'm not fully sure about the extent of the refactor with multiple exporter support. So if you could provide a bit more context, that would be really helpful :smile:

2024-05-22 11:45 UTC, dashmage commented on tests/functional/test_charm.py
> +    """Perform basic functional tests that require a service to be present."""
Could we be a bit more clear here on what "service" means? I presume that the tests in the `TestCharm` class are still for testing without actual hardware though.

2024-05-22 11:45 UTC, dashmage commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
But doesn't this mean that for hardware independent tests, we won't be adding the cos-agent relation and wouldn't the charm be in a blocked state?

2024-05-23 02:47 UTC, chanchiwai-ray commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
This makes sense for the dev branch now, since the `self.exporters` is now hardware dependent if you check the code. But I am not sure if that the right choice to make though, since exporter will only be enabled when hardware + cos agent relation joined now, cc @jneo8 is the what you expected when you support multiple exporter?

2024-05-23 04:59 UTC, jneo8 commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
It make sense for charm's functionality. You don't want to install a GPU exporter without GPU device available.

2024-05-23 05:01 UTC, jneo8 commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
Also the purpose we have here is just check exporter service is available. We can verify that on unit-tests and real-hardware functional tests.

2024-05-24 03:57 UTC, sudeephb commented on tests/functional/test_charm.py
> +    """Perform basic functional tests that require a service to be present."""
I have updated the docstring to `Perform tests that require one or more exporters to be present.` I hope it's clearer now. What do you think?

2024-05-24 03:58 UTC, sudeephb commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
+1
Now that we don't have any exporters when there's no hardware present, we can test all the functionality that requires exporters(which includes checking if exporter service is available), only when the hardware is present.

2024-05-24 04:07 UTC, dashmage commented on tests/functional/test_charm.py
> +    """Perform basic functional tests that require a service to be present."""
Yep this is good, thanks!

2024-05-24 04:08 UTC, dashmage commented on tests/functional/test_charm.py
> +@pytest.mark.realhw
I understand now, thanks for the responses :smile:

2024-05-24 04:09 UTC, dashmage approved these changes
LGTM

2024-05-24 07:16 UTC, jneo8 approved these changes

2024-05-24 09:37 UTC, merged