Add ipmiseld intergration with unit test
canonical/hardware-observer-operator pull request #250
Opened 2024-05-29 05:01 UTC by zxhdaze

Add ipmiseld intergration, it will be installed and run automatically if bmc is available.
This is draft PR. Still need to add function test.

2024-05-30 03:23 UTC, sudeephb commented on tests/unit/test_hw_tools.py
>  class TestIPMISENSORStrategy(unittest.TestCase):
You don't need to add test for installing ipmiseld under TestIPMISENSORStrategy(Same for DCMI). If the IPMI Sensor is later rewritten in such a way that it's not handled together with ipmi-sel, ipmi-seld, etc, then we still want the tests to pass even if seld is not installed. 
So, I recommend creating a new test class TestIPMISELDStrategy, where you can verify ipmi-seld is installed. Other existing tests(including this) can be left untouched as far as possible.

2024-05-30 03:27 UTC, jneo8 requested changes

2024-05-30 03:27 UTC, jneo8 commented on src/hw_tools.py
> +    ipmiseld_pkg = "freeipmi-ipmiseld"
**question:** 

Why this one is not in the `IPMISELStrategy`?

2024-05-30 03:27 UTC, jneo8 commented on src/hw_tools.py
> +            result = subprocess.check_output("ipmiseld", universal_newlines=True)
**suggestion:** 

ipmiseld is a systemd service, check service status will be a more better way to verify it's running.

Also I suggest you to move the verify logic to a independent function so you can test it more easily.

2024-05-30 03:27 UTC, jneo8 commented on src/hw_tools.py
> +    ipmiseld_pkg = "freeipmi-ipmiseld"
**suggestion:** 

Please add some comment to mention the reason why we want to install `ipmiseld`, other people may confuse the reason behind.

2024-05-30 03:33 UTC, Pjack commented on src/hw_tools.py
>      pkg = "freeipmi-tools"
We could give a better name for these two packages.

2024-05-30 03:33 UTC, Pjack commented on src/hw_tools.py
> +        try:
What is the major reson we have to check the process here? I cannot find similiar logic when installing other packages. It should be handled by the `apt install xxxxx` itself.

2024-05-30 03:45 UTC, zxhdaze commented on src/hw_tools.py
> +            result = subprocess.check_output("ipmiseld", universal_newlines=True)
This is actually to ensure the systemd service to be running instead of a check. But consider the service will be running automatically after install, maybe I can add a independent function for verifying.

2024-05-30 04:00 UTC, zxhdaze commented on tests/unit/test_hw_tools.py
>  class TestIPMISENSORStrategy(unittest.TestCase):
Should I create a strategy for ipmiseld? Now I'm thinking about moving the installation of ipmiseld under ipmi-sel strategy, and also test it at TestIPMISELStrategy.

2024-05-30 04:39 UTC, zxhdaze commented on src/hw_tools.py
> +    ipmiseld_pkg = "freeipmi-ipmiseld"
Just moved it under IPMISELStrategy

2024-05-30 04:41 UTC, zxhdaze commented on src/hw_tools.py
> +        try:
You are right, I just removed the check process.

2024-05-30 04:42 UTC, zxhdaze commented on src/hw_tools.py
>      pkg = "freeipmi-tools"
I just moved the installation of the other package under IPMISELStrategy.

2024-05-30 04:48 UTC, dashmage requested changes
Left some comments, great work so far :clap:

2024-05-30 04:48 UTC, dashmage commented on src/hw_tools.py
> +        logger.info("%s skip removing %s", self._name, self.ipmiseld_pkg)
Aren't you overriding the default super class `remove` method functionality here? So it wouldn't log for the freeipmi pkg now.

2024-05-30 04:48 UTC, dashmage commented on src/hw_tools.py
> +        parent_pkg_installed = super().check()
Wouldn't this be more simply expressed like,

```python
freeipmi_pkg_installed = check_deb_pkg_installed(self.freeipmi_pkg)
ipmiseld_pkg_installed = check_deb_pkg_installed(self.ipmiseld_pkg)
return freeipmi_pkg_installed and ipmiseld_pkg_installed
```
so we don't have to refer to the super class behaviour here.

It would also be nice if you changed `pkg` --> `freeipmi_pkg`

2024-05-30 08:14 UTC, jneo8 commented on src/hw_tools.py
> +            result = subprocess.check_output("ipmiseld", universal_newlines=True)
If `ipmiseld` systemd service status is active. It should be fine?

2024-05-30 08:26 UTC, jneo8 requested changes
Need to add more information to the code base.
Others are LGTM.

2024-05-30 08:53 UTC, dashmage commented on src/hw_tools.py
> +        parent_pkg_installed = super().check()
Since the logic isn't that complex, I feel it's better to let the overriding method take over the logic and not invoke the super(). That's only my opinion though. The code looks better that way.

2024-05-30 11:50 UTC, zxhdaze commented on src/hw_tools.py
> +        logger.info("%s skip removing %s", self._name, self.ipmiseld_pkg)
Right, I will add a super() call here too.

2024-06-04 07:40 UTC, rgildein commented on src/hw_tools.py
> +        parent_pkg_installed = super().check()
And what will happen when the check for `freeipmi_pkg` changed? You will need to manage it on two places.

2024-06-05 05:59 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        super().install()
I am not familiar with the strategy class, why do we call `super()` in the class? Is it possible that we can have a case where we only need `freeipmi-ipmiseld` but not `freeipmi-tools`?

2024-06-05 06:05 UTC, chanchiwai-ray commented on src/hw_tools.py
>  class IPMISELStrategy(IPMIStrategy):
Again not familiar with the strategy class, why are we inheriting from `IPMIStrategy`? Aren't they different package?

2024-06-05 09:36 UTC, jneo8 approved these changes
Overall it's good for me. But we still need to work on https://github.com/canonical/hardware-observer-operator/issues/251

2024-06-05 09:36 UTC, jneo8 commented on src/hw_tools.py
>  class IPMISELStrategy(IPMIStrategy):
If `freeipmi-tools` is required, then it make sense. @zxhdaze can you confirm this?

2024-06-05 15:18 UTC, aieri commented on src/hw_tools.py
> +        super().install()
I don't believe so. I think the check should fundamentally be
```
if I have a bmc:
    install everything I have related to ipmi
```

2024-06-06 02:57 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        super().install()
Ff we have a bmc, the parent class will install `freeipmi-tools`. But then this class inherit from the parent class and call `super().install` again before installing `freeipmi-ipmiseld`. So the total calls for `install` if we have a bmc is:

install `freeipmi-tools` x 1
install `freeipmi-tools` x 1 + `freeipmi-ipmiseld` x 1

Of course if the second install `freeipmi-tools` is idempotent that's fine, but practically no need to inherit from the parent

2024-06-06 03:00 UTC, chanchiwai-ray commented on src/hw_tools.py
>  class IPMISELStrategy(IPMIStrategy):
`apt info freeipmi-seld` does not depend on `freeipmi-tools` (package wise) but it could be a runtime dependency, I am not sure

2024-06-06 14:44 UTC, zxhdaze commented on src/hw_tools.py
> +        super().install()
Not sure about this but from what I have seen, the bmc_hw_verifier() doesn't check parent class. It only checks if each child class is available and add them to the list. So the freeipmi-tools would be only installed once in this scenario?

2024-06-06 14:48 UTC, zxhdaze commented on src/hw_tools.py
>  class IPMISELStrategy(IPMIStrategy):
I don't think it depends on freeipmi-tools, but as @aieri  mentioned we should install everything is bmc is available.

2024-06-06 18:52 UTC, dashmage approved these changes
LGTM

2024-06-07 01:27 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        super().install()
Okay, I get it now. The `IPMIStrategy` is not in the strategy list: https://github.com/canonical/hardware-observer-operator/blob/main/src/hw_tools.py#L608, and that's kind of weird to me since that is not a abstract class.

2024-06-07 01:28 UTC, chanchiwai-ray commented on src/hw_tools.py
>  class IPMISELStrategy(IPMIStrategy):
Okay, I get it now. The IPMIStrategy is not in the strategy list: https://github.com/canonical/hardware-observer-operator/blob/main/src/hw_tools.py#L608, and that's kind of weird to me since that is not a abstract class.

2024-06-07 02:53 UTC, merged