fix: redfish validation
canonical/hardware-observer-operator pull request #276
Opened 2024-07-08 02:23 UTC by jneo8

Skip redfish validation if either username or password is missing
fix: #270

2024-07-08 02:31 UTC, samuelallan72 requested changes

2024-07-08 02:31 UTC, samuelallan72 commented on src/service.py
> +            logger.warning("Empty redfish certificate, skip validation.")
This log message references a certificate, but the check is for username and password.

2024-07-08 02:31 UTC, samuelallan72 commented on src/service.py
> +        if redfish_conn_params and not (
The previous statement already checks for presence of redfish_conn_params.

```suggestion
        if not (
```

2024-07-08 02:53 UTC, samuelallan72 approved these changes
Looks good thanks, just one little nit in the tests.

2024-07-08 02:53 UTC, samuelallan72 commented on tests/unit/test_service.py
> +                "missing username",
nit

```suggestion
                "missing password",
```

2024-07-08 04:59 UTC, samuelallan72 approved these changes

2024-07-08 08:13 UTC, chanchiwai-ray approved these changes

2024-07-08 09:25 UTC, rgildein approved these changes
One not blocking comment.

2024-07-08 09:25 UTC, rgildein commented on src/service.py
> +        ):
```suggestion
        if not (redfish_conn_params.get("username") and redfish_conn_params.get("password")):
```

2024-07-09 01:52 UTC, jneo8 commented on src/service.py
> +        ):
It should be fine, it formated by black.

2024-07-09 01:53 UTC, merged