Fix integration test to use internal traefik address
canonical/hardware-observer-operator pull request #279
Opened 2024-07-15 23:47 UTC by zxhdaze

2024-07-16 00:25 UTC, samuelallan72 requested changes
Thanks for this.  I left some comments.

Also please note that this isn't getting the internal ip of traefik, this is getting the ip address that traefik is configured to serve on - it should be one of the k8s cluster public/exposed ip addresses.  Eg. if this is microk8s using metallb, it will be one of the metallb addresses.

2024-07-16 00:25 UTC, samuelallan72 commented on tests/integration/test_cos_integration.py
> +    result_json = stdout.split("proxied-endpoints: ")[1].strip().strip("'")
This kind of string processing is error-prone.  Instead please use the `--format json` flag to `juju run` above, and then you can parse the stdout as json.

2024-07-16 00:25 UTC, samuelallan72 commented on tests/integration/test_cos_integration.py
> +    prometheus_alerts_endpoint = f"{traefik_url}/{model_name}-prometheus-0/api/v1/alerts"
This is strange to me - in my experience, there isn't a `traefik` key in proxied endpoints (because traefik proxies to other applications, not to itself).  And you should be able to get the url for prometheus from this output at `proxied-endpoints.prometheus/0.url`.

2024-07-18 02:01 UTC, jneo8 submitted a review, later dismissed
LGTM, can you add some comments to explain behavior here?

2024-07-18 02:01 UTC, jneo8 commented on tests/integration/test_cos_integration.py
> +    returncode, stdout, stderr = await ops_test.run(
**suggestion (non-blocking):** 

Can you leave some comment to explain why we need this?

2024-07-18 02:16 UTC, chanchiwai-ray submitted a review, later dismissed
LGTM, thanks

2024-07-18 02:16 UTC, chanchiwai-ray commented on tests/integration/test_cos_integration.py
> +    returncode, stdout, stderr = await ops_test.run(
I also think it will be nice to have that. I found my answer here https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s#heading--browse-dashboards

2024-07-18 02:24 UTC, samuelallan72 submitted a review, later dismissed
LGTM, thanks!

2024-07-19 03:44 UTC, chanchiwai-ray approved these changes

2024-07-19 03:46 UTC, jneo8 approved these changes

2024-07-22 13:43 UTC, merged