Add config options for redfish
canonical/hardware-observer-operator pull request #28
Opened 2023-07-05 07:35 UTC by sudeephb

2023-07-05 08:29 UTC, jneo8 approved these changes

2023-07-05 11:04 UTC, esunar approved these changes

2023-07-05 11:31 UTC, Pjack requested changes
Raise a concern but not strong disagree. Let's think about that 1 more day before merge into master branch.

2023-07-05 11:31 UTC, Pjack commented on src/charm.py
> +        redfish_creds = {
Similiar situation in 
https://github.com/canonical/prometheus-hardware-exporter/pull/16/files
Parameters of redfish is only used in collectors. If we have more collectors, the parameters may become very long. 

My another concern is the mapping has to be exactly correct, there are many layers and conversions. 

Config of charm  ->   Exporter.install (encalpulate as redfish_creds)-> config_template.render (extract and write to file) -> prometheus-hardware-exporter.main (read config). 

I would like to reduce the conversion to avoid error. e.g. Config of charm ----> (write to file) -> prometheus-hardware-exporter.main (read config).  This is a place I feel we may refactor one day.

2023-07-06 02:15 UTC, jneo8 commented on src/charm.py
> +        redfish_creds = {
One way to make sure the quality is to define dataclass in config instead of inline code.

2023-07-06 08:20 UTC, Pjack commented on src/charm.py
> +        redfish_creds = {
Based on the discussion, it's not a serious problem at this moment. I will let the MR pass

2023-07-06 08:25 UTC, chanchiwai-ray commented
Can you add functional test for this?

2023-07-06 09:05 UTC, Pjack approved these changes

2023-07-06 09:51 UTC, chanchiwai-ray commented on tests/functional/test_charm.py
> +            app.set_config({"redfish-host": new_redfish_host}),
Note sure if they can be on the same function `set_config`. Also, can you rebase onto the master again? I've increased the timeout for functional test. Hopefully the tests can be finished on the runner.

2023-07-10 04:29 UTC, merged