Add TESTING.md
canonical/hardware-observer-operator pull request #280
Opened 2024-07-18 15:19 UTC by zxhdaze

Add instruction about how to setup hw-obs + COS on real hardware.

2024-07-18 23:25 UTC, samuelallan72 requested changes
Thanks for adding these docs!  I read through and left some comments about structure and formatting, and some comments about things I was confused about and may need to be clearer to those that aren't familiar with this testing.

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +# Deploy hardware-observer with COS on real machine
Why is this in a file called `SETENV.md`?  Is this a new wellknown file like readme.md or contributing.md?

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +
I think we can leave out these juju setup instructions, maybe just linking to juju docs.  There are many ways to set up juju or a controller.  Could we structure it more like:

```
## Prerequisites

<a note about juju controller>

### Extra requirements if using juju controller on LXD

<your notes below about using a different bridge> 
```

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +$ lxc network delete lxdbr0
All these code snippets should be formatted as code blocks.  Either using backticks

    ```
    $ cmd
    ```

or indenting:

```
    $ cmd
```

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +To add local machine to the controller, you need to pass the juju client credential to it:
This can be in a new section like "Add local machine".

Also the terminology could be more consistent - here we're using local machine, real machine, and real hardware to refer to the same thing.

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +This command will show the dashboard endpoint and default password, the default uername is "admin".
```suggestion
This command will show the dashboard endpoint and default password.  The default username is "admin".
```

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +Now you should be able to access the dashboard.
Maybe list the name of the dashboard here?

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +$ cat ~/.local/share/juju/ssh/juju_id_rsa.pub >> ~/.ssh/authorized_keys
This implies the local workstation where you're running juju; this seems like a footgun, as a developer may not realise or want juju agents running on their workstation.

I'm not sure how testing locally is being done with hardware observer, but I'd suggest these instructions be clearer about requirements and prerequisites for the machine that is to be manually added.  Eg. must be ubuntu X, accessible over the network, must have the juju ssh key on it, etc.

2024-07-18 23:25 UTC, samuelallan72 commented on SETENV.md
> +$ juju add-machine ssh:username@ip.add.re.ss
Is `username` arbitrary?

2024-07-19 03:42 UTC, chanchiwai-ray commented on SETENV.md
> +This guide outlines the steps to deploy the hardware-observer and COS on real hardware.
I think `real hardware` can be replaced by `physical machine`

2024-07-19 03:42 UTC, chanchiwai-ray commented on SETENV.md
> +Here, "real hardware" refers to machines that are not VMs or containers and have access to real
Same here `real hardware` -> `physical machine`. 

On the other note, 

> ... hardware resources like RAID cards and BMC management tools.
 
looks like a prerequisite. May be we should convert it to a prerequisite session. For example:

```
# Deploy hardware-observer with COS on physical machine

This guide outlines the steps to deploy the hardware-observer and COS on physical hardware.

**prerequisite**

- blah
- blah
- blah

```

2024-07-22 19:28 UTC, aieri commented on SETENV.md
> +# Deploy hardware-observer with COS on real machine
this guide is essentially about setting up a development environment. I see all of these as pretty good options:
* dev environment section in README.md (if not too long)
* contributing.md (hard to contribute without a dev environment :))
* dev-environment.md (to keep the setup separate from more generic development guidelines)

2024-07-22 19:31 UTC, aieri commented on SETENV.md
> +Here, "real hardware" refers to machines that are not VMs or containers and have access to real
well, I think we should be clear about the limitations of running hardware observer on a machine without any of those, but at the same time it's not a strict requirement. For example, you might only need to develop better mdadm integration, so a consumer-grade desktop PC would be sufficient (and technically even simply a VM)

2024-07-22 19:35 UTC, aieri commented on SETENV.md
> +$ lxc network delete lxdbr0
and consider dropping the `$` if you want to facilitate copy/pasting (in this context I think it would be better)

2024-07-22 19:35 UTC, aieri commented on SETENV.md
> +$ cat ~/.local/share/juju/ssh/juju_id_rsa.pub >> ~/.ssh/authorized_keys
that's a fair point. How about having a prerequisite of "you have a physical machine you can fully take over and expect to redeploy when you're done". On one hand you don't want to leave too many things as "exercise for the reader" or following the guide would become too cumbersome, on the other hand it has to be clear to the reader what the expected environment they'd be running these commands in is supposed to be

2024-07-23 21:58 UTC, zxhdaze commented on SETENV.md
> +Here, "real hardware" refers to machines that are not VMs or containers and have access to real
Well I think this doc can focus on deploying hardware-observer on a physical machine. For users of VM they may just follow the general guide on charmhub.

2024-07-24 05:40 UTC, aieri requested changes

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +This guide outlines the steps to deploy the hardware-observer and COS on physical machine.
I think it'd be worth explaining that we're proposing an unusual topology and why. In a normal production scenario there's no need for anything more complex than 1. have a controller, 2. deploy hardware observer on a physical machine, 3. connect to an existing COS. For example:
```
Most of hardware observer's functionality can only be experienced when installing the charm on server-grade hardware and relating to a COS installation. As this can be a relatively expensive setup, we are offering this guide to document how to create an environment for development or rapid prototyping on a single physical host. Note that the proposed topology is in no way appropriate for production, nor it can be considered a supported deployment.
```

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +### Extra requirements if using juju controller on LXD
```suggestion
### Extra requirements
```
I think we should be specific: this is _our_ proposed dev environment setup. No need to have ifs and buts.

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +If you try to add a local machine to the LXD controller. You will need to create a new bridge:
```suggestion
Due to some [historical reasons](https://bugs.launchpad.net/juju/+bug/1964513), the machine hosting the LXD controller cannot be added to the model unless the default LXD bridge is renamed.
```

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +If you have a physical machine that you can fully take over and expect to redeploy when you're done, you can follow these steps to add it to juju.
maybe move this suggestion to the opening paragraph as a disclaimer? This would allows you to be more prescriptive here and simplify

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +To add physical machine to the controller, you need to pass the juju client credential to it:
'pass' is rather vague
```suggestion
To add the physical machine to the model, you need to allow the juju client to log into it via SSH:
```

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +juju add-machine ssh:<username>@ip.add.re.ss
is this right? shouldn't we create the model first? this command may add the new machine to the controller model if it's the only one

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +Now you should be able to access to grafana.
```suggestion
Now you should be able to access grafana.
```

2024-07-24 05:40 UTC, aieri commented on dev-environment.md
> +To integrate hardware-observer with COS, you can follow this [guide](https://charmhub.io/hardware-observer/docs/integrate-with-cos)
eh, I'm generally ok with referencing other docs instead of copypasting but I think this is too much: the reader would need to click on this link, then click on https://juju.is/docs/sdk/dev-setup (it's the first sentence in the referenced document), then... wonder what they actually want or need.

I think this document should be very opinionated: "here is how to set up a simple dev environment on a single machine. Do this, then this, then this". While some of those steps may be held in other pages, I think we should be careful to only reference specific blocks of code that don't include if statements.

Or to use diataxis parlance, it looks to me like we're mixing tutorials with explanations here.

2024-07-24 23:40 UTC, aieri requested changes
I have several suggestions but the document is already looking quite good and usable, thanks!

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +Then you can manually add physical machine, switch to the controller you just created and run:
suggestion:
```suggestion
Now you can create a model and add your physical machine via the manual provider:
```

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +To add the physical machine to the model, you need to allow the juju client to log into it via SSH:
iirc you can only add a machine if the juju client can then elevate its privileges
```suggestion
To add the physical machine to the model, you need to allow the juju client to log into it via SSH as a user with sudo rights. On an Ubuntu machine, the `ubuntu` user typically satisfies this requirement:
```

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +juju add-machine ssh:<username>@ip.add.re.ss
```suggestion
# use a different username if needed 
# any IP belonging to the host should work  
juju add-machine ssh:ubuntu@ip.add.re.ss
```

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +juju add-model hw-obs
no longer necessary given line 40

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +Install MicroK8s package, it is recommanded to use a strictly confined version:
I'm curious, why? Especially since this is a dev environment

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +sudo chown -f -R $USER ~/.kube
interesting, wouldn't you already be able to read `~/.kube` since it's in your own home?

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
interesting trick, is this to fetch the src of the default route? Because if that's the case going for `2.2.2.2` isn't strictly necessary

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +Before deploy COS bundle, wait for all the microk8s addons to be rolled out:
```suggestion
Before deploying the COS bundle, wait for all the microk8s addons to be rolled out:
```

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +Create model and deploy COS-lite bundle:
```suggestion
Create a COS model and deploy COS-lite bundle:
```

2024-07-24 23:40 UTC, aieri commented on dev-environment.md
> +Switch to lxd-controller and add necessary relations:
```suggestion
Switch back to your physical model and add the relations to COS:
```

I guess? You'd also need to show the `juju switch hw-obs` command

2024-07-25 00:26 UTC, samuelallan72 commented on dev-environment.md
> +Install MicroK8s package, it is recommanded to use a strictly confined version:
I believe this is actually a requirement - latest juju will refuse to bootstrap on a non-strictly confined microk8s.

2024-07-26 00:20 UTC, zxhdaze commented on dev-environment.md
> +Install MicroK8s package, it is recommanded to use a strictly confined version:
As https://github.com/canonical/bundle-kubeflow/issues/830 reports, juju 3.x requires Microk8s snap install in strictly confinement. I have changed it to "required".

2024-07-26 22:56 UTC, zxhdaze commented on dev-environment.md
> +sudo chown -f -R $USER ~/.kube
Not sure how it works but if I don't give permission I will have to use `sudo` on the rollout command.

2024-07-30 01:58 UTC, jneo8 requested changes
Two suggestions

2024-07-30 01:58 UTC, jneo8 commented on dev-environment.md
> +To add the physical machine to the model, you need to allow the juju client to log into it via SSH as a user with sudo rights. On an Ubuntu machine, the `ubuntu` user typically satisfies this require
**suggestion:** 

Can you add a description it's juju controller on LXD cloud and machine is added manually? And why we choose LXD cloud to bootstrap the controller?

More to ask, are you sure it's working always? As I remember, if you adding machine using `juju add-machine ssh:xxxxxx`, the machine will try to send request to juju controller to register itself. The LXD juju controller may have issue that the machine can't connect to the controller.

2024-07-30 01:58 UTC, jneo8 commented on dev-environment.md
> +```
**suggestion:** 

As I understand, it's a two controllers setup. How do you make sure the connection to juju controller is working?

Do you need more config to bootstrap?

```
juju bootstrap microk8s k8s-controller --debug --config controller-service-type=loadbalancer --config controller-external-ips=[10.11.12.13]
```

2024-07-30 19:08 UTC, aieri commented on dev-environment.md
> +Set up microk8. Steps can be found in this [guide](https://juju.is/docs/sdk/dev-setup?_gl=1*nsqfdk*_ga*MjEzOTcxMzA2OS4xNzEwMzYzNDU0*_ga_5LTL1CNEJM*MTcyMjI5NDE2MC4xMDMuMS4xNzIyMjk0MTY4LjUyLjAuMA..).
is this link correct? It simply sends me to the juju dev environment setup page.
And why the complex URL parameters?

2024-07-30 19:08 UTC, aieri commented on dev-environment.md
> +Set up microk8. Steps can be found in this [guide](https://juju.is/docs/sdk/dev-setup?_gl=1*nsqfdk*_ga*MjEzOTcxMzA2OS4xNzEwMzYzNDU0*_ga_5LTL1CNEJM*MTcyMjI5NDE2MC4xMDMuMS4xNzIyMjk0MTY4LjUyLjAuMA..).
oh and s/microk8/microk8s/

2024-07-30 19:08 UTC, aieri commented on dev-environment.md
> +To add the physical machine to the model, you need to allow the juju client to log into it via SSH as a user with sudo rights. On an Ubuntu machine, the `ubuntu` user typically satisfies this require
I think we could reduce the risk of connectivity issues by asking users to use the lxd bridge address for the physical host. So something like

```
BR0_ADDR=$(ip -4 -j a sho dev br0 | jq -r .[].addr_info[0].local)
juju add-machine ssh:ubuntu@$BR0_ADDR
```

2024-07-30 23:37 UTC, zxhdaze commented on dev-environment.md
> +Set up microk8. Steps can be found in this [guide](https://juju.is/docs/sdk/dev-setup?_gl=1*nsqfdk*_ga*MjEzOTcxMzA2OS4xNzEwMzYzNDU0*_ga_5LTL1CNEJM*MTcyMjI5NDE2MC4xMDMuMS4xNzIyMjk0MTY4LjUyLjAuMA..).
The MicroK8s setup instructions is under the Juju development environment setup page. I've updated the link to point directly to the relevant section.

2024-07-30 23:39 UTC, zxhdaze commented on dev-environment.md
> +```
I've tested this command on both local and Testflinger environments, and it consistently worked well. Given that this is intended for a general setup guide, I think maybe we can keep the command as it is?

2024-07-30 23:55 UTC, zxhdaze commented on dev-environment.md
> +To add the physical machine to the model, you need to allow the juju client to log into it via SSH as a user with sudo rights. On an Ubuntu machine, the `ubuntu` user typically satisfies this require
Updated this comment with LXD description. Also added the reason of using LXD at line 17.

2024-07-31 00:28 UTC, samuelallan72 commented on dev-environment.md
> +Set up microk8s. Steps can be found in this [guide](https://juju.is/docs/sdk/dev-setup?_gl=1*nsqfdk*_ga*MjEzOTcxMzA2OS4xNzEwMzYzNDU0*_ga_5LTL1CNEJM*MTcyMjI5NDE2MC4xMDMuMS4xNzIyMjk0MTY4LjUyLjAuMA..#he
Please remove unecessary url params:

```suggestion
Set up microk8s. Steps can be found in this [guide](https://juju.is/docs/sdk/dev-setup#heading--manual-set-up-your-cloud).
```

2024-07-31 09:57 UTC, jneo8 submitted a review, later dismissed

2024-08-01 18:34 UTC, aieri approved these changes

2024-08-02 07:24 UTC, Pjack approved these changes

2024-08-02 14:31 UTC, gabrielcocenza approved these changes

2024-08-02 22:29 UTC, samuelallan72 approved these changes

2024-08-02 22:45 UTC, merged