Clean up logic in `_on_config_changed` event
canonical/hardware-observer-operator pull request #285
Opened 2024-08-05 19:31 UTC by zxhdaze

Fixes: https://github.com/canonical/hardware-observer-operator/issues/284, https://github.com/canonical/hardware-observer-operator/issues/215

Issue https://github.com/canonical/hardware-observer-operator/issues/284 arises because there's no return statement following the defer() in the _on_config_changed event. When hardware-observer is deployed without a resource, the _on_config_changed event triggers, but no exporter gets installed. In the absence of a return statement, the function continues execution and may attempt to restart an exporter that hasn't been installed, which lead to a crash.

Additionally, adjust the logic to validate and render the configuration regardless of whether `cos-agent` relation is provided.

2024-08-06 01:48 UTC, jneo8 requested changes
Life cycle issue to discuss

2024-08-06 01:48 UTC, jneo8 commented on src/charm.py
> -        if self.cos_agent_related:
**issue (blocking):** 

The idea here is that exporter/configuration shouldn't exists is relation is not exists. The logic seems missing after you remove this line.

Can we change the proposal to check both exporters and relation exists then restart the exporter.

2024-08-06 06:43 UTC, chanchiwai-ray commented on src/charm.py
> -        if self.cos_agent_related:
I guess this was to fix the second issue in #215

2024-08-06 13:43 UTC, gabrielcocenza requested changes

2024-08-06 18:57 UTC, zxhdaze commented on src/charm.py
> -        if self.cos_agent_related:
@jneo8, I don't understand why we can't have the exporter/configuration standalone without the cos-agent relation. I imagine some users might only need to deploy hardware-observer without Grafana-agent.

2024-08-06 19:02 UTC, zxhdaze commented on tests/unit/test_charm.py
> +                    return
Moving this to other PR.

2024-08-06 23:52 UTC, aieri commented on src/charm.py
> -        if self.cos_agent_related:
adding to the above, why is it beneficial to only setup the exporter when the relation to grafana-agent exists? I get that without COS hardware-observer isn't very useful, but it shouldn't be a problem either, and it might help us simplify the lifecycle of the charm by removing dependencies

2024-08-07 00:32 UTC, samuelallan72 commented on src/charm.py
> -        if self.cos_agent_related:
We had this discussion a while back, for openstack-exporter as well, and we had arguments for and against.  I'm in the same camp as you @aieri ; COS isn't required for the exporter to run, so let's not add it as a dependency (and someone may wish to deploy it without COS for testing or want to use something manual to read the exporter).

2024-08-07 12:15 UTC, gabrielcocenza approved these changes

2024-08-07 20:04 UTC, zxhdaze commented on src/charm.py
> -        if self.cos_agent_related:
@jneo8 I have reversed this change since it is a life cycle issue, maybe we can leave it to be modified in the next life cycle change.

2024-08-07 21:00 UTC, gabrielcocenza requested changes
Just details to make the PR with less changes

2024-08-07 21:40 UTC, gabrielcocenza commented on tests/unit/test_charm.py
> +                    self.harness.charm._on_update_status.assert_called()
After rethink you can keep this way because of this `self.harness.charm._on_update_status.assert_called()`. We really need to refactor this unit test later :laughing:

2024-08-07 22:06 UTC, gabrielcocenza approved these changes

2024-08-08 02:03 UTC, chanchiwai-ray commented on src/charm.py
> -        if self.cos_agent_related:
Just note that, the second part of the issue in #215 is still there:

1. Install hw-observer with correct resource -> resource is installed (keeping cos-agent **not** related)
2. change config (e.g. ports: from 10000 to 10001) -> config will not be rendered because cos-agent is **not** related
3. relate cos-agent -> exporter still starts at port `10000` because the config changed is blocked in step 2

Maybe we can split the issue into two issues, and mark this PR fix the first issue?

2024-08-08 05:27 UTC, jneo8 approved these changes

2024-08-08 05:27 UTC, jneo8 commented on src/charm.py
> -        if self.cos_agent_related:
Thanks for checking this @zxhdaze, resolved

2024-08-08 14:11 UTC, merged