Add config option to disable redfish
canonical/hardware-observer-operator pull request #292
Opened 2024-08-19 20:52 UTC by gabrielcocenza

- new charm config to disable redfish. With that, even that redfish is detected the user has the option to disable it.
- applied suggestions to change terminology. current_tools mean the ones already stored as cache.
- detected_available_tools run again (not cached) to detect new hardware
- changed redfish_conn_params to be a class property
- created new class property enabled_tools to remove detected tools that are disabled
- removed the possibility of redfish_conn_params_valid return None
- created new property is_redfish_available_and_enabled

Partially-Closes #282

2024-08-19 21:42 UTC, gabrielcocenza commented
@Pjack from your previous questions on the closed PR:

> With this new implementation, we propose to continue the installation process but disable Redfish on that specific unit only. Is this the behavior you intend to propose?

In this PR I've created a new charm config to enable/disable the redfish collector on all units. The installation process does not change from the prior behavior of installing resources and render the necessary files to have the daemon service running.

> What about other special situations, such as intermittent network connection failures? We should be careful here, if we have more and more exception, it will make the situation become complex. Therefore, we should ask ourself: why we accept invalid password become an exception. What's the guideline?

Internet connection failures will result into a failing scrape and not changing to enable/disable so I don't see how the implementation will change the current behavior


> Will Redfish be dynamically disabled after the exporter been installed? Please avoid this behavior. Once enabled, metrics should be sent out continuously.

I didn't understand this question completely. HardwareExporter will be installed  if it's detected some tools that the class is responsible, including Redfish. The collector will start or not depending on the charm configuration to enable or disable redfish. If redfish is detected and enabled (default behavior), it will stop sending metrics only when user change the `redfish-enable` to false. Other possibility would be changing to a hardware that does not have redfish and run the `redetect-hardware` and apply (very very rare I guess....)

2024-08-20 06:30 UTC, Pjack commented
> @Pjack from your previous questions on the closed PR:
> 
> > With this new implementation, we propose to continue the installation process but disable Redfish on that specific unit only. Is this the behavior you intend to propose?
> 
> In this PR I've created a new charm config to enable/disable the redfish collector on all units. The installation process does not change from the prior behavior of installing resources and render the necessary files to have the daemon service running.
> 
> > What about other special situations, such as intermittent network connection failures? We should be careful here, if we have more and more exception, it will make the situation become complex. Therefore, we should ask ourself: why we accept invalid password become an exception. What's the guideline?
> 
> Internet connection failures will result into a failing scrape and not changing to enable/disable so I don't see how the implementation will change the current behavior
> 
> > Will Redfish be dynamically disabled after the exporter been installed? Please avoid this behavior. Once enabled, metrics should be sent out continuously.
> 
> I didn't understand this question completely. HardwareExporter will be installed if it's detected some tools that the class is responsible, including Redfish. The collector will start or not depending on the charm configuration to enable or disable redfish. If redfish is detected and enabled (default behavior), it will stop sending metrics only when user change the `redfish-enable` to false. Other possibility would be changing to a hardware that does not have redfish and run the `redetect-hardware` and apply (very very rare I guess....)


Your previous PR will disable Redfish automatically when the password is empty. I have these questions because of that change. These concerns won't be valid if it is controlled by a configuration and triggered by the user.

2024-08-20 06:44 UTC, Pjack reviewed
Did we verify these behavior?

1. Enable = True , and deploy the charm, corresponding alert/metrics are added..
2. Enable = False, and deploy the charm, corresponding alert/metrics are not available .
3. Enable = True at initial, change it to False, corresponding alert/metrics will be removed.
4. Enable = Falsee at initial, change it to True, corresponding alert/metrics are added.


Please also update 
1. integration test 
2. functional test
3. test mindmap in share folder 

They can be in different, but please track them in JIRA card. Thanks!

2024-08-20 09:25 UTC, jneo8 reviewed
non-blocking comments, feel free to resolved.

2024-08-20 09:25 UTC, jneo8 commented on src/charm.py
> +        current_tools = self.get_current_tools()
**nitpick (non-blocking):** 

*Current* is a vague naming. I like the old name more because it explain it's come from the stored.

2024-08-20 09:25 UTC, jneo8 commented on src/service.py
> +    def redfish_conn_params_valid(self) -> bool:
**nitpick (non-blocking):** 

I start to feel this function shouldn't be in this class.
We should have a simple helper function to valid the connection params.

2024-08-20 20:07 UTC, aieri commented on src/service.py
> +            REDFISH_ENABLE=self.is_redfish_available_and_enabled,
non-blocking suggestion: having a dedicated property seem overkill to me. I would just enable if redfish is in `enabled_tools`

2024-08-20 20:08 UTC, aieri commented on src/service.py
> +        if not self.is_redfish_available_and_enabled:
suggestion: you can safely discard non-existent items from sets so this if is redundant

2024-08-20 21:16 UTC, gabrielcocenza commented on src/service.py
> +    def redfish_conn_params_valid(self) -> bool:
Right now it's blocking the unit if user or password is wrong. I think this is still a good thing? But one thing that I didn't think about before is that if the user disable redfish I guess it does not make sense to validate the exporter configs

2024-08-20 22:26 UTC, gabrielcocenza commented on src/service.py
> +        if not self.is_redfish_available_and_enabled:
I didn't understand completely. It needs to have an if condition to remove when redfish is disable. I understand that doesn't matter if redfish is available or not. I've refactored a little bit and I guess I did what you expected.

2024-08-20 22:45 UTC, gabrielcocenza commented
@Pjack the CI uses a VM so there is no redfish so by consequence we can't check if disable/enable redfish will generate/stop metrics. 

Of course it's possible to run manual tests on a server or create tests under `TestCharmWithHW` , but currently we facing issues to reserve a server on testflinger. It seems that they will have testflinger back just on very late August or even early September. Not sure if this PR should be blocked until the service is back

2024-08-20 23:38 UTC, aieri commented on config.yaml
> +      Boolean flag to disable the Redfish collector. Defaults to enabled (if redfish is available).
Thanks for flipping the enable/disable logic, but now this description needs to be updated :D
```suggestion
      Boolean flag to force disabling the Redfish collector. The collector will normally be run if Redfish support is detected on the unit.
```

2024-08-20 23:38 UTC, aieri commented on src/charm.py
> +        arbitrary objects. HWTool object can however be re-instantiated from tool names.
Sorry my previous suggestion was not 100% correct
```suggestion
        arbitrary objects. HWTool objects can however be re-instantiated from tool names.
```

2024-08-20 23:38 UTC, aieri commented on src/service.py
> +        if not self.is_redfish_available_and_enabled:
right, I could have been clearer. But the latest iteration does exactly what I was suggesting.

2024-08-20 23:46 UTC, aieri requested changes

2024-08-20 23:46 UTC, aieri commented on src/service.py
> +    def redfish_conn_params_valid(self) -> bool:
ah yes that's true, it is a quality of life kind of feature. But I agree with James, we could move it to a separate file at some point

2024-08-20 23:46 UTC, aieri commented on src/service.py
> +            return True
yeah no I think this check should be on the caller side: validate parameters if redfish is enabled

2024-08-21 19:40 UTC, zxhdaze approved these changes

2024-08-21 20:59 UTC, merged