Update resources for ARM
canonical/hardware-observer-operator pull request #295
Opened 2024-08-28 15:35 UTC by zxhdaze

Update docs for ARM resources:
`perccli` and `sas2ircu` are not available for arm. We simply explain these resources are only available to AMD64 servers.
`storcli` and `sas3ircu` support arm, updated the docs with relevant path.

2024-08-28 16:38 UTC, aieri requested changes

2024-08-28 21:44 UTC, gabrielcocenza reviewed
non-blocker comment:
The changes itself looks ok, but I'm not sure if this should be merged first because it feels to me that we are already have some kind of support for amr64, but in reality we are not building or running tests for this architecture. Shouldn't this change come after the automation tool start having the CI for arm64?

2024-08-29 23:00 UTC, aieri commented
yeah good point. This PR should be kept pending until we have arm64 builds.

2024-08-31 01:03 UTC, aieri requested changes
checksum validation must also be updated for the additional arm64 tools

2024-09-02 01:31 UTC, samuelallan72 commented
> Why do we store checksums of zip files if we ask users to add the binaries directly?

My guess is that we can't ship the binaries with the charm for legal reasons, but we can verify that the users provided the correct files.

2024-09-02 08:34 UTC, chanchiwai-ray commented
> And btw, I don't quite understand how src/checksum.py works. Why do we store checksums of zip files if we ask users to add the binaries directly?

This is designed as a security feature: prevent operator download something malicious without knowing

2024-09-03 02:12 UTC, aieri commented
> > And btw, I don't quite understand how src/checksum.py works. Why do we store checksums of zip files if we ask users to add the binaries directly?
> 
> This was designed as a security feature: prevent operator download something malicious without knowing

Yes, that's true, but my question was - for example - why we store the [checksum of `SAS3IRCU_P16.zip`](https://github.com/canonical/hardware-observer-operator/blob/377ea9dd9d378fd9cff39f2249507929639258e6/src/checksum.py#L170), when the user is expected to upload the [`sas3ircu` binary](https://github.com/canonical/hardware-observer-operator/blob/377ea9dd9d378fd9cff39f2249507929639258e6/metadata.yaml#L55) contained in that archive.

Anyway, I think checksum updates should be handled in a separate PR, this one is fine as is provide it isn't merged until arm64 support is actually available.

2024-09-05 05:49 UTC, chanchiwai-ray approved these changes

2024-09-05 07:14 UTC, chanchiwai-ray requested changes
I think it's better to update the description to link to `src/checksum.py` since the information in here is out-of-dated. For example, using the version mentioned in `src/checksum.py` "MR 7.27", that deb package support all arches: "storcli_007.2705.0000.0000_all.deb"

2024-09-05 07:17 UTC, chanchiwai-ray commented on metadata.yaml
> +      On AMD64 hosts, use ./Unified_storcli_all_os/Ubuntu/storcli_007.2612.0000.0000_all.deb
it says `_all` in `./Unified_storcli_all_os/Ubuntu/storcli_007.2612.0000.0000_all.deb`

2024-09-05 07:59 UTC, chanchiwai-ray commented
added checksum in here: https://github.com/canonical/hardware-observer-operator/pull/303

2024-09-05 14:19 UTC, chanchiwai-ray commented
> I think it's better to update the description to link to src/checksum.py since the information in here is out-of-dated. For example, using the version mentioned in src/checksum.py "MR 7.27", that deb package support all arches: "storcli_007.2705.0000.0000_all.deb"

Sorry, I was expecting`*_all` is working for all arch, but it's not true. Ignore my comment above

2024-09-13 02:18 UTC, chanchiwai-ray commented
superseded by https://github.com/canonical/hardware-observer-operator/pull/308

2024-09-13 02:18 UTC, closed without merging