Add multi arch support for smartctl
canonical/hardware-observer-operator pull request #296
Opened 2024-08-28 21:39 UTC by zxhdaze

2024-09-02 01:23 UTC, samuelallan72 requested changes
Thanks, looks good to me.  I left a comment about improving the test. :)

2024-09-02 01:23 UTC, samuelallan72 commented on tests/unit/test_hw_tools.py
> +        assert False, "ValueError not raised"
Pytest has a [mechanism for testing this pattern](https://docs.pytest.org/en/stable/reference/reference.html#pytest-raises):

```suggestion
    with pytest.raises(ValueError, match="Unsupported architecture: unsupported_arch"):
        get_release_url(base_url, releases)
```

:)

2024-09-02 13:57 UTC, gabrielcocenza requested changes

2024-09-02 13:57 UTC, gabrielcocenza commented on src/hw_tools.py
> +        "arm64": "smartctl_exporter-0.12.0.linux-arm64.tar.gz",
It seems that plataform lib uses the `uname` command to get the architecture and there is no `arm64` as output.
Sources: [0](https://stackoverflow.com/questions/45125516/possible-values-for-uname-m) and [1](https://wiki.debian.org/ArchitectureSpecificsMemo?action=recall&rev=219#fndef-28921cada1db0fe0680e9e948d3015a95dafcfbd-21), so I think this should be changed to `aarch64`

2024-09-02 13:57 UTC, gabrielcocenza commented on tests/unit/test_hw_tools.py
> +def test_get_release_url(mock_machine):
Please also add a unit test with the happy path

2024-09-05 09:20 UTC, chanchiwai-ray commented
we can directly jump to smartctl snap, since it's not that difficult to implement

2024-10-03 03:50 UTC, chanchiwai-ray commented
This has been superseded by https://github.com/canonical/hardware-observer-operator/pull/327 (By the way, thanks for the efforts @zxhdaze)

2024-10-03 03:50 UTC, closed without merging