Add checksum for `aarch64` resources
canonical/hardware-observer-operator pull request #303
Opened 2024-09-05 07:57 UTC by chanchiwai-ray

Add checksum for `storcli` and `sas3ircu` since only these two has arm64 release for their binary.

2024-09-05 11:50 UTC, Pjack submitted a review, later dismissed
LGTM

2024-09-05 12:59 UTC, gabrielcocenza requested changes

2024-09-05 12:59 UTC, gabrielcocenza commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
I've investigated and I think this current structure is not ready for this.

This `sha256_checksum` is for the `storcli_007.2705.0000.0000_all.deb` file which is amd64. For arm64 the file is `storcli64_007.2705.0000.0000_arm64.deb` which the checksum is `9c36caacb6b7f956a9f5bcdb3f37d24e4aa8263ce01243b251092a39e5e32e35`.

It's necessary to re-think the data structure here

2024-09-05 14:20 UTC, chanchiwai-ray commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
thanks, I found out that `_all` does not mean all architectures: https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#deb-format

2024-09-05 14:23 UTC, chanchiwai-ray commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
```
dpkg --info ./storcli_007.2705.0000.0000_all.deb
 new Debian package, version 2.0.
 size 2062694 bytes: control archive=474 bytes.
     354 bytes,    16 lines   *  control
      54 bytes,     2 lines   *  postinst             #!/bin/sh
      75 bytes,     4 lines   *  preinst              #!/bin/sh
 Package: storcli
 Version: 007.2705.0000.0000
 Section: storcli
 Priority: optional
 Architecture: all
 Essential: no
 Depends: bash
 Pre-Depends:
 Recommends:
 Suggests:
 Installed-Size: 7000000
 Maintainer: OS-Utils  <bangalore-mr-osutils.pdl@broadcom.com>
 Conflicts:
 Replaces:
 Provides:
 Description: Storage Command Line Tool, manages storage controllers.
```

2024-09-05 14:33 UTC, gabrielcocenza commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
Interesting....
Yeah I guess it shouldn't be an issue if the user pass this file that is for all archs, but at the same time it's weird if we deny if it pass a valid arm64 package

```
dpkg --info ./storcli64_007.2705.0000.0000_arm64.deb
 new Debian package, version 2.0.
 size 1667656 bytes: control archive=460 bytes.
     340 bytes,    16 lines   *  control              
      53 bytes,     2 lines   *  postinst             #!/bin/sh
      76 bytes,     4 lines   *  preinst              #!/bin/sh
 Package: storcli64
 Version: 007.2705.0000.0000
 Section: storcli64
 Priority: optional
 Architecture: arm64
 Essential: no
 Depends: bash
 Pre-Depends: 
 Recommends: 
 Suggests: 
 Installed-Size: 7000000
 Maintainer:Broadcom<support@broadcom.com>
 Conflicts: 
 Replaces: 
 Provides: 
 Description: Storage Command Line Tool, manages storage controllers.
```
I guess we need some documentation or accept both

2024-09-05 14:38 UTC, gabrielcocenza commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
> thanks, I found out that _all does not mean all architectures: 

What does it mean? I didn't understand from the link you have passed
From the output it does seems that works for all architectures

2024-09-05 22:53 UTC, aieri commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
I think it's fine if we let the operator _minimally_ shoot themselves in the foot (meaning: uploading an amd64 binary on an arm machine and vice-versa), but we definitely should accept the upload of `storcli64_007.2705.0000.0000_arm64.deb`

2024-09-06 01:20 UTC, chanchiwai-ray commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
the one it mentioned `*_all` does not work on arm64 machine

2024-09-06 08:25 UTC, chanchiwai-ray commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
> I think it's fine if we let the operator minimally shoot themselves in the foot (meaning: uploading an amd64 binary on an arm machine and vice-versa), but we definitely should accept the upload of storcli64_007.2705.0000.0000_arm64.deb

it will not pass the "validate_checksum", that function actually validate the arch as well. So if ` storcli64_007.2705.0000.0000_arm64.deb` only support amd64, the checksum will not be included. So they can't shoot themselves in the foot

2024-09-06 13:07 UTC, gabrielcocenza submitted a review, later dismissed

2024-09-06 13:07 UTC, gabrielcocenza commented on src/checksum.py
> +        desc="MR 7.27 all",
We know now that this doesn't work for all archs, so I think we can change from `all` to `amd64` to be more precise.

2024-09-06 21:46 UTC, aieri submitted a review, later dismissed
lgtm, but I also agree that the descriptions shouldn't contain 'all' (frankly I think those debs are incorrectly packaged, they definitely contain arch-specific code)

2024-09-06 21:46 UTC, aieri commented on src/checksum.py
> +        desc="MR 7.27 all",
I agree

2024-09-09 02:29 UTC, chanchiwai-ray commented on src/checksum.py
> +        desc="MR 7.27 all",
I think we will need to add some property like `filename` or something. I added `all` is because the filename contains `*_all`. There are some other filename that might contain `*_amd64`, and that might cause people to pick the wrong one (e.g. they choose the `*_amd64`) and checksum will fail

2024-09-09 12:45 UTC, gabrielcocenza commented on src/checksum.py
>          sha256_checksum="45ff0d3c7fc8b77f64de7de7b3698307971546a6be00982934a19ee44f5d91bb",
From my side we can close this thread :+1:

2024-09-09 12:52 UTC, gabrielcocenza approved these changes

2024-09-13 02:11 UTC, jneo8 approved these changes

2024-09-13 02:16 UTC, merged