Add Snap Strategy
canonical/hardware-observer-operator pull request #306
Opened 2024-09-06 20:14 UTC by gabrielcocenza

DCGM and smartctl- will be installed via snap. This PR creates the SnapStrategy so we can install, remove and check as it happens with other stratigies in the code base.

2024-09-09 01:50 UTC, samuelallan72 requested changes

2024-09-09 01:50 UTC, samuelallan72 commented on src/hw_tools.py
> +        snap.remove([self.snap_name])
Since we're following this strategy pattern, I find it odd that the stategy base class doesn't contain these public install and remove methods, and that the signature of these methods then changes for each implementation.  It might be helpful to move more logic into the stategy classes, so the calling code doesn't need to know the implementation.

Ie. so we can remove all the `if isinstance(strategy, XYZ)...` checks.

2024-09-09 01:58 UTC, samuelallan72 requested changes
Also, I'm not sure how helpful it is to add this before adding any actual snaps, because this code doesn't have any real use yet, can't be functionally tested, and we don't have any client code that uses it (ie. we don't know yet if this api will be what we want).

It's tricky with figuring out when to write things and in what order, and I think I've gone back and forth over it.  For this, my opinion is that this is a new feature where we should add support for an actual snap, not just developing an api in a vaccuum. :)

2024-09-09 15:00 UTC, gabrielcocenza commented
@samuelallan72 

The DCGM and Smartctl snaps are not ready yet. This PR can be pending until those snaps are available. The idea here is just start having conversations about the approach and not wait until is ready for trying to figure out what to do.

2024-09-10 22:46 UTC, samuelallan72 commented on src/hw_tools.py
> +        snap.remove([self.snap_name])
If this PR is about exploring changes to facilicate supporting exporters installed from the snap - as @gabrielcocenza noted:

> The idea here is just start having conversations about the approach and not wait until is ready for trying to figure out what to do.

Then considering refactoring the strategies is definitely within scope. :)

2024-09-11 03:04 UTC, jneo8 requested changes

2024-09-11 03:04 UTC, jneo8 commented on src/hw_tools.py
> +    def install(self, channel: str = "latest/stable") -> None:
I guess the channel is part of the configuration we get from the charm configuration? 
Actually we need to know how to get the channel information when execute the *install* function. This PR need to include the changing of `HWToolHelpe`?

@gabrielcocenza Can you add more information about this?

2024-09-11 20:49 UTC, gabrielcocenza commented on src/hw_tools.py
> +        snap.remove([self.snap_name])
I agree that some refactoring might be good, but I think we should target it into a different PR later.

Calling `strategy.install()` and not checking instances type for strategies makes sense to me

2024-09-11 21:32 UTC, gabrielcocenza commented on src/hw_tools.py
> +    def __init__(self, tool: HWTool):
How will we pass the channel to install from?

2024-09-11 21:41 UTC, gabrielcocenza commented on src/service.py
> +
I believe that for snaps services the "render_config" for the congif_change will be refresh the charm to update the channel, set the port in the snap config and restart the service.

Will do that after https://github.com/canonical/dcgm-snap/pull/4 is done

2024-09-11 21:41 UTC, gabrielcocenza commented on src/service.py
> +            if self.settings.service_template
Instead of those `if` checks we could split into two different Exporters type:
1. Those that have config to render as template
2. Those that don't have config to render. E.g: snaps

2024-09-11 23:32 UTC, aieri requested changes

2024-09-11 23:32 UTC, aieri commented on src/service.py
> +            if self.settings.service_template
I think we should move toward dropping service_template altogether: it's currently only used by smartctl_exporter and hardware_exporter, and we're snapping smartctl_exporter. If we snap hardware_exporter we can drop a bunch of code from here.

2024-09-11 23:32 UTC, aieri commented on src/service.py
> +            return True
comment: I don't think it's a good idea to overload the meaning of True and False to represent success or failure but I see this is an established pattern in this codebase

2024-09-11 23:32 UTC, aieri commented on src/service.py
> +        )
why do we need this conditional? the hardware exporter settings do contain a config_template attribute

2024-09-11 23:32 UTC, aieri commented on src/service.py
> +            else ""
same here

2024-09-11 23:38 UTC, samuelallan72 commented on src/hw_tools.py
> +        snap.remove([self.snap_name])
Ok no worries :+1:

2024-09-12 06:26 UTC, samuelallan72 commented on config.yaml
> +      it will start at port 9400.
For consistency with other exporters this charm ships, could we default to 10202?

2024-09-12 06:26 UTC, samuelallan72 commented on src/config.py
> +    service_path: Path = Path(f"/etc/systemd/system/{name}.service")
Is there a reason we're working with the underlying systemd service here instead of using the snap service directly?

2024-09-12 06:26 UTC, samuelallan72 commented on src/service.py
> +            return True
maybe out of scope for this PR: either way it would be good to document the semantics of the return type, both for this and `.render_service()`.

2024-09-12 06:26 UTC, samuelallan72 commented on tests/unit/test_charm.py
> +    def test_exporters(
I think this test is too overloaded - this test contains several conditionals and is hard to read.  It might be better to split it into three tests and drop the parameterized decorator. It's worth the small amount of extra duplication to make the tests clearer and more declarative.

2024-09-13 02:29 UTC, jneo8 commented on src/hw_tools.py
> +    def __init__(self, tool: HWTool):
I prefer to hardcode the HWTool in the class. But both are working.

2024-09-13 02:29 UTC, jneo8 commented on src/hw_tools.py
> +    def install(self, channel: str = "latest/stable") -> None:
Thanks, it's good for me.

2024-09-13 02:35 UTC, Pjack commented
@gabrielcocenza  Would you mind separating this PR into two parts? The first part is common to both the smartctl-exporter-snap and dcgm-exporter-snap, so it would be more convenient to work on them in parallel if we decouple the first and second parts. Thanks!
1. SnapStrategy
2. Integrate dcgm exporter snap 

I propose to merge SnapStrategy first.

2024-09-17 00:31 UTC, samuelallan72 requested changes

2024-09-17 00:31 UTC, samuelallan72 commented on src/hw_tools.py
> +    def install(self, channel: str = "latest/stable") -> None:
Maybe something was lost in the splitting of PRs, but this method still takes `channel` as an argument, and doesn't use `self.channel`.

2024-09-17 00:31 UTC, samuelallan72 commented on src/hw_tools.py
> +
I reckon this could be a private method (it's not used outside the strategy), or even better inlined because it's a single line method.

2024-09-17 00:31 UTC, samuelallan72 commented on src/hw_tools.py
> +            snap.add(self.snap_name, channel=channel)
```suggestion
            snap.add(self.snap_name, channel=self.channel)
```

2024-09-17 00:31 UTC, samuelallan72 commented on src/hw_tools.py
> +            )
This logs an error to the charm log, but that's silent to the user - can we bubble this error up to the charm status?  How do the other exporters handle installation failures?

2024-09-17 00:31 UTC, samuelallan72 commented on src/hw_tools.py
> +    def install(self, channel: str = "latest/stable") -> None:
```suggestion
    def install(self) -> None:
```

2024-09-17 01:44 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    def install(self, channel: str = "latest/stable") -> None:
don't you need `def install(self, channel)` but not `def __init__(self, channel)`? if you are following the current design? https://github.com/canonical/hardware-observer-operator/blob/main/src/hw_tools.py#L182

2024-09-17 01:47 UTC, chanchiwai-ray commented on src/hw_tools.py
> +                elif isinstance(strategy, (APTStrategyABC, SnapStrategy)):
How do you change snap channel, if you are running `strategy.install` without arg?

2024-09-17 01:52 UTC, samuelallan72 commented on src/hw_tools.py
> +                elif isinstance(strategy, (APTStrategyABC, SnapStrategy)):
I think the original idea was to set the channel when the class is init'd, but it may have been lost during the reverts.

2024-09-18 04:36 UTC, jneo8 requested changes

2024-09-18 04:36 UTC, jneo8 commented on src/hw_tools.py
> +class SnapStrategy(StrategyABC):
**suggestion:** 

I kind of prefer code like this:

- No init function
- hard code HWTool
- Pass channel on `install` function

```python
class SnapStrategyABC(StrategyABC, metaclass=ABCMeta):
    """Snap strategy class."""

    def install(self, channel: str = "latest/stable") -> None:
        """Install the snap from a channel."""
        
class SmartCtlStrategy(SnapStrategyABC):
    _name = HWTool.SMARTCTL_EXPORTER
                     
class HWToolHelper:
    """Helper to install vendor's or hardware related tools."""

   def strategies(self) -> List[StrategyABC]:
        """Define strategies for every tools."""
        return [
            StorCLIStrategy(),
            RedFishStrategy(),
            ...
            # It's more easy to define strategy here
            SmartCtlStrategy(),
        ]
    # The channel information should only be given here. This make sure the object dependency is one-way.
    def install(self, resources: Resources, channel: (some-type), hw_available: Set[HWTool]) -> Tuple[bool, str]:
        """Install tools."""
        
        ...
           
        for strategy in self.strategies:
            if strategy.name not in hw_available:
                continue
            try:
                if isinstance(strategy, TPRStrategyABC):
                    path = fetch_tools.get(strategy.name)  # pylint: disable=W0212
                    if path:
                        strategy.install(path)
                if isinstance(strategy, SnapStrategy):
                    # The channel should be an argument for install function
                    strategy.install(channel)
                elif isinstance(strategy, APTStrategyABC):
                    strategy.install()  # pylint: disable=E1120
                logger.info("Strategy %s install success", strategy)
            except (
                ResourceFileSizeZeroError,
                OSError,
                apt.PackageError,
                ResourceChecksumError,
                snap.SnapError,
            ) as e:
                logger.warning("Strategy %s install fail: %s", strategy, e)
                fail_strategies.append(strategy.name)

        if fail_strategies:
            return False, f"Fail strategies: {fail_strategies}"
        return True, ""
```

So the (dis)advantage are:

- The strategy can keep in hard code, it's more easy to trace and keep the flexibility. (Imagine if you have different operation for DCGM & Smart).
- ~~Chance to use snap resource in the future~~
- The only breaking change only happen on `HWToolHelper.install` function. Other design won't be broken.

2024-09-18 14:50 UTC, gabrielcocenza commented on src/hw_tools.py
> +                elif isinstance(strategy, (APTStrategyABC, SnapStrategy)):
> How do you change snap channel, if you are running strategy.install without arg?

I think this will need to happen at the exporter level on what today is  `render_config`. There we'll refresh the snap to use the proper channel and the strategy will be declared something like: `SnapStrategy(HWTool.DCGM, self.config["dcgm-snap-channel"])`

2024-09-18 15:50 UTC, gabrielcocenza commented on src/hw_tools.py
> +            )
Forgot to re-raise the error. Thanks

2024-09-18 19:35 UTC, aieri requested changes
looks good, but the snap strategy should be aligned with the other strategies in terms of configuration being done by the client when calling `install` and not in the constructor (for consistency)

2024-09-18 19:35 UTC, aieri commented on src/hw_tools.py
> +class SnapStrategy(StrategyABC):
while I agree that we should remove the constructor for consistency with the other strategies, I don't quite get why it would be preferable to move complexity to the install function, as that requires the caller to have deeper knowledge about how each strategy works and adds extra conditionals to `HWToolHelper.install`

2024-09-19 00:02 UTC, gabrielcocenza commented
> while I agree that we should remove the constructor for consistency with the other strategies, I don't quite get why it would be preferable to move complexity to the install function, as that requires the caller to have deeper knowledge about how each strategy works and adds extra conditionals to HWToolHelper.install

I agree....

@aieri @jneo8 @samuelallan72  After putting more effort on how to integrate the dcgm snap I ended up noticing that we might not need to have a SnapStrategy for exporters that are snaped.

When we have debian packages or other binaries the Strategy is installing and removing the packages while the exporter on the `service` module is responsible to render the systemd configs and check the health of the daemons.

When we have a snap I'm not seeing the need to have this kind of separation and it's seems to me that it's simpler just handle everything as a service and we'll be able to do pretty much everything in just one module.

Please take a look at the draft PR that I've created at https://github.com/canonical/hardware-observer-operator/pull/319

Unfortunately this PR is showing to be hard to have the Generic snap class without a real implementation. In any case, I think this other PR has a cleaner approach

2024-09-19 07:55 UTC, jneo8 commented on src/hw_tools.py
> +class SnapStrategy(StrategyABC):
> Different snaps will have different channels to install from. I don't see how passing a single channel on ...

It's a pseudocode code, so pass the configuration you want.

2024-09-19 22:26 UTC, gabrielcocenza commented
Closing this PR. The approach changed to not have a SnapStrategy and work directly with the exporter class itself. The new PR is at #319

2024-09-19 22:26 UTC, closed without merging