Update resource documentation to point to the source of truth.
canonical/hardware-observer-operator pull request #308
Opened 2024-09-11 02:21 UTC by chanchiwai-ray

Currently, the resource documentation is not pointing to the source of truth: i.e. the `checksum.py` file. This PR updates the description of each resource to point to `checksum.py`

2024-09-11 02:23 UTC, chanchiwai-ray commented
I think the resource's description should be pointing to more user-friendly pages, e.g. in charmhub https://charmhub.io/hardware-observer/docs/monitor-hw-raid-controller. And we should update the charmhub page with a list of supported resources that are automatically generated from the `checksum.py`. What do you think?

2024-09-11 02:24 UTC, chanchiwai-ray commented on metadata.yaml
> +      https://github.com/canonical/hardware-observer-operator/blob/main/src/checksum.py.
To be discussed

2024-09-11 02:36 UTC, jneo8 submitted a review, later dismissed

2024-09-11 02:39 UTC, samuelallan72 commented
> I think the resource's description should be pointing to more user-friendly pages, e.g. in charmhub https://charmhub.io/hardware-observer/docs/monitor-hw-raid-controller. And we should update the charmhub page with a list of supported resources that are automatically generated from the checksum.py

Agreed, this sounds like a good method. :+1:

2024-09-11 02:40 UTC, chanchiwai-ray commented on metadata.yaml
> +      https://github.com/canonical/hardware-observer-operator/blob/main/src/checksum.py.
We could alternatively point this to charmhub page, and make the page great

2024-09-11 03:08 UTC, aieri requested changes
While more accurate, to me this seems to be a step back from a usability perspective.
As a user, I probably care more about how to use the software than to know how it works internally, and the current descriptions are very good at concisely telling me what to do to make things work. I am definitely not against documenting which versions we accept, but I don't think it should come at the expense of very a practical "go here, do this, etc".

Additionally, 99% of the time a user probably wants to be able to sideload the latest version of these resources (and the charm not to break if they don't push a newer one when available); I would expect "I want to know if a specific version from 3 years ago" to be an exceedingly rare use case. From this point of view a list of accepted versions and checksums brings little value (and less than adding checksums for newer revisions).

2024-09-11 04:25 UTC, chanchiwai-ray commented
Since `juju charm-resources hardware-observer --format yaml` can print the resource description as-it-is (better looking than the one in charmbub resource page), we can preserve the description here

2024-09-11 19:50 UTC, aieri approved these changes

2024-09-11 23:30 UTC, samuelallan72 approved these changes

2024-09-12 01:30 UTC, chanchiwai-ray commented
Will need to wait until https://github.com/canonical/hardware-observer-operator/pull/303 is merged

2024-09-13 02:16 UTC, merged