[WIP] ci: POC arm64 runner
canonical/hardware-observer-operator pull request #312
Opened 2024-09-13 03:52 UTC by jneo8

2024-09-16 07:56 UTC, jneo8 commented
I can't make grafana-agent works on arm64 machine, [issue open](https://github.com/canonical/grafana-agent-operator/issues/184)

2024-09-20 06:56 UTC, chanchiwai-ray commented on tests/functional/bundle.yaml.j2
> +    series: {{ series }}
You have globally define `series`, do you still need it? And why pin the revision?

2024-09-20 07:02 UTC, samuelallan72 requested changes
I know the constraints for grafana-agent across architectures in the bundle is still being worked on, but I left some comments on other areas in the PR.  Thanks :)

2024-09-20 07:02 UTC, samuelallan72 commented on .github/workflows/check.yaml
> +      #   - unit
Reminder to uncomment the checks above before merging :)

2024-09-20 07:52 UTC, chanchiwai-ray commented on tests/functional/test_charm.py
> +        arch=architecture,
Once you have model constraint, may be this is not necessary

2024-09-20 08:07 UTC, jneo8 commented on tests/functional/test_charm.py
> +        arch=architecture,
Removed

2024-09-20 08:07 UTC, jneo8 commented on tests/functional/conftest.py
> +    return "amd64"
Updated

2024-09-20 08:10 UTC, chanchiwai-ray submitted a review, later dismissed

2024-09-20 08:37 UTC, samuelallan72 requested changes

2024-09-20 08:37 UTC, samuelallan72 commented on charmcraft.yaml
> +      architectures: ["amd64", "arm64"]
Sorry I missed this earlier - the bases need to be split (we shouldn't run a charm built on a different architecture).  See https://github.com/canonical/charm-prometheus-libvirt-exporter/pull/37/files#diff-8af267359854d30b091fde763088e458bf27c8fedc056895f3104ef05b61f4b5 for example

2024-09-20 08:41 UTC, jneo8 commented on charmcraft.yaml
> +      architectures: ["amd64", "arm64"]
Updated

2024-09-20 08:41 UTC, samuelallan72 approved these changes
Thanks, looks good to me :D

2024-09-20 08:53 UTC, chanchiwai-ray approved these changes

2024-09-20 09:00 UTC, merged