Fix integration tests (make -> tox)
canonical/hardware-observer-operator pull request #321
Opened 2024-09-23 00:28 UTC by samuelallan72

The Makefile was removed, so we must use tox directly here now.

2024-09-23 01:09 UTC, Pjack approved these changes

2024-09-23 01:51 UTC, chanchiwai-ray approved these changes

2024-09-23 01:53 UTC, samuelallan72 commented
Manually running the tests: https://github.com/canonical/hardware-observer-operator/actions/runs/10986372682  It seems these tests are not auto run for PRs.

2024-09-23 08:06 UTC, chanchiwai-ray requested changes
It's still failing. Maybe you need to bump the controller version

2024-09-25 13:07 UTC, gabrielcocenza submitted a review, later dismissed

2024-09-26 01:49 UTC, chanchiwai-ray approved these changes
LGTM

2024-09-26 01:49 UTC, chanchiwai-ray commented on .github/workflows/cos_integration.yaml
> +  pull_request:
I am not sure if we intentionally missing this, @Pjack can you confirm

2024-09-26 01:55 UTC, Pjack commented on .github/workflows/cos_integration.yaml
> +  pull_request:
Initially, the idea was to run integration tests before releasing a new version to the stable branch. 
This may take more time and potentially slow down our development cycle. 
I don't know what's exactly status now. Do we need to run the test over 1 hour?

2024-09-26 01:58 UTC, samuelallan72 commented on .github/workflows/cos_integration.yaml
> +  pull_request:
> I don't know what's exactly status now. Do we need to run the test over 1 hour?

This time it succeeded in 27 minutes, which isn't too bad.  I'm happy with that for CI - the longest func tests here took 17 minutes, so it's not that much longer to wait.

2024-09-26 05:57 UTC, chanchiwai-ray commented on .github/workflows/cos_integration.yaml
> +  pull_request:
Feel free to resolve when a conclusion is made

2024-09-26 05:58 UTC, samuelallan72 commented on .github/workflows/cos_integration.yaml
> +  pull_request:
@Pjack are you ok with running this in CI for PRs?

2024-09-27 02:33 UTC, Pjack approved these changes

2024-09-27 02:34 UTC, merged