Add a custom metrics CSV for the dcgm snap
canonical/hardware-observer-operator pull request #325
Opened 2024-09-24 19:48 UTC by Deezzir

Provides a custom metrics CSV file for the `dcgm` snap. The file can be provided through the `dcgm-exporter-metrics-file` configuration. The [default metrics from the upstream](https://github.com/NVIDIA/dcgm-exporter/blob/main/etc/default-counters.csv) are not comprehensive, and we added other ones that can be helpful to monitor in production.

The more information on the config can be found [here](https://snapcraft.io/dcgm).

2024-09-25 13:06 UTC, gabrielcocenza requested changes

2024-09-25 13:06 UTC, gabrielcocenza commented on src/service.py
> +        gpu_metrics_file: Path = Path("./src/gpu_metrics/dcgm_metrics.csv")
This path is very likely to not work once the charm is build and running.

Please add the charm_dir on the DCGM exporter as it happens with other exporters. See the example:

https://github.com/canonical/hardware-observer-operator/blob/0f62edce1ea3b20fdcf9a3669fc59c839df78b6b/src/charm.py#L83-L84

From the charm_dir than you can access the template. E.g:

https://github.com/canonical/hardware-observer-operator/blob/0f62edce1ea3b20fdcf9a3669fc59c839df78b6b/src/service.py#L101

2024-09-25 20:56 UTC, aieri commented on src/service.py
> +                shutil.copy(self.metrics_file, self.metrics_location)
is there any issue in doing this unconditionally?

2024-09-25 22:09 UTC, gabrielcocenza requested changes

2024-09-25 22:09 UTC, gabrielcocenza commented on src/service.py
> +    metrics_location: Path = Path("/var/snap/dcgm/common/")
we can have a single variable for this:
```suggestion
    metrics_location: Path = Path("/var/snap/dcgm/common/dcgm-exporter-metrics-file")
```
If you need just the directory you can call `metrics_location.parent`

2024-09-25 22:09 UTC, gabrielcocenza commented on src/service.py
> +        if self.snap_client.get(self.metric_config) != self.metric_config_value:
I think adding some logs would be nice here...

If I understand this correctly, this would be the same as:
```suggestion
        if metrics_location.exists():
            logger.debug("metric file %s for DCGM already exists", metrics_location.name)
            return True
        
       logger.info("creating the custom metric file for DCGM")
       # continue the code of copying the file
```

See my comment to have a single variable for `metrics_location`

2024-09-25 22:09 UTC, gabrielcocenza commented on src/service.py
> +                logger.error("Failed to copy the metrics file: %s", err)
We don't realy know what failed here so let's be generic
```suggestion
                logger.error("Failed to configure custom DCGM metrics")
```

2024-09-25 22:21 UTC, Deezzir commented on src/service.py
> +    metrics_location: Path = Path("/var/snap/dcgm/common/")
Its the name of the snap configuration, not the metrics file

2024-09-25 22:30 UTC, Deezzir commented on tests/unit/test_service.py
> +        self.assertEqual(self.exporter.exporter_name, "dcgm")
I will stay with the unittest, so there are no inconsistencies.

2024-09-25 22:40 UTC, Deezzir commented on src/service.py
> +        if self.snap_client.get(self.metric_config) != self.metric_config_value:
The main part of that code block is to check whether the snap config is set. If not, we can copy it, ignoring whether it's there; it's a safe operation.

2024-09-26 10:21 UTC, chanchiwai-ray commented on src/service.py
> +                shutil.copy(self.metrics_file, self.metrics_location)
(non-blocking) would it be more useful to add this to the snap? e.g. `snap set xxx=/home/ubuntu/xxx.csv` then the snap copy this file to the desired location.

2024-09-26 13:03 UTC, gabrielcocenza commented on src/service.py
> +        if self.snap_client.get(self.metric_config) != self.metric_config_value:
My concern here is that if we change the metrics (remove or add new ones), the charm upgrade won't update the metrics because the snap is already configured.

I think we should check if the snap config is empty or equal to `dcgm_metrics.csv` and overwrite. If is different we skip this step so the user still have a workaround of setting a custom metric file as they wish

2024-09-26 17:06 UTC, Deezzir commented on src/service.py
> +                shutil.copy(self.metrics_file, self.metrics_location)
As discussed, I will remove the condition and do the metric configuration every time the function is called to limit mutability

2024-09-26 18:20 UTC, gabrielcocenza commented on src/gpu_metrics/dcgm_metrics.csv
> +# Selected metrics for dcgm-exporter
@Deezzir please add this header into the file

2024-09-26 18:50 UTC, Deezzir commented on src/gpu_metrics/dcgm_metrics.csv
> +# Selected metrics for dcgm-exporter
Would you like me to move the file to the templates? I still think that the location its in rn is better

2024-09-26 19:25 UTC, gabrielcocenza commented on src/gpu_metrics/dcgm_metrics.csv
> +# Selected metrics for dcgm-exporter
I'm ok with the place. I just want to add the comment that I gave in the first comment saying that the file is juju controlled

2024-09-26 19:36 UTC, Deezzir commented on src/gpu_metrics/dcgm_metrics.csv
> +# Selected metrics for dcgm-exporter
Done

2024-09-26 21:03 UTC, aieri submitted a review, later dismissed

2024-09-26 21:09 UTC, gabrielcocenza approved these changes

2024-09-26 21:15 UTC, Deezzir commented on src/service.py
> +                shutil.copy(self.metrics_file, self.metrics_location)
Yes, we would need another plug for that. As the snap is confined, it can't copy or touch files outside some predefined locations.  For example, `$SNAP_COMMON` at `/var/snap/dcgm/common`.  The user needs to put the file there first so that Snap can manage it.

2024-09-27 00:13 UTC, samuelallan72 requested changes

2024-09-27 00:13 UTC, samuelallan72 commented on tests/unit/test_service.py
> +        self.mock_shutil.copy.accept_not_called()
```suggestion
        self.exporter.strategy.install.assert_called()
        self.mock_shutil.copy.assert_not_called()
```

It looks like these have been widely used typos in this codebase.  Called typoed methods here don't fail because they're mocks.

Please update accept_called and accept_not_called to assert_called and assert_not_called in all the code you've added here - it's out of scope for the rest of the codebase in this PR.

A hint for testing tests is do something to purposefully make the test fail, run the test, and verify it fails (eg. for here it could be commenting out the strategy.install() call and checking this test fails, or inverting the condition in the test and checking it fails).

2024-09-27 00:13 UTC, samuelallan72 commented on src/service.py
> +            self.snap_client.restart(reload=True)
Some of this (especially the logger call) can be outside the try block.  Also can we check for a narrower set of exceptions? I'm a bit uneasy about so much code running inside a broad try/except, especially since the error is mostly squashed.

2024-09-27 00:16 UTC, samuelallan72 commented on tests/unit/test_service.py
> +        self.mock_shutil.copy.accept_not_called()
Opened a bug report for fixing the other cases https://github.com/canonical/hardware-observer-operator/issues/329

2024-09-27 00:57 UTC, Deezzir commented on tests/unit/test_service.py
> +        self.mock_shutil.copy.accept_not_called()
Thanks for pointing that out!

2024-09-27 01:14 UTC, Deezzir commented on src/service.py
> +            self.snap_client.restart(reload=True)
It doesn't make much difference; the three statements(logging excluded) seem like one logic unit for setting the custom metrics config. I agree that squashing to a general exception does not feel right, but in that case, it's okay as long as we're reporting the error. 

I prefer different exceptions for each case if we need some additional logic to handle them, but there is not much we can do in this case. 

The only case where this would arise is if something is wrong with the copy. `FileNotFound` is highly unlikely as the file comes with the charm. `PermissionError` is also a low possibility as the charm operates with privileged perms. Also, `restart` may fail, but only if the installation goes wrong, which should be handled by `super.install()` and the `if` check.

The only advantage will be case-specific logging, but I will report the message in a generic log—the downside is a unit test for each case. So I am not sure.

What do you think?

2024-09-27 01:16 UTC, samuelallan72 commented on src/service.py
> +            self.snap_client.restart(reload=True)
No worries, it sounds fine to keep those three lines inside the try block then. :+1:  I think we're thinking about refactoring some of the logic from returning booleans to just raising errors on failure, so this may be refactored out soon anyway. :)

2024-09-27 01:18 UTC, Deezzir commented on src/service.py
> +            self.snap_client.restart(reload=True)
Also, regarding the set function, I saw in #327 that there will be a separate function for setting configs, which handles the errors.

2024-09-30 12:31 UTC, gabrielcocenza commented on src/gpu_metrics/dcgm_metrics.csv
> +# DCGM_FI_DEV_VGPU_INSTANCE_IDS, counter, Count of vGPU Instances
From the issue it seems that it won't be compatible with prometheus, so let's remove it. What worth adding is that fields with `DCGM_FT_STRING` or `DCGM_FT_BINARY` are incompatible with prometheus and shouldn't be added

2024-09-30 14:49 UTC, gabrielcocenza approved these changes

2024-10-02 01:28 UTC, samuelallan72 submitted a review, later dismissed

2024-10-02 02:00 UTC, samuelallan72 approved these changes

2024-10-02 17:52 UTC, gabrielcocenza approved these changes

2024-10-02 18:56 UTC, aieri approved these changes

2024-10-02 19:32 UTC, merged