Migrate smartctl-exporter from deb package to snap package
canonical/hardware-observer-operator pull request #327
Opened 2024-09-25 08:23 UTC by chanchiwai-ray

2024-09-25 08:25 UTC, chanchiwai-ray commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
snap_client need to be update every time snap operation is performed.

```
s = snap.SnapCache()["smartctl-exporter"]
s.present  # returns False
snap.add("smartctl-exporter", channel="latest/candidate")
s.present  # still returns False

s = snap.SnapCache()["smartctl-exporter"]
s.present  # now returns True
```

2024-09-25 08:25 UTC, chanchiwai-ray commented on config.yaml
> +    default: "latest/candidate"  # fix me
wait until latest/stable

2024-09-25 12:30 UTC, gabrielcocenza reviewed
Nice to see that the code is getting less complex with the usage of snaps.

Please add unit tests for the `SmartCtlExporter`

2024-09-25 12:30 UTC, gabrielcocenza commented on config.yaml
> +    default: "latest/candidate"  # fix me
I think you can leave as latest/stable. What will happen is that the hardware-observer will be at blocked state saying that it was not possible to install it

2024-09-25 12:30 UTC, gabrielcocenza commented on src/service.py
> +        )
Don't you need to restart the services after changing the config to takw place?

2024-09-26 01:08 UTC, samuelallan72 commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
Nice find!

Can we consider now using `@property` here please?  That makes it clearer that it's a method, that it does logic every time it's called, that it can't be assigned to, etc.

2024-09-26 01:14 UTC, samuelallan72 commented on src/service.py
> +        return super().configure() and self.set(
(out of scope for this PR) By the way, I can't see anything that actually uses the return value from configure, install, or uninstall.  That might be a nice refactoring soon - remove the return value.  I reckon we can rely on errors raised, rather than a return value.

2024-09-26 01:51 UTC, chanchiwai-ray commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
> Can we consider now using @property here please? That makes it clearer that it's a method, that it does logic every time it's called, that it can't be assigned to, etc.

I am not sure what do you mean here, we are now using `@property` here

2024-09-26 01:53 UTC, chanchiwai-ray commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
> Nice find! Could you add the info about about why it needs to be re-called each time to ensure fresh information? Also I'm wondering about this because it's SnapCache - maybe there's an explicit method to update the cache too to be sure?

`s.present` points to a static data structure, and it's not being updated as you run `snap.add`

2024-09-26 01:54 UTC, chanchiwai-ray commented on src/service.py
> +        )
the snap hook handles it

2024-09-26 01:54 UTC, samuelallan72 commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
Ah sorry, some typos...

> I am not sure what do you mean here, we are now using @property here

I meant to type "Can we consider **not** using `@property` here"

> s.present points to a static data structure, and it's not being updated as you run snap.add

Yep, I meant could you add that info to the method docstring for future reference?

:sweat_smile:

2024-09-26 01:55 UTC, chanchiwai-ray commented on src/service.py
> +        return super().configure() and self.set(
the method name itself confuses me too: it's named `configure` but internally run `install`

2024-09-26 03:46 UTC, chanchiwai-ray commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
I feel like "property" is just a syntactic sugar, and it does exactly what you requested here. To be clear, I am trying to be consistent with the existing codebase: `get_snap_client` inside `SnapExporter` will break the consistency of the this class, which is an encapsulation of a "snap" that handle the lifecycle of the itself. A `get_snap_client` is more like something should be done outside the `SnapExporter`. May be a refactor is better for this purpose. WDYT?

2024-09-26 03:59 UTC, chanchiwai-ray commented
> We need to consider how to migrate from older version of hardware-observer to this new version. If you want to separate them into 2 PRs. I suggest we can work on a dev branch and merge them together.

@Pjack now is fixed

2024-09-26 04:33 UTC, samuelallan72 commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
Sure probably.  You'll need to refactor some things anyway, because some mocks in the unit tests expect that .snap_client is a real property, not a fake one.

2024-09-26 08:07 UTC, chanchiwai-ray commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
👍🏼 I think in this case we won't need to change unit test if we are using property, but will need to update unit test if we are using it as a function which will deviate the scope of the PR.

2024-09-26 08:09 UTC, samuelallan72 commented on src/service.py
> +        return snap.SnapCache()[self.strategy.snap]
Ah ok, if the unit tests still work, that's cool - I'm surprised they work still. :+1:

2024-09-26 08:15 UTC, samuelallan72 requested changes

2024-09-26 09:32 UTC, chanchiwai-ray commented on src/hw_tools.py
> +def remove_legacy_smartctl_exporter_deb(stored_tools: set) -> None:
Not quite, `smartmontools` is from apt

2024-09-26 09:38 UTC, chanchiwai-ray commented on src/hw_tools.py
> +def remove_legacy_smartctl_exporter_deb(stored_tools: set) -> None:
updated

2024-09-26 13:08 UTC, gabrielcocenza commented on src/service.py
> +        return super().configure() and self.set(
That happens because the snap lib uses install for both install or refresh, so i would be ok changing the name to be more explicit about this

2024-09-26 13:31 UTC, gabrielcocenza requested changes

2024-09-26 13:31 UTC, gabrielcocenza commented on src/hw_tools.py
> +def remove_legacy_smartctl_exporter(stored_tools: set) -> None:
```suggestion
def remove_legacy_smartctl_exporter(stored_tools: Set[HWTool]) -> None:
```

2024-09-26 13:31 UTC, gabrielcocenza commented on src/hw_tools.py
> +        stored_tools.remove("smartctl")
I don't enjoy at all doing this by reference. It's dangerous IMO. Please move this removal to the `get_stored_tools` to be more explicit

2024-09-26 13:31 UTC, gabrielcocenza commented on src/hw_tools.py
> +    smartctl_exporter_service_path = Path(f"/etc/systemd/system/{name}.service")
Can't you also remove the `smartmontools` deb package once this is shipped in the exporter snap?

2024-09-26 23:03 UTC, samuelallan72 commented on src/hw_tools.py
> +def remove_legacy_smartctl_exporter_deb(stored_tools: set) -> None:
Thanks :)

2024-09-26 23:44 UTC, samuelallan72 commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("legacy_exists", [True, False])
nit: I'd prefer this parametrize was removed, so we can remove the conditional if/else in the test.  We can replace this test with two tests that don't have control flow logic, for simplicity and clarity.

2024-09-27 02:53 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    smartctl_exporter_service_path = Path(f"/etc/systemd/system/{name}.service")
We can't and shouldn't. This tool can be installed by the operators itself, removing it might cause unexpected behavior: see original `remove` for this strategy (I remember someone point this out in one of the issues)

2024-09-27 02:53 UTC, chanchiwai-ray commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("legacy_exists", [True, False])
Updated

2024-09-27 03:18 UTC, chanchiwai-ray commented on src/hw_tools.py
> +        stored_tools.remove("smartctl")
updated

2024-09-27 03:18 UTC, chanchiwai-ray commented on src/hw_tools.py
> +def remove_legacy_smartctl_exporter(stored_tools: set) -> None:
It does not take arg anymore

2024-09-27 05:12 UTC, samuelallan72 approved these changes

2024-09-27 07:29 UTC, chanchiwai-ray commented on src/service.py
> +        )
Resolving as it seems this is clear now

2024-09-27 07:32 UTC, chanchiwai-ray commented on config.yaml
> +    default: "latest/candidate"  # fix me
@Pjack need you input here. Do you know the ETA for this? If not, I think it's okay to leave it as latest/candidate to avoid backward incompatibility. @gabrielcocenza A non-installable snap will break charm refresh

2024-09-27 07:34 UTC, jneo8 submitted a review, later dismissed

2024-09-27 10:19 UTC, Pjack submitted a review, later dismissed

2024-09-27 10:21 UTC, Pjack commented on config.yaml
> +    default: "latest/candidate"  # fix me
I plan to push the snap to stable channel after we finish the testing.

2024-09-27 12:40 UTC, gabrielcocenza approved these changes

2024-09-27 12:40 UTC, gabrielcocenza commented on src/charm.py
> +            self._stored.stored_tools.remove("smartctl")  # type: ignore[attr-defined]
nit:

You could use discard that would avoid checking it first to not raise Keyerror, but not big deal

Also I think it worth a comment why we are doing this (maybe we can  remove it in the future)

2024-10-01 01:38 UTC, samuelallan72 approved these changes

2024-10-02 04:08 UTC, chanchiwai-ray commented on src/charm.py
> +            self._stored.stored_tools.remove("smartctl")  # type: ignore[attr-defined]
These code should not exists for long, and only happens during a refresh, I think we can leave it as it is.

2024-10-02 04:08 UTC, chanchiwai-ray commented on config.yaml
> +    default: "latest/candidate"  # fix me
Promoted to stable

2024-10-02 04:08 UTC, chanchiwai-ray commented on src/service.py
> +        return super().configure() and self.set(
That could be a refactoring in the future

2024-10-02 05:40 UTC, merged