Fix write_to_file function
canonical/hardware-observer-operator pull request #336
Opened 2024-10-11 21:46 UTC by gabrielcocenza

Probably, because of a racing condition, sometimes the file was written into inconsistent state which breaks the configuration and the hardware-exporter service.

After adding a file lock and detaching the permission from writting, the bug seems to be fixed

Closes: #305

2024-10-14 01:25 UTC, jneo8 reviewed
Thanks, overall LGTM. Need more information on `os.chmod` part.

2024-10-14 01:25 UTC, jneo8 commented on src/service.py
> +            os.chmod(path, mode)
**question (non-blocking):** 

Can you add more information why change `os.open(path, os.O_CREAT | ...)` to `os.chmod`?

2024-10-14 12:20 UTC, gabrielcocenza commented on src/service.py
> +            os.chmod(path, mode)
Is it necessary?

In the end of the day what we want is to create or overwrite a file with a certain permission and I think this logic is simpler to understand.

2024-10-15 00:36 UTC, samuelallan72 requested changes
> Probably, because of a racing condition,

I feel like if we have race conditions where code is trying to write to the same file at the same time, then we should fix the source, not just add file locking. It may require a refactor to only write out the config from one place. It would be nice to do some more debugging and find the source of the race condition here.

2024-10-15 00:36 UTC, samuelallan72 commented on src/service.py
> +            os.chmod(path, mode)
Agreed, using `os.chmod` is much clearer than the ternary statement with the lesser-known os.fdopen and os.open calls.

2024-10-15 02:23 UTC, jneo8 approved these changes

2024-10-15 02:23 UTC, jneo8 commented on src/service.py
> +            os.chmod(path, mode)
Because this remind me that we have reverse change in the past: https://github.com/canonical/hardware-observer-operator/pull/225/commits/8260938168091225a1387bbc35e6451db25c0be9

It's ok to change it if the behavior is equal and you think it's more simpler. I just want to know if you have another concern.

2024-10-15 21:17 UTC, gabrielcocenza commented
> I feel like if we have race conditions where code is trying to write to the same file at the same time, then we should fix the source, not just add file locking. It may require a refactor to only write out the config from one place. It would be nice to do some more debugging and find the source of the race condition here.

I tested again and removing the lock file, but keeping the implementation seems to solve the issue. I didn't see in the logs more than one hook triggering the `write_to_file` function.

I'm not sure about the root cause. My guess is that `os.open` is a low-level system call. Maybe when you wrap the file descriptor in os.fdopen(), you're attempting to treat a low-level file descriptor as a higher-level file object, but subtle issues can occur if the file descriptor isn't handled perfectly (e.g., file not properly synced, buffers not flushed).

I believe that keeping things simple and using more high level python functions are enough to solve the issue

2024-10-15 22:29 UTC, samuelallan72 commented on src/service.py
> +            os.chmod(path, mode)
Hmm I'm not sure why we switched to that before. Either way, by @gabrielcocenza's testing, it certainly seems safer to only use the high level `open` function.

Also a benefit of separately using `os.chmod`, is that we can guarantee that the mode will be set. `os.open` doesn't guarantee it: [Open the file path and set various flags according to flags and **possibly its mode** according to mode](https://docs.python.org/3/library/os.html#os.open). So perhaps it won't set it if the file already exists? I'm not sure.

2024-10-15 22:32 UTC, samuelallan72 approved these changes
Thanks for experimenting! It's nice that we can go with something even simpler than the previous implementation and solve the bug at the same time. :+1:

2024-10-15 22:32 UTC, samuelallan72 commented on src/service.py
> +        if mode:
```suggestion
        if mode is not None:
```

Technically we should compare with None here, because just checking for truthy value will fail if the user specifically sets `mode=0o000`. In practice though this doesn't make sense, so fine to leave as-is.

2024-10-16 19:33 UTC, Deezzir submitted a review, later dismissed
Legit

2024-10-16 22:01 UTC, aieri submitted a review, later dismissed

2024-10-16 22:45 UTC, samuelallan72 commented on src/service.py
> +        os.chmod(path, mode)
Did you want these within the try block too? Touch and chmod can both fail with similar errors.

2024-10-16 23:58 UTC, Deezzir commented on tests/unit/test_service.py
> +        final_content = path.read_text()
I would inline this

2024-10-17 01:16 UTC, jneo8 commented on src/service.py
> +    path.touch()
**question:** 

What will happen if file already exists?

2024-10-17 01:19 UTC, samuelallan72 commented on src/service.py
> +    path.touch()
It will still succeed; touch is idempotent as far as I know. If the file already exists, the modification timestamp will be updated.

2024-10-17 01:19 UTC, jneo8 commented on src/service.py
> +    path.touch()
Thanks for explain.

2024-10-17 01:21 UTC, samuelallan72 commented on src/service.py
> +    path.touch()
Ah I found the official doc for pathlib.touch: https://docs.python.org/3/library/pathlib.html#pathlib.Path.touch :)

2024-10-17 13:09 UTC, gabrielcocenza commented on src/service.py
> +        os.chmod(path, mode)
Yep, guess you are right. Moved to the try block.

2024-10-17 14:21 UTC, Deezzir approved these changes

2024-10-17 15:07 UTC, gabrielcocenza commented on tests/unit/test_service.py
> +        prior_permission = path.stat().st_mode & 0o777
This seem to return the result into decimal, which is OK, but I prefer into oct that shows what usually we pass like `0o666`

2024-10-17 16:02 UTC, aieri approved these changes

2024-10-17 18:22 UTC, merged