Add nouveau check and modprobe to install
canonical/hardware-observer-operator pull request #359
Opened 2024-11-30 03:00 UTC by Deezzir

The PR fixes some issues with the current Nvidia driver install logic:

- There is a check for nouveau drivers; if they are present, tell the operator. Otherwise, there is no point in installing Nvidia's closed-source drivers, as the Nvidia module slot is already occupied
-  Change the order of the arguments passed to `ubuntu-drivers`; see https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/2090502 - hilarious
- Run `modprobe` to load the installed drivers, ensuring a reboot is unnecessary. 

The changes were tested on a testflinger machine.

2024-12-02 13:05 UTC, gabrielcocenza submitted a review, later dismissed

2024-12-02 14:04 UTC, Deezzir commented on src/hw_tools.py
> +        if 0 == subprocess.call("lsmod | grep nouveau", shell=True):
Some

2024-12-02 19:12 UTC, aieri requested changes
A couple of suggestions, and we'll need unit tests (but I know you know this :))

2024-12-02 19:12 UTC, aieri commented on src/hw_tools.py
> +        if 0 == subprocess.call("lsmod | grep nouveau", shell=True):
non-blocking: lsmod is just a pretty printer for `/proc/modules`, so I would suggest skipping subprocess and simply reading that file

2024-12-02 19:12 UTC, aieri commented on src/hw_tools.py
> +            subprocess.call("modprobe nvidia".split())
`call` will not throw exceptions for non-zero RCs. Are you sure you don't mean to use `check_call`?

2024-12-02 19:35 UTC, Deezzir commented on src/hw_tools.py
> +            subprocess.call("modprobe nvidia".split())
Yes, it's intentional, I don't want to handle any errors from the modpobe. It should only fail if there is nothing to load or something is already installed, like no nouveau. We handle those cases + plus the charm will check if the driver is loaded by looking at `/proc/driver/nvidia/version `

2024-12-02 19:36 UTC, Deezzir commented on src/hw_tools.py
> +            subprocess.call("modprobe nvidia".split())
But I guess we can be a little bit more explicit, wdyt

2024-12-02 23:38 UTC, aieri approved these changes

2024-12-03 13:41 UTC, gabrielcocenza approved these changes

2024-12-03 16:10 UTC, merged