Don't install DCGM if the driver has been blacklisted
canonical/hardware-observer-operator pull request #363
Opened 2024-12-04 23:26 UTC by aieri

If the sysadmin wants to pass the gpu to a virtual instance via pci
passthrough, they will need to make the gpu unavailable to the host
system by blacklisting[0] the kernel driver. On such a system DCGM would
not be able to function and should therefore not be deployed.

This commit makes the NVIDIA gpu verifier more strict by only marking
DCGM as an available tool if both an NVIDIA gpu is detected *and* the
kernel module is not blacklisted.

[0] https://wiki.debian.org/KernelModuleBlacklisting

2024-12-05 01:00 UTC, Deezzir requested changes

2024-12-05 01:00 UTC, Deezzir commented on src/hw_tools.py
> +                for line in fd.readline():
I think it is also okay to use `fd.read()`; the files shouldn't be that big to take advantage of line-by-line parsing.

2024-12-05 01:28 UTC, aieri commented on src/hw_tools.py
> +    for conffile in chain(iglob("/etc/modprobe.d/*.conf"), "/etc/modprobe.conf"):
you're right, I had checked it in ipython and then forgot to update the actual file XD

2024-12-05 03:25 UTC, aieri commented on src/hw_tools.py
> +                for line in fd.readline():
yeah that's true, but doesn't looking line per line keep the regex matching cleaner?

2024-12-05 08:28 UTC, d-kazantsev commented on src/hw_tools.py
> +                for line in fd.readline():
In my case I can not find blacklisting info in any of the files under /etc/modprobe.d. I'm blacklisting Nvidia drives using kernel parameters  during boot: 

BOOT_IMAGE=/boot/vmlinuz-6.8.0-48-generic root=/dev/mapper/vg0-lvroot ro console=tty0 console=ttyS0,115200n8 nvme_core.multipath=0 modprobe.blacklist=nouveau,nvidiafb

Wouldn't it be better to utilize lshw output and check if UNCLAIMED is present for NVIDIA GPU?

"a node is marked as UNCLAIMED if no specific support for it has been loaded (or lshw has been unable to identify the driver)"

2024-12-06 02:09 UTC, jneo8 reviewed
Thank you for the implementation!

Based on the code review (note: I haven’t tested it), I believe we’re at a good point to start adding unit tests.

2024-12-06 02:09 UTC, jneo8 commented on src/hw_tools.py
> +    # * we don't know the full name of the module
**polish:** 

I think this should be doc-string instead of comment.
(Also applicable to below functions)

2024-12-06 02:46 UTC, aieri commented on src/hw_tools.py
> +                for line in fd.readline():
iiuc by peeking at the lshw source code, a device is declared claimed if it has a corresponding logical name under `/dev/`, which only implies that the driver hasn't been loaded, and not necessarily that the driver _cannot_ be loaded.

hardware observer will attempt to install and load a suitable NVIDIA driver if it detects a gpu; I think that if we gated that behavior behind the gpu having been claimed (i.e. having some sort of driver loaded) we could not handle the transition (no driver, empty blacklist) → (NVIDIA driver installed and loaded)

My assumption could however be incorrect if it is always true that in the absence of an explicit blacklisting an NVIDIA gpu will always be claimed via the nouveau driver...

...and since `linux-generic` depends on `linux-modules-extra-$(uname -r)`, which contains `nouveau.ko.zst`, you may be right: no matter how minimal an Ubuntu installation, you will always at least load nouveau.

2024-12-07 04:38 UTC, aieri commented on src/hw_tools.py
> +                for line in fd.readline():
after thinking some more about this, I would prefer to continue looking at blacklisting via the various ways it can be configured instead of relying on lshw. This is because while the claimed/unclaimed behavior could be used to determine if the driver has been blacklisted, it is only so due to a set of side effects. Additionally, you could theoretically imagine a setup with nouveau being blacklisted and no nvidia driver being installed: in that case the gpu would be unclaimed and yet hardware observer should go ahead and deploy the proprietary driver and DCGM.

2024-12-07 04:39 UTC, aieri commented on tests/unit/test_hw_tools.py
> +    )
this feels ridiculous and only necessary to hit 100% coverage. Any better ideas?

2024-12-09 12:13 UTC, gabrielcocenza approved these changes
Small suggestion, but LGTM.

2024-12-09 12:13 UTC, gabrielcocenza commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("cmdline_bool", [True, False])
A single parametrize makes easier to test all scenarios
```suggestion
@pytest.mark.parametrize("modprobe_bool, cmdline_bool, excpected", [(True, True, True), (True, False, True), (False, False, True)])
```

2024-12-09 12:13 UTC, gabrielcocenza commented on tests/unit/test_hw_tools.py
> +    )
Nope :sweat_smile: . I would do the same

2024-12-09 18:34 UTC, aieri commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("cmdline_bool", [True, False])
yes, but flattening would mean that I have to calculate all the combinations myself (and in fact you're missing `(False, True, True)` ;))

2024-12-09 23:03 UTC, samuelallan72 commented on tests/unit/test_hw_tools.py
> +    )
We could drop the 100% coverage requirement to a more reasonable requirement (90%? 95%?). That could avoid something ridiculous just to satisfy the metric.

2024-12-10 01:23 UTC, gabrielcocenza commented on tests/unit/test_hw_tools.py
> +    )
> We could drop the 100% coverage requirement to a more reasonable requirement (90%? 95%?). That could avoid something ridiculous just to satisfy the metric.

Maybe adding a tag like `# pragma: no cover` can skip this part that does not need to test it

2024-12-10 02:27 UTC, jneo8 approved these changes
LGTM if we follow Gabriel's suggestion on unit test.

2024-12-10 02:27 UTC, jneo8 commented on tests/unit/test_hw_tools.py
> +    assert _is_nvidia_module_blacklisted_via_cmdline() == expect
**praise:** 

Nice one here.

2024-12-10 02:27 UTC, jneo8 commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("cmdline_bool", [True, False])
I support Gabriel's suggestion.

The key here is to declare the possible variables and expected return values explicitly. Otherwise, it results in a redundant implementation within the unit test.

2024-12-10 02:35 UTC, chanchiwai-ray commented on tests/unit/test_hw_tools.py
> +    )
just an alternative, if you don't `@mock.patch("hw_tools._is_nvidia_module_blacklisted")` (it's just a high level wrapper) in `test_nvidia_gpu_verifier`, but patch the underlying `_is_nvidia_module_blacklisted_via_*`, you probably don't need this test case. Still, you will need to parameterized them in `test_nvidia_gpu_verifier`

2024-12-10 02:43 UTC, chanchiwai-ray commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("cmdline_bool", [True, False])
I think Andrea's implementation is better and simpler since it's a Cartesian product of two variables. At the same time, I think James concern is also valid, line 972 is exactly the same as the code, and it just feels weird that we are some asserting the expected result

2024-12-10 14:17 UTC, Deezzir approved these changes
LGTM

2024-12-11 03:17 UTC, aieri commented
not merging yet because manual tests show that updating to this charm version forces the driver to be installed and loaded, despite the blacklisting

2024-12-12 02:05 UTC, aieri commented
one possible hacky way to handle the upgrade issue would be to do something like this in `_on_install_or_upgrade`:
```
if HWTool.DCGM in self.stored_tools and not nvidia_gpu_verifier():
    self.stored_tools.remove(HWTool.DCGM)
```
(basically a gpu-specific hardware redetection round)

2024-12-12 06:14 UTC, jneo8 commented
> one possible hacky way to handle the upgrade issue would be to do something like this in `_on_install_or_upgrade`

Need to be very careful about this proposal. This somehow means run the detect function every time when hook is triggered.

> not merging yet because manual tests show that updating to this charm version forces the driver to be installed and loaded, despite the blacklisting

I believe this issue occurs because the list of HWTool included the GPU prior to the upgrade.  

It’s a bit of a chicken-and-egg problem—you’ll need a way to clean the local state to prevent this from happening.

New deployed unit won't encounter this.

I have couple proposals:

- Ask people to redeploy the juju unit. Since the origin issue is a edge case and new deployment won't encounter this after merging. It can be a lowest effort option for us.
- Provide --clean-resource argument to the re-detect action, which will remove the unused resource on the machine. User encounter this issue can be simple fixed by running the action.
- Run re-detect every time on install/upgrade hook, this may be lowest priority option since changing the life-cycle make it become more not stable.

2024-12-12 06:47 UTC, samuelallan72 commented
Drive by comment: how expensive is it to detect the tools? Perhaps we can build the tools list on every charm hook, rather than using stored state?

2024-12-12 06:56 UTC, jneo8 commented
> Drive by comment: how expensive is it to detect the tools? Perhaps we can build the tools list on every charm hook, rather than using stored state?

We did this in the past and encounter an issue that some unstable hardware just you different result every time you run re-detect. I will suggestion not dig into the same hole again.

2024-12-14 00:37 UTC, aieri commented on tests/unit/test_hw_tools.py
> +@pytest.mark.parametrize("cmdline_bool", [True, False])
given the lack of agreement and blocking requests for changes I'll keep this as is

2024-12-14 00:38 UTC, aieri commented
ok, I've tested that at least the upgrade scenario from rev 84 (pre-dcgm) works fine. Further cleanups would require changing how and when we do hw redetection, which is a much bigger endeavor than this change

2024-12-14 00:39 UTC, merged