Stop managing the installation of the NVIDIA driver.
canonical/hardware-observer-operator pull request #380
Opened 2024-12-18 02:07 UTC by aieri

While we initially provided automatic installation of the NVIDIA driver
as a convenience, we then ran into the complexity of dealing with users
wanting to configure pci-passthrough and/or vgpu, and to possibly move
across these configurations post-deployment (see #362, #379).

After some more discussions, we agreed that deploying a gpu driver is
not the responsibility of hardware-observer, but rather of the principal charm
that needs to use the gpu (e.g. nova or kubernetes-worker).

This commit therefore drops the functionality of automatically
installing the driver and determining if it has been blacklisted for a
simpler workflow of installing DCGM only if a driver is found to have
been installed and loaded.

Fixes: #379

2024-12-18 02:35 UTC, jneo8 requested changes
(Need clarification)
I see your approach overall.

However I have some concerns about the user experience that I feel haven't been fully addressed in this PR:

- If a GPU is detected but no driver is found, should the charm enter a "blocked" status? I think this needs clarification.

- (Optional) I believe there’s still value in having hw-observer assist users with GPU driver installation. It could be provided as an optional Juju action to enable automatic driver installation.

2024-12-19 01:41 UTC, jneo8 commented
> No, I don't think we should enter a blocked state regardless of presence or absence of a gpu. We should deploy dcgm when we see an NVIDIA gpu, and not deploy it / remove it where we don't (the removal part is not automated, TBD, and out of scope for this PR).

The key point here is: how does the user realize they need to install the driver? Unlike other hardware tools, the user experience with hw-observer aims to proactively guide users by reminding them of all the necessary manual operations they need to complete.

2024-12-19 02:20 UTC, jneo8 approved these changes
Thanks. LGTM.

2024-12-19 02:21 UTC, Deezzir approved these changes
Thanks

2024-12-19 02:59 UTC, merged