Replace redfish discover method
canonical/hardware-observer-operator pull request #69
Opened 2023-10-02 05:06 UTC by dashmage

`redfish.discover_ssdp` method is replaced with a simple login call to the redfish service. If the `RetriesExhaustedError` exception is raised, we can infer that the redfish service isn't present on the system.

This is done because the `redfish.discover_ssdp` method finds all the redfish services on the same network which is not what we want.

Fixes #61.

2023-10-02 05:22 UTC, dashmage commented
Unit tests failing on GH CI for test coverage reasons but doesn't fail on my local :confused: 

![image](https://github.com/canonical/hardware-observer-operator/assets/25390807/862ecddc-d58b-47a1-a241-699c497b3ea8)

2023-10-02 07:27 UTC, jneo8 commented
> Unit tests failing on GH CI for test coverage reasons but doesn't fail on my local 😕
> 
> ![image](https://user-images.githubusercontent.com/25390807/271887696-862ecddc-d58b-47a1-a241-699c497b3ea8.png)

The failing is because of the coverage missing.

2023-10-02 07:31 UTC, jneo8 requested changes
LGTM but please provide more unit tests to make unit test coverage be 100%.

2023-10-02 07:31 UTC, Pjack requested changes
There is no unit test of redfish_available, any reason to skip it?

2023-10-02 07:31 UTC, Pjack commented on src/hw_tools.py
> +        redfish_obj = redfish_client(base_url=host, username=user, password=pwd)
What's the default value of username and password? If it is "None" or "", we can avoid the local variable "user" and "pwd".

2023-10-03 05:41 UTC, dashmage commented on src/hw_tools.py
> +        redfish_obj = redfish_client(base_url=host, username=user, password=pwd)
Good point. Addressed this in the latest commit.

2023-10-03 05:41 UTC, dashmage commented
Added unit tests for new function.

2023-10-05 04:58 UTC, Pjack approved these changes
LGTM

2023-10-05 06:40 UTC, sudeephb approved these changes
LGTM

2023-10-05 08:35 UTC, jneo8 approved these changes

2023-10-05 08:55 UTC, merged